### ISSUE TITLE
Translation spanish not work

### ISSUE THREAD

**Issue by Lazarojunior** [surveyjs/editor#100]
### Are you requesting a feature, reporting a bug or ask a queation?
Bug

### What is the current behavior?
Translater for spanish not working.

### How would you reproduce the current behavior (if this is a bug)?

The file 'editor/src/localization/spanish.ts' is in wrong syntax. At the end of the line you have to use the ',' character, you are using ';'.

See the example below:

var spanishTranslation: {
    // strings for survey templates
    survey: {
        dropQuestion: "Por favor coloque una pregunta aquí";
        copy: "Copiar";
        addToToolbox: "Agregar al toolbox";
        deletePanel: "Eliminar panel";
        deleteQuestion: "Eliminar pregunta";
    };

#### Provide the test code and the tested page URL (if applicable)
Tested page URL:
Test code
your_code_here

### Specify your

* browser:
* editor version:

**Comment by andrewtelnov** [comment]
@Lazarojunior Yes, how could I missed that!

Thank you,
Andrew
