### ISSUE TITLE
Event Handler stop working when switching tabs

### ISSUE THREAD

**Issue by traquall** [surveyjs/editor#101]
### Are you requesting a feature, reporting a bug or ask a question?

bug

### What is the current behavior?

When I switch tabs from "designer" to "Edit JSON", events handler on SurveyEditor.survey disappears.

### What is the expected behavior?

Events handler still work after changing tabs

### How would you reproduce the current behavior (if this is a bug)?

Add an event handler on editor.survey, then switch tab to "Edit JSON", switch back to the designer and the event handler doesn't work anymore.

-> Event handler on editor (like onModified, onQuestionAdded) works fine after switching tabs

#### Provide the test code and the tested page URL (if applicable)

    var editor = new SurveyEditor.SurveyEditor("surveyEditorContainer", editorOptions);

    editor.survey.onCurrentPageChanged.add(function(sender, options){
        console.log("pageChanged");
    });

### Specify your

* browser: Chrome
* editor version:

**Comment by andrewtelnov** [comment]
@traquall Editor re-creates the survey in designer in several different situations. I have added a new event: onDesignerSurveyCreated, where options.survey is the survey in the designer.
Please use this event to setup the event handler for the survey.
It is available in the dev version: https://surveyjs.azureedge.net/dev/surveyeditor.js

Thank you,
Andrew

**Comment by traquall** [comment]
Thank you @andrewtelnov !!
