### ISSUE TITLE
Localisation of Validator types

### ISSUE THREAD

**Issue by joshreid** [surveyjs/editor#104]
Hi @andrewtelnov 
Can we localise the Validator type strings for improved experience?

<img width="374" alt="screen shot 2017-06-07 at 9 40 07 pm" src="https://user-images.githubusercontent.com/167671/26872429-9e94f956-4bca-11e7-9a86-59b7e9cb2f6e.png">

Any thoughts be much appreciated.

**Comment by andrewtelnov** [comment]
@joshreid Sure, I will do it right now. I am working on improving editor localization at the current moment. I have missed it, and triggers...

Thank you,
Andrew

**Comment by joshreid** [comment]
Legend, thanks Andrew!
