### ISSUE TITLE
Small Bug/Typo: Embed CDN

### ISSUE THREAD

**Issue by grinfax** [surveyjs/editor#105]
In the embed code of the survey editor is shows the CDN address as: 
`<script src="https://surveyjs.azureedge.net/0.12.17/survey.jquery .min.js"></script>`

when it should be: 

`<script src="https://surveyjs.azureedge.net/0.12.17/survey.jquery.min.js"></script>`

Remove space betwen jquery and .min

**Comment by andrewtelnov** [comment]
@grinfax Yes, thank you, The fix will be available in the next update.

Thank you,
Andrew
