### ISSUE TITLE
Dynamically add questions parameters

### ISSUE THREAD

**Issue by traquall** [surveyjs/editor#107]
### Are you requesting a feature, reporting a bug or ask a question?

Feature

### What is the current behavior?

As far i know, for the moment we can add parameter to a type of question before the designer is created.

### What is the expected behavior?

I'd like to dynamically add parameter to a question in order to add as many parameter as response choices and being able to see it in the json result

Thanks a lot !

**Comment by andrewtelnov** [comment]
@traquall Could you please describe your scenario in more details?

Thank you,
Andrew

**Comment by traquall** [comment]
I need to add an indication on every response choices to get them in the json result, but as the number of responses is variable , I can't just add property to all radioGroup buttons.
So i need to add properties dynamically when the user adds a choices or remove a property when he remove a choice.

I don't know if this was more clear ... 
Thanks again :)

**Comment by andrewtelnov** [comment]
@traquall I wish I could understand the problem you are trying to solve :)
Do you want to add new values into result JSON based on the answers? In this case onValueChanged event you may call survey.setValue("mydynamicValue", myValue); This value will be in the result JSON.

Thank you,
Andrew

**Comment by traquall** [comment]
@andrewtelnov I wish someone could understand the problem ^^' I have some trouble explaining this one , i'll make an example.

I'm creating a survey with a radioGroup question and i need that for every response choices there is a property on the question (in order to add "tips" on responses when i'll use this survey).
So i need 3 properties when I create the question (prop1, prop2, prop3)
if i add a response choices, I'll need 4 (prop 1, ... prop4)
if i remove a response, I'll need 2.

And I don't know how to add properties that are visible on the question editor and on the json result.

Is it better? :p
Thank you

**Comment by andrewtelnov** [comment]
@traquall OK. I think I've got you.
Here is what you have to do:
1) Add all properties into the radiogroup question type: https://www.surveyjs.io/Editor/examples/addproperties.html#code
2) Use onCanShowProperty event to hide/show your custom properties: https://www.surveyjs.io/Editor/examples/removeproperties.html#code

Let me know if it works for you.

Thank you,
Andrew

**Comment by traquall** [comment]
@andrewtelnov Thank you :) you got me !

**Comment by traquall** [comment]
@andrewtelnov just one last thing ^^' 
It works very well but after I add a choice I need to click somewhere else before the question to see new visible properties.
Where and how can i reload the view ? 
I tried to add "editor.text = editor.text;" that works well with "onPageChanged" event to reload the view but "onCanShowProperty" is called too much.

Here's my code for onCanShowProperty :

```
editor.onCanShowProperty.add(function(sender, options){
		var canShow = false;
		
	    if(options.obj.getType() == "radiogroup") {
	    	for(var i = 1;i<=options.obj.choices.length; i++){
	    		if(options.property.name == "response indic "+i){
	    			canShow = true;
	    		}
	    	}	    		  
	    }
	    if(propList.includes(options.property.name)){
    		canShow = true;
    	}
	    options.canShow = canShow;
	});
	editor.render("editorElement");
```

**Comment by andrewtelnov** [comment]
@traquall Yes, objectEditor (shows the list of properties) has the objectChanged method. Unfortunately, it is not accessible outside the editor right now.  I will make it available right now...

**Comment by traquall** [comment]
@andrewtelnov 
Thank you so much for your work !
Best customer service I've ever seen :)

**Comment by andrewtelnov** [comment]
I may update the editor dev version on https://github.com/surveyjs/builds/, if you want to play with it right now. Just let me know. 
You will have to add the following code:
`editor.selectedObjectEditor.objectChanged(); `
It will update the properties of the selected object.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@traquall Anyway the dev version is updated, you may use it as: 
https://surveyjs.azureedge.net/dev/surveyeditor.min.js

**Comment by traquall** [comment]
@andrewtelnov  
Do I need to add it at the end of "onCanShowProperty" ?
I tried this, it didn't update properties and create an error when i click on rating questions :
"Uncaught TypeError: Cannot read property 'length' of undefined"

**Comment by andrewtelnov** [comment]
@traquall You will have to do the following:
```
editor.selectedObjectEditor.onPropertyValueChanged.add((sender, options) => {
            ///options.property, options.object, options.newValue
           /// based on properties above  call
          editor.selectedObjectEditor.objectChanged();
});
```

**Comment by traquall** [comment]
@andrewtelnov 
onPropertyValueChanged doesn't trigger when I add response choices :/

**Comment by andrewtelnov** [comment]
@traquall There is a onItemValueAdded event:
editor.onItemValueAdded.add((sender, options) => {
      //options.propertyName
      //options.itemValue
      editor.selectedObjectEditor.objectChanged();
});
I may add onItemValueRemoved and onItemValueUpdated if needed.

**Comment by traquall** [comment]
@andrewtelnov I tried it and the object editor don't show the new property until I click somewhere else, but I can see that the number of choices has changed

**Comment by andrewtelnov** [comment]
@traquall ok, I will try to make a demo. Probably I will have to change something in the code to make it work.

**Comment by traquall** [comment]
@andrewtelnov It's not very important ^^ i'm good like this is

**Comment by traquall** [comment]
@andrewtelnov Thanks

**Comment by andrewtelnov** [comment]
ok :-)
