### ISSUE TITLE
Limit the number of checkboxes selected by users

### ISSUE THREAD

**Issue by boitaumail** [surveyjs/editor#108]
Hi everyone,

# Are you requesting a feature, reporting a bug or ask a queation?
Question

### What is the current behavior?
Today, I can choose multiple choice question (checkbox) or single choice question (radiogroup)

### What is the expected behavior?
I would like a checkbox question with un limited number of answers. Is there a way to do it ?
eg : A question like : "Choose the 2 mains topics that you would like to see in our website ?"
- item 1
- item 2
- item 3
- item 4

If the user select more than 2 items, it throw an error (or something to limit his choice).

Thank you.

**Comment by andrewtelnov** [comment]
@boitaumail The easiest solution right now is to use [onValidateQuestion event](http://surveyjs.org/docs/api_surveymodel.html#onValidateQuestion).
Here is the demo, that does exactly what you want: https://plnkr.co/edit/HooHtas3ooFVcUu3kC1O?p=preview

PS: Please post questions about Survey Library to https://github.com/surveyjs/surveyjs/issues.

Thank you,
Andrew

**Comment by mlandmann** [comment]
Andrew, this is a feature that should be built into the checkbox.  I just had a request from a club -- they want to put up their officer elections -- 6 people and they wanted to only allow people to select 3.  I get the code above -- but don't want to hack up the system for just one situation.  But there is a bigger picture to accomplish just that.  Is that something you guys can add to your development Q, please.  A user should be able to design a survey with this option -- and not involve a program to add some specifc JS code to just their survey.

**Comment by andrewtelnov** [comment]
@mlandmann I have implemented [maxSelectedChoices property](https://github.com/surveyjs/survey-library/issues/2500). You will be able to use it from v1.8.13
Right now it can be done by using choicesEnableIf property. Here is [the example](https://plnkr.co/edit/4VdhMQmC4HRr5WE5).

Thank you,
Andrew
