### ISSUE TITLE
Inline CSS in survey HTML elements

### ISSUE THREAD

**Issue by maithuy** [surveyjs/editor#109]
### Are you requesting a feature, reporting a bug or ask a queation?
Feature

### What is the current behavior?
Inline css is added after questions are rendered
<span style="margin-left: 3px; display: inline; position: static;">Wrinkles</span>

### What is the expected behavior?
No inline css added so that authors can control the styles of the survey elements

<span>Wrinkles</span>

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by andrewtelnov** [comment]
@maithuy Yes, you are right. it is better remove inline styles.
We will work on it.

Thank you,
Andrew
