### ISSUE TITLE
Calling rest to make calculations on for example "multipletext" type

### ISSUE THREAD

**Issue by towojtek** [surveyjs/editor#110]
### Are you requesting a feature, reporting a bug or ask a queation?

Feature

### What is the current behavior?

For now just a dropdown questions can use rest calls.

Example json:
{ type: "dropdown", name: "country", title: "Select the country...", isRequired: true,
      choicesByUrl: {url: "https://restcountries.eu/rest/v2/all", valueName: "name"} }

### What is the expected behavior?

Possibility to call rest on other types like : "multipletext".

Example:
{ type: "multipletext", name: "animals", title: "Animals",
      items: [{ name: "question_1", title: "How many cats do you have?",isRequired: true },
        { name: "question_2", title: "How many dogs do you have?", isRequired: true },
        { name: "question_3", title: "How many cows do you have?", isRequired: true },
// expected : call rest to receive number of animals and print it as 4th item ( I know that there is //possiblity to make calculations on front-end side but I want all of calculations to be made on backend //side 
//example of 4th imagined item 
// { name: "sum_Of_Animals", title: "Total amount of animals", 
// visibleIf: "{animals.question_1} > 0 and {animals.question_2} > 0 and {animals.question_3} >0"},
// valueByUrl : { url : "address to rest service which takes 3 values from previous items and respond with sum of them", valueName : "title of json respond "sum" when response is {"sum" : "4"}"
]},

### How would you reproduce the current behavior (if this is a bug)?

It's not a bug, it's a feature ;)

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by andrewtelnov** [comment]
@towojtek I understand you scenario. However, unlike dropdown (and radiogroup/checkbox) I think it is not a common scenario.
Do you need it to have just for one question in one survey? I may make a demo to change multitextquestion.items on calling rest service. It will be 5-10 lines of code.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@towojtek I maybe wrong if we see it is a common scenario, we would definitely introduce in the library itself. However, right now, I feel, it is better to implement this functional outside the library.

**Comment by WojciechDob** [comment]
Can you show me how to optain such a functionallity, on multitextquestion for this example ?
Example:
Json structure: 
{ type: "multipletext", name: "animals", title: "Animals",
items: [
{ name: "question_1", title: "How many cats do you have?",isRequired: true },
{ name: "question_2", title: "How many dogs do you have?", isRequired: true },
{ name: "question_3", title: "How many cows do you have?", isRequired: true }
{ name: "sum", title: "Amount of animals",  
visibleIf: "{animals.question_1} > 0 and {animals.question_2} > 0 and {animals.question_3} >0"},
valueByUrl : { url : "RestApi", valueName: "sum", calculationOf : "question_1,question_2,question3"
]}

**Comment by WojciechDob** [comment]
Just in my opinion, it might be usefull.
Imagine scenario when you are making huge calculations on values received from user.
Rest call will solve this scenario imidietly

**Comment by andrewtelnov** [comment]
@towojtek @WojciechDob I have added a demo. Please refer to: https://github.com/surveyjs/surveyjs/issues/478

Thank you,
Andrew
