### ISSUE TITLE
How can I deserialize the survey's JSON?

### ISSUE THREAD

**Issue by jweto** [surveyjs/editor#111]
### Are you requesting a feature, reporting a bug or ask a queation?

Ask a Question.

### What is the current behavior?

I want to deserialize a survey JSON to store the elements in my own database model, but the JSON schema changes based on its elements. What's the best way to solve that? I'm begginner at JSON manipulation.

### What is the expected behavior?

Is there a way to produces a fixed schema when save the survey JSON? Is there any material to help me with this issue? 

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by andrewtelnov** [comment]
@jweto Why don't you store the json as a text in your database and then restore it as a text?
The most developer platforms allows to convert json to text and vice versa.
For example.
For Javascript: https://stackoverflow.com/questions/6487699/best-way-to-serialize-unserialize-objects-in-javascript
For .Net: http://www.newtonsoft.com/json/help/html/SerializingJSON.htm

Thank you,
Andrew
