### ISSUE TITLE
Having transpile errors finding KnockoutObservables trying to include surveyjs editor in angular2 ionic2 project.

### ISSUE THREAD

**Issue by martyquinn** [surveyjs/editor#112]
Compile error: 
[11:59:41]  clean finished in 11 ms
[11:59:41]  copy started ...
[11:59:41]  transpile started ...
[11:59:50]  typescript: E:/ionic/clinicianSurveyor/node_modules/surveyjs-editor/surveyeditor.d.ts, line: 145
            Cannot find name 'KnockoutObservable'.

     L144:      protected getItemsText(): string;
     L145:      protected isValueEmpty(val: any): boolean;

[11:59:50]  typescript: E:/ionic/clinicianSurveyor/node_modules/surveyjs-editor/surveyeditor.d.ts, line: 146
            Cannot find name 'KnockoutObservable'.

     L145:      protected isValueEmpty(val: any): boolean;

[11:59:50]  typescript: E:/ionic/clinicianSurveyor/node_modules/surveyjs-editor/surveyeditor.d.ts, line: 147
            Cannot find name 'KnockoutObservable'.

     L148:  export declare class SurveyNestedPropertyEditor extends SurveyPropertyItemsEditor {

[11:59:50]  typescript: E:/ionic/clinicianSurveyor/node_modules/surveyjs-editor/surveyeditor.d.ts, line: 867
            Cannot find name 'KnockoutObservable'.

     L866:      template?: string;
     L867:      items?: KnockoutObservableArray<IToolbarItem>;

[11:59:50]  typescript: E:/ionic/clinicianSurveyor/node_modules/surveyjs-editor/surveyeditor.d.ts, line: 868
            Cannot find name 'KnockoutObservable'.

     L867:      items?: KnockoutObservableArray<IToolbarItem>;
     L869:  export declare class SurveyEditor implements ISurveyObjectEditorOptions {

[11:59:50]  typescript: E:/ionic/clinicianSurveyor/node_modules/surveyjs-editor/surveyeditor.d.ts, line: 869
            Cannot find name 'KnockoutObservable'.

     L869:  export declare class SurveyEditor implements ISurveyObjectEditorOptions {
     L870:      static defaultNewSurveyText: string;

[11:59:50]  typescript: E:/ionic/clinicianSurveyor/node_modules/surveyjs-editor/surveyeditor.d.ts, line: 871
            Cannot find name 'KnockoutObservable'.

     L870:  static defaultNewSurveyText: string;
     L871:  surveyId: string;
     L872:  surveyPostId: string;

[11:59:50]  typescript: E:/ionic/clinicianSurveyor/node_modules/surveyjs-editor/surveyeditor.d.ts, line: 872
            Cannot find name 'KnockoutObservable'.

     L871:  surveyId: string;
     L872:  surveyPostId: string;
     L873:  generateValidJSONChangedCallback: (generateValidJSON: boolean) => void;

### What is the expected behavior?
No errors.
I ran npm install knockout  - here's the package.json 
{
  "name": "myRash",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/animations": "4.1.3",
    "@angular/common": "4.1.3",
    "@angular/compiler": "4.1.3",
    "@angular/compiler-cli": "4.1.3",
    "@angular/core": "4.1.3",
    "@angular/forms": "4.1.3",
    "@angular/http": "4.1.3",
    "@angular/platform-browser": "4.1.3",
    "@angular/platform-browser-dynamic": "4.1.3",
    "@ionic-native/core": "3.10.2",
    "@ionic-native/splash-screen": "3.10.2",
    "@ionic-native/status-bar": "3.10.2",
    "@ionic/storage": "2.0.1",
    "@swimlane/ngx-charts": "^5.3.1",
    "@types/d3": "^4.9.0",
    "@types/knockout": "^3.4.41",
    "anychart-angular2": "^1.0.3",
    "bootstrap": "^3.3.7",
    "cordova-android": "^6.2.3",
    "cordova-ios": "^4.4.0",
    "cordova-plugin-console": "^1.0.5",
    "cordova-plugin-device": "^1.1.4",
    "cordova-plugin-splashscreen": "^4.0.3",
    "cordova-plugin-statusbar": "^2.2.2",
    "cordova-plugin-whitelist": "^1.3.1",
    "d3": "^4.9.1",
    "ionic": "^3.4.0",
    "ionic-angular": "3.4.2",
    "ionic-plugin-keyboard": "^2.2.1",
    "ionicons": "3.0.0",
    "knockout": "^3.4.2",
    "ko-observable": "^0.1.1",
    "rxjs": "5.4.0",
    "survey-angular": "^0.12.18",
    "survey-knockout": "^0.12.19",
    "surveyjs-editor": "^0.12.19",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.12"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.3.7",
    "@ionic/cli-plugin-cordova": "1.4.0",
    "@ionic/cli-plugin-ionic-angular": "1.3.1",
    "@types/knockout": "^3.4.40",
    "typescript": "2.3.3"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-console": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-whitelist": {},
      "ionic-plugin-keyboard": {}
    },
    "platforms": [
      "android",
      "ios"
    ]
  }
}

### How would you reproduce the current behavior (if this is a bug)?
Not sure.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: Firefox 
* editor version: 47.0.2

**Comment by andrewtelnov** [comment]
@martyquinn Could you please take a look at [angular 2 quick start repo](https://github.com/surveyjs/surveyjs_angular_quickstart)?

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
There is no follow-up.

**Comment by dmitrykurmanov** [comment]
@alekhraut, hello! We've checked your project and we think that you need to add this code to your tsconfig file:
`"compilerOptions": { ... "typeRoots": ["./node_modules/@types/"]` ... }

and the pull request https://github.com/alekhraut/ionicDemoInputMask/pull/1

**Comment by edwinborda** [comment]
[https://github.com/surveyjs/surveyjs_angular_cli/issues/14](https://github.com/surveyjs/surveyjs_angular_cli/issues/14)
