### ISSUE TITLE
How to show question icon next to question title?

### ISSUE THREAD

**Issue by muhfred** [surveyjs/editor#114]
### Are you requesting a feature, reporting a bug or ask a queation?

Question

### What is the current behavior?

the question title is displayed on every added question.

### What is the expected behavior?

show question icon on every added question next to question title.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: chrome latest version
* editor version: 0.12.19

**Comment by andrewtelnov** [comment]
@muhfred  Do you mean the same icon or different for every question?
If you mean a different one, you may use the markdown feature: http://surveyjs.org/examples/jquery/survey-markdown-radiogroup/

Thank you,
Andrew

**Comment by muhfred** [comment]
@andrewtelnov No I mean in the editor to show the question icon on every question added, radiogroup, checkbox, dropdown, etc...
Thank you.

**Comment by andrewtelnov** [comment]
@muhfred I am lost. Do you mean on the Toolbox?

Thank you,
Andrew

**Comment by muhfred** [comment]
@andrewtelnov I mean, that, I want to show the question icon which is in the toolbox, to be on the question itself when added in the editor.

**Comment by andrewtelnov** [comment]
@muhfred What is the aim of showing the icon? Do you want to make it clickable? What is the purpose to have the additional noise? 
I may make an optionally of course, but what do you want to achieve exactly? 

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
There is no followup for a long time.

**Comment by umr55766** [comment]
I want to add some icon like this [attached images]
My purpose is to show some info about the question.

For example : If field is last submission date - then I can show info like how this data will be used and what does this field mean, etc

<img width="167" alt="Screen Shot 2020-03-01 at 7 32 56 PM" src="https://user-images.githubusercontent.com/16179313/75627110-78cb6e80-5bf3-11ea-910e-4ef00cdf53bb.png">

**Comment by andrewtelnov** [comment]
@muhfred We have description property, that commonly displayed under the question title. Do you want to display the description property on clicking the icon?

Thank you,
Andrew

**Comment by umr55766** [comment]
Thank you Andrew for replying!

1. Can I toggle description field visibility ?
2. How do I add that icon ?
3. This is my form https://user-images.githubusercontent.com/52668474/74974820-3b622680-5426-11ea-8889-eb61174cfb65.jpg

Thanks!
