### ISSUE TITLE
How-to: Set certain tool properties' default value when Editor initialized?

### ISSUE THREAD

**Issue by xraywu** [surveyjs/editor#117]
### Are you requesting a feature, reporting a bug or ask a queation?

Asking a question

### What is the expected behavior?

Hi, we are looking for a method to set the default values of certain tool properties (e.g. always set `storeAsTextData` as `true` for File) during Editor initialization. Is there way of doing so?

**Comment by andrewtelnov** [comment]
@xraywu You may add your own item into toolbox or replace/remove the existing items: https://www.surveyjs.io/Editor/examples/toolboxcustomization.html#code

Thank you,
Andrew
