### ISSUE TITLE
Feature - Prevent adding response choices

### ISSUE THREAD

**Issue by traquall** [surveyjs/editor#118]
### Are you requesting a feature, reporting a bug or ask a queation?

Question or feature if it doesn't exist

### What is the expected behavior?

I'd like to hide/lock or delete :  'add new' button and delete response choices buttons in choices tab.
In order, for example, to have a question with 'YES / NO' choices only

Is it doable for now ?

Thank you

**Comment by andrewtelnov** [comment]
@traquall Do you want this functionality for a particular question or question type or every where?

I was thinking about adding 'Yes/No' functionality as a new question. QuestionBoolean - a checkbox with 3 (optional 2 states): true, false, undefined (optional). true and false value will be able to change to "Yes/No"

Will it be a better solution for you?

Thank you,
Andrew

**Comment by traquall** [comment]
@andrewtelnov I would prefer to be able to custom every type of question, this will facilitate the creation of 'Yes/No buttons' and other type of questions too.

Thank you,
Traquall

**Comment by andrewtelnov** [comment]
@traquall That is fine, we will add it into our TODO list and implement.
I am asking about QuestionBoolean. Maybe this is actually a better solution to you?
I have been recently helping to transfer a paper survey into surveyjs and found that QuestionBoolean would make the survey clear in terms of UI and survey JSON.

Thank you,
Andrew

**Comment by traquall** [comment]
@andrewtelnov I think a QuestionBoolean may be a great add to surveyjs, but that's not what i actually need ^^', i need to have a question with 3 choices and prevent to add or remove choices to keep 3 choices. 
(And if you add this functionnality, i think we will be able to prevent add/remove dynamically ?)

Thank you,
Traquall

**Comment by andrewtelnov** [comment]
@traquall Ok got you about the choices.
Could you please explain more about  

> i think we will be able to prevent add/remove dynamically

What do you mean by that?

Thank you,
Andrew

**Comment by traquall** [comment]
@andrewtelnov 
I mean, If I need to lock 'add new' or/and 'remove' buttons depending on a condition .
for example : I want that a radio question has between 2 and 5 responses choices, so if this radio question has 2 choices i lock the remove button and if radio question has 5 choices i lock the add button.
(for example, but anyway this will offer a lot of possibilities)

Thank you,
Traquall

**Comment by andrewtelnov** [comment]
@traquall ok, I got it.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@traquall I have started to work on this functionality. It should be available in the next minor. We will release it on the next week. Please refer to [this issue](https://github.com/surveyjs/editor/issues/120). There is an example of using.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@traquall FYI: https://github.com/surveyjs/editor/issues/120 has been implemented.

Thank you,
Andrew

**Comment by traquall** [comment]
@andrewtelnov Thank you !
