### ISSUE TITLE
Feature - Return different properties name to json

### ISSUE THREAD

**Issue by traquall** [surveyjs/editor#119]
### Are you requesting a feature, reporting a bug or ask a queation?

Asking if it exists, if not requesting a feature.

### What is the current behavior?

I can add properties like this : 
Survey.JsonObject.metaData.addProperty("questionbase", "a parameter");
and this will return "a parameter":"answer" in the json

### What is the expected behavior?

I'd like to change the name of the property in the json in order to have camelCase in the json.
For example : 
Survey.JsonObject.metaData.addProperty("questionbase",{name :  "Short résumé", returnToJson : "shortResume");
-> It shows "Short résumé" to users completing the survey
and return "shortResume":"the answer" in the Json

Thank you, 
Traquall

**Comment by andrewtelnov** [comment]
@traquall You have to add a property into defaultStrings in https://github.com/surveyjs/editor/blob/master/src/editorLocalization.ts.
Property editor will try to take the tittle from this variable or localized variant.
For example:
```
Survey.JsonObject.metaData.addProperty("questionbase",{name : "shortResume");
SurveyEditor.defaultStrings.p["shortResume"] = "Short résumé";

```
Thank you,
Andrew

**Comment by traquall** [comment]
@andrewtelnov I didn't understand what I should do with https://github.com/surveyjs/editor/blob/master/src/editorLocalization.ts.
and SurveyEditor has no 'defaultStrings' property ...

Thank you

**Comment by andrewtelnov** [comment]
@traquall You are right defaultStrings are not in the list of export classes/variables ;( 
I have just included it: https://github.com/surveyjs/editor/commit/f31036688d411612f4adada8edcd3b821a8deeb4
It will be available from the next minor release. After that the code written above will work.

Thank you,
Andrew

**Comment by traquall** [comment]
@andrewtelnov Ok ^^ thank you a lot

**Comment by traquall** [comment]
@andrewtelnov When is this release planned ? 

Thanks

**Comment by andrewtelnov** [comment]
@traquall We are planning to release on Tuesday. Unfortunately, there is a show stopper issue in a new question PanelDynamic in vue platform. We hope to solve it today-tomorrow. Otherwise we may delay the release on one-two days.

You may try the dev version right now: 
https://surveyjs.azureedge.net/dev/survey.ko.min.js
https://surveyjs.azureedge.net/dev/surveyeditor.css
https://surveyjs.azureedge.net/dev/surveyeditor.min.js

Thank you,
Andrew

**Comment by traquall** [comment]
@andrewtelnov Thank you :)

**Comment by traquall** [comment]
Is this feature present in the latest release?
If so, has it changed ? because it does not work with the previous code.

Thanks

**Comment by andrewtelnov** [comment]
@traquall Yes, it is a bug. I have fixed. I have modify a unit test and added a check, so we should not break it again.
We will likely release today.

Thank you,
Andrew

**Comment by traquall** [comment]
@andrewtelnov Thank you

**Comment by traquall** [comment]
@andrewtelnov This still not work in 0.12.30

**Comment by andrewtelnov** [comment]
@traquall I wanted to make a demo and to my surprice it doesn't work indeed :(
I have changed the Property Editor since then greatly and the old unit test does nothing right now. I will fix it and come back.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@traquall I have fixed it. I am sorry about this.

Thank you,
Andrew

**Comment by traquall** [comment]
@andrewtelnov No problem ^^

Thank you

**Comment by traquall** [comment]
I don't know how, but it was working in 0.12.32 and then it won't work anymore (still in 0.12.32)

**Comment by traquall** [comment]
https://github.com/surveyjs/editor/issues/190
