### ISSUE TITLE
Hide "Apply" button

### ISSUE THREAD

**Issue by SlowburnAZ** [surveyjs/editor#121]
### Question

Is there an "afterRender" event that I can tap into?

Customer is complaining about the "Apply" button in the question editor modals.  Would like to be able to hide the Apply button, since the "OK" button also applies the changes and closes the modal.  They'd also like to make the "OK" button say "Save" instead.

Thanks!

Of course, if there's another way to do this, I'm all ears.

**Comment by andrewtelnov** [comment]
@SlowburnAZ You will be able to use the following code after the next minor update:
```
editor.showApplyButtonInEditors = false;
SurveyEditor.defaultStrings.pe.ok = "Save";

```

Thank you,
Andrew
