### ISSUE TITLE
Multi Select imagepicker with option groups

### ISSUE THREAD

**Issue by gaurav-singhal** [surveyjs/editor#124]
### Are you requesting a feature, reporting a bug or ask a queation?
Feature if it doesn't exist

### What is the current behavior?
Single select image picker sample is provided. Need multi-image picker with option groups. How to customize it. http://rvera.github.io/image-picker/  Check Grouped Options.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by dmitrykurmanov** [comment]
https://github.com/surveyjs/surveyjs/issues/559#issuecomment-322129450

**Comment by gaurav-singhal** [comment]
Hi I was able to get it working for running the survey using afterRender option suggested there.

```
{ type: "checkbox", name: "choosepicture", renderAs: "imagepicker", title: "What animal would you like to see first ?", 
     choices: [
        {value: "lion", group: "g1", text: "http://surveyjs.org/images/image-picker/lion.jpg"},
        {value: "giraffe", group: "g2", text: "http://surveyjs.org/images/image-picker/giraffe.jpg"},
        {value: "panda", group: "g3", text: "http://surveyjs.org/images/image-picker/panda.jpg"},
        {value: "camel", group: "g2", text: "http://surveyjs.org/images/image-picker/camel.jpg"}
     ]
  }

```
My question is how do we allow user to set the group in Editor??

**Comment by dmitrykurmanov** [comment]
@gaurav-singhal, do you need a custom property in the editor? You can do something like this:

`Survey.JsonObject.metaData.addProperty("checkbox", {name: "group:string", default: "g0"});` - adding _tag_ property for all checkboxes in the editor

 Please check this example https://surveyjs.io/Examples/Editor/?id=addproperties Is it ok for you?
