### ISSUE TITLE
"None of the above" checkbox behaviour

### ISSUE THREAD

**Issue by ian-klinck** [surveyjs/editor#125]
I am trying to implement standard "None of the above" checkbox behaviour. i.e.
- If you have other checkboxes checked, and click "None of the above", the other checkboxes clear, so only "None of the above" is checked.
- If you have "None of the above" checked, and click other checkboxes, "None of the above" clears, so only "None of the above" is checked.

We can do the first one with a trigger (if the question includes "NotA", set the value of the question to "NotA").

I cannot figure out how to do the second with SurveyJS triggers, etc. Is it possible?

(Note that we are trying to implement this in a way that it is all managed within SurveyJS, as we want to be able to create & modify surveys after this product is live without modifying code.)

Thanks!

**Comment by andrewtelnov** [comment]
@ian-klinck Here is the plunker example: https://plnkr.co/edit/H1YjYH?p=preview

Thank you,
Andrew

**Comment by ian-klinck** [comment]
Thanks! We'll give this a shot!

**Comment by john1625b** [comment]
@andrewtelnov When I use this code in my project, I get a "Maximum call stack size exceeded" when I click on 'none of the above'. When I put a console log in the onValueChanged function, the message prints infinitely when I click on the 'none of the above' option. I think what is happening is that clicking 'none of the above' triggers another onValueChange which then calls the function over and over again. How would I fix this? thanks.

**Comment by andrewtelnov** [comment]
@john1625b That is strange. It works perfectly in plunker. Probably you are using another version or for another platform.
Anyway, I have changed the example. It should be fine now: https://plnkr.co/edit/H1YjYH?p=preview
I have added onValueChangingProcessing variable.

Thank you,
Andrew

**Comment by john1625b** [comment]
@andrewtelnov Hey I just solved the problem. The reason why it wasn't working on my end was because we had triggers set through the survey.js GUI builder. The trigger was something like "set the value to none if none of the above is selected. So all I had to do was remove these triggers which we set. Anyways thank you for your help!

**Comment by ian-klinck** [comment]
@andrewtelnov 
So, this is working great for the "None of the Above" option.

However, we've got one question in a survey with both a "None of the Above" (NotA) option and a "Prefer not to Answer" (PntA) option. I'm trying to implement this for both buttons, but running into a bit of an issue on an edge case. It works fine for selecting "normal" options & then the NotA/PntA answer or vice-versa, but If I select NotA, then PntA, then back to NotA, then *all* checkboxes are cleared, and I cannot select NotA without selecting something else first. (Similarly if I select PntA, then NotA, then PntA again.)

Below is how we've tried to extend the code to cover both checkboxes. "NA" is "None of the Above", and "PN" is "Prefer not to Answer". Any ideas?

 ```
 noneOfTheAboveHandler(survey, options) {
    const none = 'NA';
    const preferNotToAnswer = 'PN';
    const { question } = options;
    if (!question || question.getType() !== 'checkbox') {
      return;
    }

    if (!question.prevValue || !options.value) {
      question.prevValue = options.value;
      return;
    }

    const { prevValue } = question;
    const index = options.value.indexOf(none);
    const indexPNA = options.value.indexOf(preferNotToAnswer);


    if (index >= 0 && indexPNA >= 0) {
      if (prevValue.indexOf('PN') < prevValue.indexOf('NA')) {
        question.value = [preferNotToAnswer];
      } else {
        question.value = [none];
      }
    } else if (index >= 0) {
      if (prevValue.indexOf('NA') >= 0) {
        const value = question.value;
        value.splice(index, 1);
        question.value = value;
      } else {
        question.value = [none];
      }
    } else if (indexPNA >= 0) {
      if (prevValue.indexOf('PN') >= 0) {
        const value = question.value;
        value.splice(indexPNA, 1);
        question.value = value;
      } else {
        question.value = [preferNotToAnswer];
      }
    }

    question.prevValue = options.value;
  }

```

**Comment by andrewtelnov** [comment]
@ian-klinck Here is the [working example](https://plnkr.co/edit/hSO3td?p=preview)

Thank you,
Andrew

**Comment by ian-klinck** [comment]
Thanks! I'll give this a shot!
