### ISSUE TITLE
Is there a way to assign the question ID to the rendered question element?

### ISSUE THREAD

**Issue by maithuy** [surveyjs/editor#126]

**Comment by andrewtelnov** [comment]
@maithuy Here is the example, that does exactly what you need: http://editor.surveyjs.io/examples/oncreatequestion.html#code

Thank you,
Andrew

**Comment by maithuy** [comment]
@andrewtelnov Thanks for the example. It'd be great to see this in ReactJS ES6. -Thuy

**Comment by dmitrykurmanov** [comment]
@maithuy, hello! How could we provide example in RactJS ES6 for you? May be by creating github repo or may be by some new sandbox with webpack(rollup/something else). Could you please help us with this problem?

**Comment by maithuy** [comment]
@andrewtelnov Hi Andrew, I'm working on a skin care quiz prototype. I've used the SurveyJS to load the questionnaires, which is this on render method in ReactJS

   import React from 'react';
   import quizMatrix from '../model/all-question-model';
   import * as Survey from 'survey-react';
   .
   .
   .
   var model = new Survey.Model(quizMatrix[0]);
    return (
      <div>
        <div className="rf-skin-quiz">
          <Survey.Survey model={model} onComplete={this.sendDataToServer} />
        </div>
        <div>
          {this.resultAsString}
        </div>
      </div>
    );

The prototype URL is http://rfvirtualderm.s3-website-us-west-1.amazonaws.com/

Currently, SurveyJS populates the questions with a 'random' generated ID, please see snippet below. I would like to be able to assign a specific ID to the questions, in this question example, it'd would be id="sensitivity-triggers", as well as assign a specific css class.

`
<div id="sq_111" class="sv_q" style="display: inline-block; vertical-align: top; width: 100%;">
<h5 class="sv_q_title"><span>* What triggers your sensitivity?</span></h5>
.....
.......
</div>
`

Is there a way to have the question ID in the JSON and dynamically assign them on render?

Hope you could help with this.
Thanks!

**Comment by andrewtelnov** [comment]
@maithuy Do you want to add a new property to question object?
It can be done in this way:
Survey.JsonObject.metaData.addProperty("question", {name: "ID"});
or if you want to make it as a numeric:
Survey.JsonObject.metaData.addProperty("question", {name: "ID:number"});

Thank you,
Andrew

**Comment by maithuy** [comment]
@andrewtelnov Thanks so much for a quick reply.

Could I have the IDs for all questions in the json? If I add a property to a question,  I would need to access each question load and add it?

This <Survey.Survey model={model} onComplete={this.sendDataToServer} /> does the  following/previous/next rendering automatically, if I want to customize at a point somewhere in between, how would I go about customizing it?

**Comment by andrewtelnov** [comment]
@maithuy Ah, I see the issue that you have now. Yes, we have a counter, that increased on creating every new question, and question id = "sq_" + static question counter ++;
We can't use question name, because name maybe not unique. 
I may make question.id property writable you will be able to change it on [survey.onQuestionAdded event](https://www.surveyjs.io/Documentation/Library/?id=surveymodel#onQuestionAdded).
Will it work for you?

Thank you,
Andrew

**Comment by maithuy** [comment]
@andrewtelnov Would that mean I can change the question ID using onQuestionAdded={this.assignQuestionID} like the below?

I've tried that but the method doesn't output the console log.

```js
import React from 'react';
import quizMatrix from '../model/all-question-model';
import * as Survey from 'survey-react';


class Quiz extends React.Component {
  constructor(props) {
    super(props);
    this.results = {};
    this.sendDataToServer = this.sendDataToServer.bind(this);
  }

  componentDidMount() { }

  componentDidUpdate() { }

  sendDataToServer(survey) {
    var resultAsString = JSON.stringify(survey.data);
    console.log(resultAsString); //send Ajax request to your web server.
    this.props.nextStep();
  }

  assignQuestionID(survey) {
    console.log('assign new question ID');
  }

  render() {

    Survey.defaultStandardCss.navigation.completed = "rf-btn rf-btn-default-primary";
    Survey.defaultStandardCss.navigation.prev = "rf-btn rf-btn-default-primary";
    Survey.defaultStandardCss.navigation.next = "rf-btn rf-btn-default-primary";

    var model = new Survey.Model(quizMatrix[0]);
    return (
      <div>
        <div className="rf-skin-quiz">
          <Survey.Survey model={model} onComplete={this.sendDataToServer} onQuestionAdded={this.assignQuestionID}  />
        </div>
        <div>
          {this.resultAsString}
        </div>
      </div>
    );
  }
}

export default Quiz;
```

**Comment by andrewtelnov** [comment]
@maithuy Yes, exactly. You have to make sure that id is unique.
question.id becomes writable from the next minor update.

Thank you,
Andrew

**Comment by maithuy** [comment]
@andrewtelnov Thank you. How do I find out when the next minor update is?

**Comment by andrewtelnov** [comment]
@maithuy I believe we will release it in the middle next week, so in about in a week.
The current version is 0.12.23, you see it on the left top corner: https://www.surveyjs.io/

Thank you,
Andrew

**Comment by maithuy** [comment]
@andrewtelnov Hi Andrew, I installed the latest version and am not sure how to assign a custom ID for the page, is it through setter method? I don't see it on the documentation page. Thanks in advance.

**Comment by andrewtelnov** [comment]
@maithuy It is read-only in the current version. I've just made it writable as for questions.

Thank you,
Andrew
