### ISSUE TITLE
How can Assign "Score" into ItemValue object

### ISSUE THREAD

**Issue by ak34504** [surveyjs/editor#127]
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by andrewtelnov** [comment]
@ak34504 Please take a look at [this demo](https://www.surveyjs.io/Examples/Editor/?id=addproperties)
`Survey.JsonObject.metaData.addProperty("questionbase", {name: "score:number"});`
Where do you want to render it?
You may use [survey.onAfterRenderQuestion event](https://www.surveyjs.io/Documentation/Library/?id=surveymodel#onAfterRenderQuestion)

Thank you,
Andrew

**Comment by ak34504** [comment]
Thanks Andrew for response. However my requirement is not to render the score. But we want it
- Attach a weight to each question, say 10%
- Attach a score to each of the answer of question (e.g. we have three response and we can have 1, 5 and 10 as score of each response respectively)
- When user answer a question, e would like to store this in response and then use this score as per weitage to calculate the final score of audit
- Then we shall be using this in our reports.

I hope to clarify our requirements

**Comment by andrewtelnov** [comment]
Then you need only to add properties and onComplete event or on server makes a calculation.

Thank you,
Andrew

**Comment by ak34504** [comment]
How can add score property for each Answer?

**Comment by andrewtelnov** [comment]
'Survey.JsonObject.metaData.addProperty("questionbase", {name: "score:number"});'
After that you may assign this property into JSON and library will read it.

**Comment by ak34504** [comment]
Hi Andrew ,

{
 pages: [
  {
   name: "page1",
   elements: [
    {
     type: "radiogroup",
     choices: [
      {
       value: "1",
       text: "2",
       score:"13"
      },
      {
       value: "2",
       text: "3",
       score:"10"
      },
      {
       value: "3",
       text: "4",
       score:"15"
      }
     ],
     name: "Question Ex"
    }
   ]
  }
 ]
}

this is My JSON,I'm defining "score" for all options,now i need to reader these score on Web Page.

**Comment by andrewtelnov** [comment]
@ak34504 Ah, you are adding the score property into ItemValue object, not into the question itself.
Unfortunately, there is no easy to do it right now.
We have it in our TODO list however.

**Comment by ak34504** [comment]
Thanks @andrewtelnov 
when we can expect release.

**Comment by andrewtelnov** [comment]
@ak34504 It is here now:
`Survey.JsonObject.metaData.addProperty("itemvalue", {name: "score:number"});`

Thank you,
Andrew

**Comment by abdoady** [comment]
Here is a complete good example of your requirement "may be late, but hopefully will help someone else".
https://plnkr.co/edit/GFZssRnoZNUgYn8cGdI8?p=preview
