### ISSUE TITLE
I Need to Create Form for collecting Information along with particular Questions. 

### ISSUE THREAD

**Issue by ak34504** [surveyjs/editor#128]

**Comment by dmitrykurmanov** [comment]
@ak34504, hello! Could you please describe your scenario in greater details? You can get any of our [examples](https://surveyjs.io/Examples/Library/?id=survey-options&platform=jQuery#) and open it in sandbox (plnkr). Then you can modify this example and post to us. It is the better way of creating issues. Thanks.

**Comment by ak34504** [comment]
@dmitrykurmanov ,
![surveyissue](https://user-images.githubusercontent.com/31439493/29866708-dd462dd8-8d96-11e7-9bf1-927d95ba59f5.png)


1:-There Are two form "1" and "2".
2:-after click on "More" Button form 2 is open and Enter More Information and click on save button these data are save along with this Question.

**Comment by dmitrykurmanov** [comment]
@ak34504, ok I see. We have "collapse/expand functionality for panels" in our todo list. As a workaround you can do it with **visibleIf** property, for example: https://surveyjs.io/Examples/Library/?id=condition-kids&platform=jQuery

**Comment by dmitrykurmanov** [comment]
@tsv2013, @andrewtelnov, @ak34504 and what about popup functionallity for the survey?

**Comment by ak34504** [comment]
@dmitrykurmanov ,

This is not what we want.its just like a child question
i need to create one separate form for questions where question can have child question, file attachment and data forms all present in single form ans button (Ex. "save" button) also i need on same form

**Comment by andrewtelnov** [comment]
@ak34504 We will keep you scenario in mind, but it is not a generic :-( and it will be hard to describe it in JSON format.

Thank you,
Andrew

**Comment by ak34504** [comment]
In surveyjs.io in TOOLBOX  have HTML tool ,we can use and get the value ?

**Comment by tsv2013** [comment]
@ak34504 Yes, SurveyJS has HTML question, but it serves to show additional information beautified enought and has no value. Thus in order to implement your scenarion some amount of code should be written. In my opinion the right way is to create custom question, that will contain a button and a popup for additional information input.
