### ISSUE TITLE
How can be add CSS class Name in Control or parent "div"?   

### ISSUE THREAD

**Issue by ak34504** [surveyjs/editor#131]
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by dmitrykurmanov** [comment]
@ak34504 , hello please check these examples:
https://surveyjs.io/Examples/Library/?id=survey-customcss&platform=jQuery
https://plnkr.co/edit/aIz4bdA0pFVw7WttInVF?p=preview
