### ISSUE TITLE
How to set default value for CheckBox(RunTime)

### ISSUE THREAD

**Issue by lalitkhanna** [surveyjs/editor#133]
### Are you requesting a feature, reporting a bug or ask a queation?
Here is the scenario: 
In my form user choices some option but as per some business rules he/she can't be choice some of the option so we need to set some other option from server side.

We tried to do so but we're unable to update on run time,Can you please show some example for this scenario.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by andrewtelnov** [comment]
@lalitkhanna Here is the code:
`survey.setValue("myCheckboxQuestion", [value1, value1]);`

Thank you,
Andrew

**Comment by lalitkhanna** [comment]
This is not happening, can you please give some example.

Thanks
Lalit

**Comment by andrewtelnov** [comment]
@lalitkhanna Here is [the demo](https://www.surveyjs.io/Examples/Library/?id=survey-data&platform=jQuery)

**Comment by lalitkhanna** [comment]
Thanks Andrew
