### ISSUE TITLE
generateValidJSON can be set to false even though default is true

### ISSUE THREAD

**Issue by kennetlindberg** [surveyjs/editor#135]
### Are you requesting a feature, reporting a bug or ask a queation?
Bug

### What is the current behavior?
If other options are set then generateValidJSON is set to false if not explicitly set to true.

### What is the expected behavior?
generateValidJSON should be true if not explicitly set to false.

### How would you reproduce the current behavior (if this is a bug)?
See Test code

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

var options = {
  showTestSurveyTab : true
};
var editor = new SurveyEditor.SurveyEditor("editor", options);

### Specify your

* browser: Chrome 60.0.3112.113
* editor version: 0.12.23

**Comment by andrewtelnov** [comment]
@kennetlindberg I have fixed it.

Thank you,
Andrew

**Comment by kennetlindberg** [comment]
That was fast, thanks! :)
