### ISSUE TITLE
Set a property from code?

### ISSUE THREAD

**Issue by kennetlindberg** [surveyjs/editor#141]
### Are you requesting a feature, reporting a bug or ask a queation?

Question

### What is the expected behavior?

Is it possible to set a property from code? For example if I wanted to make "locale" selection more visible and create my own button outside the editor or in the toolbar.

Thanks!

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: Chrome 60.0.3112.113
* editor version: 0.12.23

**Comment by andrewtelnov** [comment]
@kennetlindberg Sure, here is the [plunker demo](https://plnkr.co/edit/mrxWPe3s8OY5Ttv7e9yZ?p=preview)

Thank you,
Andrew

**Comment by kennetlindberg** [comment]
Hi, thanks for your reply. It works, kind of, however the Property Panel (right side) is not updated when locale is changed which can lead to problems.

**Comment by kennetlindberg** [comment]
@andrewtelnov No, that is not what I meant. I'll try to explain a bit more:
If you enter for example a title for a question in multiple languages and have that question selected when you change the locale using the new button, the title field in the properties panel is not updated to reflect the newly selected locale.

**Comment by andrewtelnov** [comment]
@kennetlindberg I got it. Here is the updated [plunker demo](https://plnkr.co/edit/mrxWPe3s8OY5Ttv7e9yZ?p=preview)

PS: You have to use the latest version of Library and Editor.

Thank you,
Andrew
