### ISSUE TITLE
How to ignore Question Number

### ISSUE THREAD

**Issue by lalitkhanna** [surveyjs/editor#143]
### Are you requesting a feature, reporting a bug or ask a queation?

As default we got question number which we want to avoid, is there any way to do this ?

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by andrewtelnov** [comment]
@lalitkhanna survey.showQuestionNumbers
Set this property to "off" to turn off the numbering on questions titles or "onpage" to start numbering on every page. The default value is "on".

PS: Please use surveyjs repo for question about the library. You are asking the question into the wrong repo.

Thank you,
Andrew

**Comment by lalitkhanna** [comment]
Thanks
