### ISSUE TITLE
Is it possible to change 'Test Survey' to 'custom text' in survey editor's tab header text. 

### ISSUE THREAD

**Issue by rangasurendra** [surveyjs/editor#145]
### Are you requesting a feature, reporting a bug or ask a question?
Question

### What is the current behavior?
Greetings! is it possible to change tab header text in Survey Editor.

### What is the expected behavior?
Sort of initialization configuration to customize specific header texts, with their localization strings.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by andrewtelnov** [comment]
@rangasurendra Please take a look at [localization example](https://www.surveyjs.io/Examples/Editor/?id=localization).
You may change the English strings as well. Here is the demo: https://plnkr.co/edit/HqwK8uM6JlM0sG3ShOvd?p=preview

Thank you,
Andrew

**Comment by rangasurendra** [comment]
Great! and thank you for the quick response and explanation.
Ranga
