### ISSUE TITLE
How to get page wise submission ? 

### ISSUE THREAD

**Issue by lalitkhanna** [surveyjs/editor#147]
### Are you requesting a feature, reporting a bug or ask a queation?
In case, I've multiple pages & these pages are depended (if pass some value from page1 to page2)  on each other then how could I get values while clicking on 'Next' ?

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by andrewtelnov** [comment]
@lalitkhanna I am not sure I understand you.
There is survey.onValueChanged event where you may set update the value of another question based on changed value.
If you you have the same name to several questions, then they will have the same answer results.

Thank you,
Andrew-

**Comment by andrewtelnov** [comment]
Please post your questions into Library repo.

Thank you-

**Comment by lalitkhanna** [comment]
Thanks
