### ISSUE TITLE
How to bind multiple values for dynamic rows ?

### ISSUE THREAD

**Issue by lalitkhanna** [surveyjs/editor#148]
### Are you requesting a feature, reporting a bug or ask a queation?
Can you please provide me some example if I need to bind values with dynamic rows ?

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by andrewtelnov** [comment]
@lalitkhanna It is an array of objects:
`[{columnName1: columnValue1, ..., columnNameN: columnValueN}, {} ]`

Thank you,
Andrew

**Comment by lalitkhanna** [comment]
Thanks
