### ISSUE TITLE
Can we inline edit for question and options?

### ISSUE THREAD

**Issue by kailashyadav** [surveyjs/editor#15]
@andrewtelnov I loved your feature and using your library in one of my project, it would be great if you can provide inline edit to your upcoming feature along with jQuery only version, right now it has dependency on Knockout or React framework.

**Comment by andrewtelnov** [comment]
@kailashyadav Are you talking about survey editor or surveyjs library?
We are thinking about jQuery version of surveyjs library. I am not sure about survey editor. Knockout is only 50k size and I do not think it is a problem for a back-end.

**Comment by kailashyadav** [comment]
@andrewtelnov i don't have much experience in knockout and wanted to add few more question type? how should i do that? for instance The company name, logo and introductory text for the Survey.

**Comment by andrewtelnov** [comment]
@kailashyadav Sorry, I have missed your question. Here is the example of adding [All countries](https://surveyjs.io/Examples/Editor/?id=toolboxcustomization) question into Editor. We support custom widgets right now as well: https://surveyjs.io/Examples/Library/?id=custom-widget-select2-tagbox

Thank you,
Andrew
