### ISSUE TITLE
Is it possible to add link inside the Questions ?

### ISSUE THREAD

**Issue by abhishek1503** [surveyjs/editor#151]
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by andrewtelnov** [comment]
@abhishek1503 Do you mean <a> tag inside the question title?

Thank you,
Andrew

**Comment by abhishek1503** [comment]
Like this form.

![survey1](https://user-images.githubusercontent.com/31983267/30474281-c0cfa8fa-9a20-11e7-81fc-0ebc152b438c.png)

**Comment by andrewtelnov** [comment]
@abhishek1503 You may use the markdown support. Here is [the example](https://www.surveyjs.io/Examples/Library/?id=survey-markdown-radiogroup)

Thank you,
Andrew
