### ISSUE TITLE
"hasOther" does not work when dropdown exceeds 18 options

### ISSUE THREAD

**Issue by nadialo** [surveyjs/editor#152]
Hi, I would like to apply "hasOther" on my 20 options dropdown, however the "Other" option does not appear at the bottom of the list,. I have tried on the editor, which it seems like when the dropdown over 18 options, the "Other"option is not functioning. Thanks. 

Here is the code I tested on 0.12.26
{
 pages: [
  {
   name: "page1",
   elements: [
    {
     type: "dropdown",
     name: "question1",
     hasOther: true,
     choices: [
      "item1",
      "item2",
      "item3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18", 
      "19"
     ],
     otherText: "Others, Please Specify"
    }
   ]

* browser: Chrome
* editor version: tested on 0.12.26 and 0.12.17

**Comment by andrewtelnov** [comment]
@nadialo I could not reproduce the issue: https://www.surveyjs.io/Editor/Editor/#446a5715-2e67-451b-b3b1-e0a1b0ae2074

Thank you,
Andrew
