### ISSUE TITLE
Bootstrap 4 and customisation options in an Angular 2/4 app

### ISSUE THREAD

**Issue by ahtsei** [surveyjs/editor#153]
### Are you requesting a feature, reporting a bug or ask a question?
Question regarding styling the editor in an Angular 2/4 app.

### What is the current behavior?
The app I am building is based on Bootstrap 4, and the SurveyJS Editor component is injecting the Bootstrap 3 CSS stylesheet and it's custom survey stylesheets after my apps CSS ie. into the global scope.

### What is the expected behavior?
Is it possible to get around this issue, and have the editor styles self contained (and optional) and thus customisable by a global stylesheet? For example having the ability to make the Bootstrap 3 stylesheet optional. I know there's the cssType property, but this seems unrelated?

#### Provide the test code and the tested page URL (if applicable)

Just for illustration purposes, here's my editor component from my angular app.

```
import { Component, Input, Output, EventEmitter, OnInit } from '@angular/core';
import * as SurveyEditor from 'surveyjs-editor';

@Component({
    selector: 'survey-editor',
    template: `<div id="surveyEditorContainer"></div>`
})
export class SurveyEditorComponent implements OnInit {
    editor: SurveyEditor.SurveyEditor;
    @Input() json: any;
    @Output() surveySaved: EventEmitter<Object> = new EventEmitter();
    ngOnInit() {
        let editorOptions = {
            showEmbededSurveyTab: false,
            generateValidJSON: true,
            showJSONEditorTab: false,
            showTestSurveyTab: true
        };

        this.editor = new SurveyEditor.SurveyEditor('surveyEditorContainer', editorOptions);
        this.editor.text = JSON.stringify(this.json);
        this.editor.saveSurveyFunc = this.saveMySurvey;
    }

    saveMySurvey = () => {
        this.surveySaved.emit(JSON.parse(this.editor.text));
    }
}
```

**Comment by andrewtelnov** [comment]
@ahtsei We want to support Bootstrap 4 out of the box. It is in our TODO list, but we are not working on it yet.

Thank you,
Andrew

**Comment by tsv2013** [comment]
@ahtsei We've introduced Bootstrap 4 support since v0.96.2 (https://github.com/surveyjs/editor/releases/tag/v0.96.2).
