### ISSUE TITLE
Adding new panel without a name

### ISSUE THREAD

**Issue by rygler** [surveyjs/editor#155]
### Are you requesting a feature, reporting a bug or ask a question?
Requesting a feature

### What is the current behavior?
When calling `addNewPanel` on a page, if you pass a string as an argument, then that string will be set as the name. If you pass in nothing, no name is set. 

### What is the expected behavior?
It would be nice if when there is no string being passed in, the panel name would default to panel1, panel2, etc...

(Also, there's a typo in the documentation for addNewPanel. The word 'into' is spelled 'inot')

**Comment by andrewtelnov** [comment]
@rygler Do you mean, if the name in Panel/Question in addNewPanel/addNewQuestion is empty - generates the name name?
I think it is reasonable.

Thank you,
Andrew

**Comment by rygler** [comment]
@andrewtelnov Yes. If no name is supplied, a default name should be generated that is not simply an empty string.

**Comment by andrewtelnov** [comment]
@rygler you are right. It is better to move this code from the editor into the library code.
I will do it.
