### ISSUE TITLE
Online Editor generating incorrect json

### ISSUE THREAD

**Issue by nheath99** [surveyjs/editor#157]
### Are you requesting a feature, reporting a bug or ask a queation?
Bug

### What is the current behavior?
Online editor at https://surveyjs.io/Editor/Editor generates a json representation on the JSON Editor tab of the current configuration. It is generating an array element named "elements", rather than "questions". Passing this json into a survey model results in an error.

### What is the expected behavior?
The generated json should contain an array element named "questions"

### How would you reproduce the current behavior (if this is a bug)?
- Go to https://surveyjs.io/Editor/Editor and design a survey
- Click JSON Editor tab
- Copy the generated JSON
- Attempt to use this JSON to create a survey:
```
var surveyModel = new Survey.Model(jsonObject);
$("#surveyContainer").Survey({
model: surveyModel
});
```
- Observe the error message: *There is no visible page or question in the survey.*

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: Chrome latest
* editor version: latest

**Comment by dmitrykurmanov** [comment]
@nheath99 hello! I can't reproduce it. I've just add matrix dynamic question. And get this json:

```
{
 pages: [
  {
   elements: [
    {
     type: "matrixdynamic",
     choices: [
      1,
      2,
      3,
      4,
      5
     ],
     columns: [
      {
       name: "Column 1"
      },
      {
       name: "Column 2"
      },
      {
       name: "Column 3"
      }
     ],
     name: "question1"
    }
   ],
   name: "page1"
  }
 ]
}
```

and then I've put it in plnkr example and it is ok . Please check https://plnkr.co/edit/OJkFstevQt2Lj7nwvMfu?p=preview

**Comment by ahtsei** [comment]
@nheath99 Both 'questions' and 'elements' arrays are supported now. Maybe you're running an older version of the surveyjs library before they were both supported? This looks like the relevant commit: https://github.com/surveyjs/surveyjs/commit/20ba98b35d5c6ef9d28ca7daea7f7199e14b088c#diff-5314826f5a8010fdc3bcf5b4c164927d

**Comment by nheath99** [comment]
My bad - I was using version 0.12.3 rather than the latest (0.12.28) - I can only assume I've copied an example from somewhere with the wrong version.
