### ISSUE TITLE
Question - How to add property with modal like 'title'

### ISSUE THREAD

**Issue by traquall** [surveyjs/editor#158]
### Are you requesting a feature, reporting a bug or ask a question?

Asking a question

The property 'title' on the editor toolbox can be directly edited or users can open a modal to edit it.

How can I add a similar modal to another property ?

Thanks,
Traquall

**Comment by andrewtelnov** [comment]
@traquall [Here is the demo](https://surveyjs.io/Examples/Editor/?id=questioneditor), where we are adding a new tag property into Question Editor.

Thank you,
Andrew

**Comment by traquall** [comment]
@andrewtelnov The tag property doesn't got a modal.

I'm talking about the editor toolbox on the right, I'd like to add a property with a textfield and a modal like the title property. (just a modal with a bigger textarea)

**Comment by andrewtelnov** [comment]
@traquall That is easy :-) just set type to text, 
`{name: "myproperty", type:"text"}` 
or "myproperty:text"

Thank you,
Andrew

**Comment by traquall** [comment]
@andrewtelnov ok.... ^^' 
Thank you
