### ISSUE TITLE
can't drop question on dynamic panel.

### ISSUE THREAD

**Issue by muhfred** [surveyjs/editor#162]
### Are you requesting a feature, reporting a bug or ask a queation?

Bug

### What is the current behavior?

can't drop question in dynamic panel if the dynamic panel is added on a second page.

### What is the expected behavior?

drop questions in dynamic panel on any created page.

### How would you reproduce the current behavior (if this is a bug)?
[https://plnkr.co/edit/qL8RWw?p=preview](https://plnkr.co/edit/qL8RWw?p=preview)
please go to page 2 in the editor and drop a question inside the dynamic panel.
it shows an error in the browser's console: 

`knockout-min.js:66 Uncaught TypeError: Unable to process binding "value: function (){return koSelectedItem }"
Message: Cannot read property 'removeQuestion' of null
    at SurveyVerbChangePageItem.changePage (surveyeditor.js:3125)
    at a.Ub.La (surveyeditor.js:3114)
    at Function.notifySubscribers (knockout-min.js:33)
    at Function.d.W (knockout-min.js:36)
    at d (knockout-min.js:36)
    at Object.ra (knockout-min.js:55)
    at HTMLSelectElement.l (knockout-min.js:94)
    at HTMLSelectElement.dispatch (unpkg.com/jquery@3.2.1/dist/jquery.js:5206)
    at HTMLSelectElement.elemData.handle (unpkg.com/jquery@3.2.1/dist/jquery.js:5014)
    at Object.trigger (unpkg.com/jquery@3.2.1/dist/jquery.js:8201)
SurveyVerbChangePageItem.changePage @ surveyeditor.js:3125
(anonymous) @ surveyeditor.js:3114
notifySubscribers @ knockout-min.js:33
d.W @ knockout-min.js:36
d @ knockout-min.js:36
ra @ knockout-min.js:55
l @ knockout-min.js:94
dispatch @ unpkg.com/jquery@3.2.1/dist/jquery.js:5206
elemData.handle @ unpkg.com/jquery@3.2.1/dist/jquery.js:5014
trigger @ unpkg.com/jquery@3.2.1/dist/jquery.js:8201
(anonymous) @ unpkg.com/jquery@3.2.1/dist/jquery.js:8269
each @ unpkg.com/jquery@3.2.1/dist/jquery.js:362
each @ unpkg.com/jquery@3.2.1/dist/jquery.js:157
trigger @ unpkg.com/jquery@3.2.1/dist/jquery.js:8268
qa @ knockout-min.js:16
u @ knockout-min.js:35
g @ knockout-min.js:96
l @ knockout-min.js:44
a.w.a.j @ knockout-min.js:47
init @ knockout-min.js:96
(anonymous) @ knockout-min.js:65
u @ knockout-min.js:35
(anonymous) @ knockout-min.js:65
o @ knockout-min.js:10
g @ knockout-min.js:65
h @ knockout-min.js:63
k @ knockout-min.js:63
h @ knockout-min.js:63
k @ knockout-min.js:63
h @ knockout-min.js:63
a.ub @ knockout-min.js:69
(anonymous) @ knockout-min.js:103
b @ knockout-min.js:102
d @ knockout-min.js:103
n @ knockout-min.js:105
a.a.fb @ knockout-min.js:112
u @ knockout-min.js:35
a.j.q @ knockout-min.js:106
l @ knockout-min.js:44
h @ knockout-min.js:43
notifySubscribers @ knockout-min.js:33
d.W @ knockout-min.js:36
d @ knockout-min.js:36
SurveyVerbs.buildVerbs @ surveyeditor.js:3036
set @ surveyeditor.js:3019
SurveyEditor.selectedObjectChanged @ surveyeditor.js:5242
(anonymous) @ surveyeditor.js:4749
notifySubscribers @ knockout-min.js:33
d.W @ knockout-min.js:36
d @ knockout-min.js:36
SurveyObjects.addElement @ surveyeditor.js:4060
SurveyEditor.doOnQuestionAdded @ surveyeditor.js:5132
(anonymous) @ surveyeditor.js:5332
Event.fire @ survey.ko.js:1480
SurveyModel.questionAdded @ survey.ko.js:8414
PanelModelBase.onAddElement @ survey.ko.js:5106
(anonymous) @ survey.ko.js:4817
newArray.push @ survey.ko.js:1260
PanelModelBase.addElement @ survey.ko.js:5225
DragDropTargetElement.doDrop @ surveyeditor.js:2580
DragDropHelper.doDrop @ surveyeditor.js:2811
el.ondrop @ surveyeditor.js:4372
`

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: 

Test code

```
your_code_here

```

### Specify your

* browser: chrome latest
* editor version: 0.12.30

**Comment by andrewtelnov** [comment]
@muhfred It has been fixed. Thank you!

Andrew

**Comment by muhfred** [comment]
Thanks.
