### ISSUE TITLE
Options Menu not showing up

### ISSUE THREAD

**Issue by dprogaki** [surveyjs/editor#165]
The dots for the option menu are not working for me. I tried also testing it in a project on its own and they still don't work. The Edit button is working.
I am using the exact code suggested here:
https://surveyjs.io/Examples/Editor/?id=options

**Comment by andrewtelnov** [comment]
@dprogaki It is hard to say why it doesn't work with your code.
I would suggest press "Edit in Plunker" button in this example and compare all JavaScript libraries that we have with your including libraries.
You may check for console errors as well.

Thank you,
Andrew

**Comment by dprogaki** [comment]
All libraries are the same and there are no errors in the console or anything. I am using asp.net core mvc. Even when I just create a new mvc project and copy paste all necessary code in there it still does not work for me. 
Could it be some interaction with the already existing mvc code?

**Comment by andrewtelnov** [comment]
@dprogaki They are part of bootstrap,  glyphicon-option-horizontal: https://www.w3schools.com/bootstrap/bootstrap_ref_comp_glyphs.asp

Thank you,
Andrew

**Comment by dprogaki** [comment]
The problem is not with the glyphicon appearing. It is there but when I press it nothing happens, no options appear.

Thank you Andrew!

**Comment by andrewtelnov** [comment]
@dprogaki Got it. Do you have this script loaded? <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
We use it to show a modal window, the standard way for bootstrap. It requires jQuery as well.

Thank you,
Andrew

**Comment by dprogaki** [comment]
Yes it is there.

`    <script src="https://unpkg.com/jquery"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/knockout/3.3.0/knockout-min.js"></script>
    <script src="https://surveyjs.azureedge.net/0.12.34/survey.ko.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.0/ace.min.js" type="text/javascript" charset="utf-8"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.0/worker-json.js" type="text/javascript" charset="utf-8"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.0/mode-json.js" type="text/javascript" charset="utf-8"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
    <link href="https://surveyjs.azureedge.net/0.12.34/surveyeditor.css" type="text/css" rel="stylesheet" />
    <script src="https://surveyjs.azureedge.net/0.12.34/surveyeditor.js"></script>
    <script src="https://surveyjs.azureedge.net/0.12.34/survey.jquery.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/bootstrap@3.3.7/dist/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>`

All of the above are there. The survey library is included because I use it below the editor, but even when it is not there the problem persists

**Comment by andrewtelnov** [comment]
@dprogaki Please remove this script, <script src="https://surveyjs.azureedge.net/0.12.34/survey.jquery.js"></script>

Thank you,
Andrew

**Comment by dprogaki** [comment]
This is included because I use the library below the editor. Even when I remove it the problem persists. Still no menu appearing.

**Comment by dprogaki** [comment]
Thank you Andrew
