### ISSUE TITLE
Matrix single choice to Matrix checkbox choice 

### ISSUE THREAD

**Issue by rhalp10** [surveyjs/editor#166]
### Are you requesting a feature, reporting a bug or ask a question?
question
### What is the current behavior?
The editor is good it's working fine, but still insufficient of other things

### What is the expected behavior?
on matrix single choice how should i change this into check box but the same output like this
,the thing is i want to click both not single? 

![image](https://user-images.githubusercontent.com/13925864/31236777-aa4625d4-aa27-11e7-8d92-1d1cbd5ff26f.png)

or in the end of single choice or checkbox has others

### How would you reproduce the current behavior (if this is a bug)?

Maybe this is a enhancement and ADD into new features of this editor

#### Provide the test code and the tested page URL (if applicable)
Test code

```
 {
     type: "matrixdynamic",
     choices: [
      1,
      2,
      3,
      4,
      5
     ],
     columns: [
      {
       name: "Column 1",
       title: "Name of Examination",
       cellType: "text"
      },
      {
       name: "Column 2",
       title: "Date Taken",
       cellType: "text"
      },
      {
       name: "Column 3",
       title: "Rating",
       cellType: "text"
      }
     ],
     name: "Professional examination (s) Passed"
    },
    {
     type: "matrix",
     columns: [
      "Undergraduate/AB/BS ",
      "Graduate/MS/MA/Ph.D."
     ],
     name: "Reason (s) for taking the course (s) or pursuing degree (s).  You may check (/) more than one answer.",
     rows: [
      "High Grades in the course or subject area (s) related to the course",
      "Good grades in high school",
      "Influence of parents or relatives",
      "Peer Influence",
      "Inspired by a role model",
      "Strong passion for the profession",
      "Prospect for immediate employment",
      "Status or prestige of the profession",
      "Availability  of course offering in chosen institution",
      "Prospect of career advancement",
      "Affordable for the family",
      "Prospect of attractive compensation",
      "Opportunity for employment abroad",
      "No particular choice or no better idea"
     ]
    }
   ],
   name: "page2",
   title: "B. EDUCATIONAL BACKGROUND"
  }

```

### Specify your

* browser: chrome
* editor version: 0.12.30

**Comment by andrewtelnov** [comment]
@rhalp10 We are going to introduce the boolean question support in the matrix dynamic. After that you will be able to do this, by using matrix dynamic and boolean question inside the cells.
I may probably do it on the next week.

Thank you,
Andrew

**Comment by rhalp10** [comment]
your welcome andrew :+1:

**Comment by andrewtelnov** [comment]
@rhalp10 Here is the example with the latest version: https://plnkr.co/edit/pjOgBE?p=preview

**Comment by rhalp10** [comment]
@andrewtelnov  ow bytheway if i add   `hasOther: true`  is this will work or  maybe you should add on   `hasOther: true` on this matrix

**Comment by andrewtelnov** [comment]
@rhalp10 I do not get it. Does the last question has anything to do with boolean cell type? I just don't understand your question...

Thank you,
Andrew

**Comment by rhalp10** [comment]
@andrewtelnov i mean like the matrix single choice if i click Other (describe) the input box will show, 
![image](https://user-images.githubusercontent.com/13925864/31307642-16c9b1ac-ab9b-11e7-9397-a39690ff1369.png) example of this

**Comment by andrewtelnov** [comment]
@rhalp10 Do you want to show it for every cell or for every row or one for a matrix?

Thank you,
Andrew

**Comment by rhalp10** [comment]
@andrewtelnov like matrix single choice it has the feature of `hasOther: true` for enable other describe maybe you can add that thing like on matrix single choice

**Comment by andrewtelnov** [comment]
@rhalp10 Hm, I just don't get it. Do you need hasOther support for boolean question? You may use the checkbox question in this case. It does support hasOther.

Thank you,
Andrew
