### ISSUE TITLE
Add new question type

### ISSUE THREAD

**Issue by kailashyadav** [surveyjs/editor#17]
@andrewtelnov Add few more question type? for instance The company name, logo and introductory text for the Survey.

**Comment by andrewtelnov** [comment]
@kailashyadav Would it be better to create this outside the survey?
Or do you want them to be editable in the editor?

**Comment by kailashyadav** [comment]
I want them editable in survey, as any survey can have different settings
for same company.

**Comment by andrewtelnov** [comment]
@kailashyadav My e-mail you may find on this page: https://github.com/andrewtelnov and the survey js editor page (at the end) https://github.com/andrewtelnov/surveyjs.editor

About additional settings. The surveyjs is a container. The idea is to create a survey widget that everybody may insert at any part of his web page.
It is not hard to add these three properties into survey. The main problem, where do you want them to place: top, bottom, left, right.
Show them all the time, or just before or during running the first page.
I mean it may be easy to implement this functionality outside the widget.

Thank you,
Andrew

**Comment by myselflokendra** [comment]
@andrewtelnov : I tried to add a new type of question by forking your repo, I got how you are adding types of questions, however as soon as I add any new type of question, I am not able to find new Survey class in the dist folder, I think I am missing something which is why I am not able to generate Survey base class (survey.bootstrap.min.js), can you please help with this? Thanks much in advance!

**Comment by andrewtelnov** [comment]
@myselflokendra Yes, we are in process of a large refactoring at this very moment. I really hope we will finish with several days. There is no survey.bootstrap[.min].js any more. There is only survey[.min].js file. Please take a look at: https://github.com/andrewtelnov/surveyjs/issues/86.
Additionally, we are moving to webpack right now: https://github.com/andrewtelnov/surveyjs/issues/75. It will allow to use the library in a modern way.
I am very sorry for the inconvenience. I will be back as soon as we will finish with the refactoring. We are working on changing the designer code.

Thank you,
Andrew

**Comment by myselflokendra** [comment]
@andrewtelnov : Gotcha! Btw, I was able to understand after I sent it you, I am doing the same way. Thanks for the quickest response.

I am able to add new question type now and now I have another question for you, I needed to manually add the class in survey.d.ts, to me it should be auto populate, right? Or I am missing something.

**Comment by andrewtelnov** [comment]
@myselflokendra We used to build d.ts file as in a gulp task during typescript compilation. Unfortunately, right now we stuck exactly with this problem. We can not use the survey.d.ts file that typescript + webpack generates to us. It seems we can't use the old d.ts file with the new created library :-(
Currently we are thinking to try browserify. We are working on this exactly issue right now. Again, sorry about that.

**Comment by andrewtelnov** [comment]
@myselflokendra I just realized that you are not using  a master github version of editor. It means you may just add a class to a .d.ts file and you will be fine.
If you do not want to have any specific functionality for your question in the editor, the only thing you need - is to register the question in the QuestionFactory:
`QuestionFactory.Instance.registerQuestion("questionname", (name) => { return new QuestionMyName(name); });
`
and tell JSON serializer about your properties. Similar to this:
`JsonObject.metaData.addClass("questionname", [{ name: "cols:number", default: 50 }, { name: "rows:number", default: 4 }], function () { return new QuestionCommentModel(""); }, "question");
`
You may post here a link to your code and I may help with registerQuestion and JSON serialization.

**Comment by andrewtelnov** [comment]
I have created a new question type as a plugin. Please, take a look: https://github.com/andrewtelnov/surveyjs/tree/master/src/plugins

**Comment by andrewtelnov** [comment]
@myselflokendra It is possible to use third-party widgets now. It give unlimited possibilities. Here is the [demo](http://editor.surveyjs.io/examples/customwidgets.html).
