### ISSUE TITLE
Matrix Question and Answer  JSON.stringify(result.data)

### ISSUE THREAD

**Issue by rhalp10** [surveyjs/editor#170]
### Are you requesting a feature, reporting a bug or ask a queation?
Question and Improvement

### What is the current behavior?

![image](https://user-images.githubusercontent.com/13925864/31311024-4e47c2a0-abd6-11e7-8879-f64d217fe7ca.png)

umm... i notice this recently the column will become the answer for each rows like**_`{"rows":column }`_** then the **_`name:`_** code will become the the question. but the issue is the data is too much long since you used name: for question instead of using like label for question display. maybe you must separate question name and answer name, usually name used for getting name of input data then send to the dataquery, then the **_`$_POST`_** data become to long. like this..
once you result **_`JSON.stringify(result.data)`_** some of the result data is unnecessary like questions
![image](https://user-images.githubusercontent.com/13925864/31311027-56b3b430-abd6-11e7-9a42-b0a5a617bf0a.png)

### What is the expected behavior?
just result what is really needed since the question is a static, the important is to display all picked result per each question,

**Comment by andrewtelnov** [comment]
@rhalp10 You may use it as:
rows: [{value: "val1", text: "My Tittle1" },  {value: "val2", text: "My Tittle2" }]

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@rhalp10 Please use this repo https://github.com/surveyjs/surveyjs/issues to ask questions about the library.

Thank you,
Andrew

**Comment by rhalp10** [comment]
@andrewtelnov sorry about that

**Comment by rhalp10** [comment]
@andrewtelnov 
i already fix this using ` name: "is for variable",
       title: "is for the questions",` 
![image](https://user-images.githubusercontent.com/13925864/31586224-cf7cfaae-b200-11e7-9c1d-e4895a3d1afc.png)
could you help me how to how to display the nested ajax array on php ?
`echo $survey_result->P_Address;` this will display only one data but on the nested i don't know how to foreach them like this, ? 
![image](https://user-images.githubusercontent.com/13925864/31586270-2feb8c2a-b201-11e7-8219-5fd5a946efcd.png)
