### ISSUE TITLE
Ranking question properties bug

### ISSUE THREAD

**Issue by steff381** [surveyjs/editor#171]
### Are you requesting a feature, reporting a bug or ask a queation?
bug

### What is the current behavior?
Environment: Online Survey Editor> Survey Designer tab 
Question Type: "rating"
Issue: Setting the rateMax, rateMin, or rateStep value have no impact on the displayed question. e.g. the widget only ever displays a scale if 1 to 5 in the "survey test" tab and in the final survey on the Surveyjs.io service page. 

### What is the expected behavior?
Changing rateMax, rateMin, or rateStep value changes the widget 

### How would you reproduce the current behavior (if this is a bug)?
In the Survey Designer Tab> create a new survey > create a Rating question > Change  rateMax, rateMin, or rateStep value.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: Chrome
* editor version: 0.12.31

**Comment by andrewtelnov** [comment]
@steff381 Indeed, values don't load correctly. I will work on it.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@steff381 The fix will be available in the next minor update on the next week.

Thank you,
Andrew
