### ISSUE TITLE
Online Editor - Question Widget onFocus issue

### ISSUE THREAD

**Issue by steff381** [surveyjs/editor#173]
### Are you requesting a feature, reporting a bug or ask a queation?
Bug

### What is the current behavior?
In the online editor, if I click on any question widget (Except for the last or the first widget in the set) the  frame scrolls to the top of the list. This issue adversely affects user experience because one must then scroll back down to the selected question. 

### What is the expected behavior?
Selecting a question widget does not change scroll location in the active frame. 

### How would you reproduce the current behavior (if this is a bug)?
Create a new survey in the survey editor and create 10 to 15 new questions. scroll down an choose the second to last question created. 

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: Chrome
* editor version: 0.12.32 (tested today after update)

**Comment by steff381** [comment]
Note: The same scrolling issue occurs when an existing question widget changes position using the drag-and-drop.

**Comment by andrewtelnov** [comment]
@steff381 I will take a look at it tomorrow. I agree it is an usability bug.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@steff381 The problem is fixed. The fix will be available in the next release.

Thank you,
Andrew
