### ISSUE TITLE
When saving a duplicate value and text, the text disappears after saving

### ISSUE THREAD

**Issue by chrisweconect** [surveyjs/editor#174]
### Are you requesting a feature, reporting a bug or ask a question?
Possible Bug.

### What is the current behavior?
When a user attempts to save a value that's the same as the text, the text disappears when the editor is reopened.  The value is also pushed outside of the hash and rendered in the survey json as a simple string.

See below:

![screen shot 2017-10-12 at 12 27 39](https://user-images.githubusercontent.com/24935674/31491788-d14a71dc-af48-11e7-85aa-a5633d3a50d4.png)

After saving:

![screen shot 2017-10-12 at 12 17 21](https://user-images.githubusercontent.com/24935674/31491591-246c21ae-af48-11e7-9fa8-a24ad25408e2.png)

In the generated JSON:

![screen shot 2017-10-12 at 12 22 19](https://user-images.githubusercontent.com/24935674/31491731-9173cd42-af48-11e7-95c8-8145c6e5bf5d.png)

### What is the expected behavior?

When an editor user enters a value (regardless if it's the same as the text), both fields should be saved the same way and rendered in the survey json as such. 

### Specify your

* browser: Chrome 61.0.3163.100 (Official Build) (64-bit)
* editor version: surveyjs Editor v0.12.32

**Comment by chrisweconect** [comment]
This is a follow-up to https://github.com/surveyjs/editor/issues/14 - still doesn't work.

**Comment by andrewtelnov** [comment]
@chrisweconect Please use the following code:
`editor.alwaySaveTextInPropertyEditors = true;`
Here is the example: https://plnkr.co/edit/p8eoKkPI7xrwuMN5ekdr?p=preview

PS: I will add documentation to this properties.

Thank you,
Andrew

**Comment by chrisweconect** [comment]
Thanks!

Chris Whamond

On Oct 12, 2017, at 20:13, Andrew <notifications@github.com<mailto:notifications@github.com>> wrote:


@chrisweconect<https://github.com/chrisweconect> Please use the following code:
editor.alwaySaveTextInPropertyEditors = true;
Here is the example: https://plnkr.co/edit/p8eoKkPI7xrwuMN5ekdr?p=preview

PS: I will add documentation to this properties.

Thank you,
Andrew
