### ISSUE TITLE
2 errors logged in console on editor load (example site)

### ISSUE THREAD

**Issue by AndOne1974** [surveyjs/editor#176]
### Are you requesting a feature, reporting a bug or ask a queation?

bug

### What is the current behavior?

js error

### What is the expected behavior?

no js error ;)

### How would you reproduce the current behavior (if this is a bug)?

goto https://surveyjs.io/Editor/Editor/

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjs.io/Editor/Editor/

### Specify your

* browser: FF 
* editor version: latest

**Comment by AndOne1974** [comment]
![screenshot_2](https://user-images.githubusercontent.com/1571332/31819132-8c1e305e-b59b-11e7-80d8-1a3461511dcc.png)

**Comment by andrewtelnov** [comment]
@tsv2013 could you please take a look at this bug?

Thank you,
Andrew

**Comment by tsv2013** [comment]
@andrewtelnov Sure

**Comment by tsv2013** [comment]
For some reason files from `surveyjs.io/fonts` folder are not accessable in spite of they are indeed published.

**Comment by tsv2013** [comment]
Fixed. Thanks to SO - https://stackoverflow.com/questions/18897079/404-on-static-content-svg-woff-ttf-on-azure
