### ISSUE TITLE
Using surveys created by surveyjs-editor

### ISSUE THREAD

**Issue by noorball** [surveyjs/editor#178]
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

Hello,

I can create survey descriptions using surveyjs-editor (SurveyEditor), can test it in surveyjs-editor without problem. 
How can I use it? Can I use it as an argument in Survey.Model()? 
Here is the rough code.

```
            //"json" is survey created by SurveyEditor
            var model = new Survey.Model(json);
            $("#surveyElement").Survey({
                model:model,
                onComplete:sendDataToServer,
            });
```

This code shows the survey without questions telling that there is no questions in the survey.

Thanks.

**Comment by andrewtelnov** [comment]
@noorball Could you check if this json will work: 
`{ questions: [ {type:"text", name: "question1" } ] }`
As well check in debugger, that you are passing the correct model.

Thank you,
Andrew

**Comment by noorball** [comment]
Thanks for response, @andrewtelnov 
Yes, this code does work.
In debugger I can see that the model is in the form 
`  {   "elements": [{ "type": "radiogroup", "name": "question1"  }   ]  }` and if I change `"elements"` to `"questions"` it will work. 
Is it desired behaviour? Is there any solution without manual renaming keys in json object?

Thank you,
Nurbol

**Comment by andrewtelnov** [comment]
@noorball What version of SurveyJS are you using?
Editor will generate the code like this.
```
{ pages: [ 
{ elements: [ {type:"text", name: "question1" } ] }
]}
```
Inside the pages, you may use elements or questions.
Does it work for you?
Maybe you will post your JSON here? Probably all your questions/pages are invisible.

Thank you,
Andrew

**Comment by noorball** [comment]
> @noorball What version of SurveyJS are you using?

Version of SurveyJS is 12.32.

> Inside the pages, you may use elements or questions.
> Does it work for you?

I can use questions, but not elements. There is a message "There is no visible page or question in the survey" if I use "elements".

> Maybe you will post your JSON here? Probably all your questions/pages are invisible.

I think if the problem was the "invisible" property then using "questions" should not have worked as well. 
The problem can be reproduced if we rename property "questions" in the json to "elements" in this [jsfiddle](https://jsfiddle.net/surveyjs/2nvc4to5/?utm_source=website&utm_medium=embed&utm_campaign=2nvc4to5)

For whatever reason I can't use "elements" inside pages. What can we do with this?

**Comment by andrewtelnov** [comment]
@noorball The editor should give you the following json:
https://jsfiddle.net/rgmp6L1g/1/
You do not use "pages" if there is only one page. However, in this case "elements" doesn't work. You will have to use "questions".
I think I will add support for elements as well.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@noorball I just looked at the code and we do support elements inside survey already.
In your fiddle you were using the old version of SurveyJS, https://unpkg.com/survey-jquery@0.12.10 
The current version is 0.12.34, I have updated to the latest version at it works as expected:
https://jsfiddle.net/6y1eky9L/1/ 

Thank you,
Andrew

**Comment by noorball** [comment]
Thanks, updating SurveyJS to the last version has helped.
