### ISSUE TITLE
angular quickstart

### ISSUE THREAD

**Issue by rafalzmuda** [surveyjs/editor#179]
Hello,
I tried to launch angular version without success.
my steps:
git clone https://github.com/surveyjs/quickstart
cd quickstart
npm install
npm start

last command throws errors (see below). I can launch app with npm run serve but appearance is  broken a bit and question editor popup is hidden (I can see it with inspector).
Second issue is that modifications from examples "Add properties" and "Customize Editor" make no effect. React version have same issue with modifications. Plunker examples work fine on my desktop.

npm start errors and log file:

> angular-surveyjs-quickstart@1.0.0 prestart /home/rafal/PhpstormProjects/quickstart
> npm run build

> angular-surveyjs-quickstart@1.0.0 build /home/rafal/PhpstormProjects/quickstart
> tsc -p src/

node_modules/@types/react/index.d.ts(171,34): error TS1005: ',' expected.
node_modules/@types/react/index.d.ts(172,34): error TS1005: ',' expected.
node_modules/@types/react/index.d.ts(2636,43): error TS1005: ']' expected.
node_modules/@types/react/index.d.ts(2636,44): error TS1005: ';' expected.
node_modules/@types/react/index.d.ts(2636,45): error TS1128: Declaration or statement expected.
node_modules/@types/react/index.d.ts(2636,46): error TS1128: Declaration or statement expected.
node_modules/@types/react/index.d.ts(2636,61): error TS1005: '(' expected.
node_modules/@types/react/index.d.ts(2695,1): error TS1128: Declaration or statement expected.

npm ERR! Linux 4.10.0-37-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! angular-surveyjs-quickstart@1.0.0 build: `tsc -p src/`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the angular-surveyjs-quickstart@1.0.0 build script 'tsc -p src/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-surveyjs-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc -p src/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-surveyjs-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-surveyjs-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/rafal/PhpstormProjects/quickstart/npm-debug.log

npm ERR! Linux 4.10.0-37-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! angular-surveyjs-quickstart@1.0.0 prestart: `npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-surveyjs-quickstart@1.0.0 prestart script 'npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-surveyjs-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-surveyjs-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-surveyjs-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/rafal/PhpstormProjects/quickstart/npm-debug.log

/home/rafal/PhpstormProjects/quickstart/npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular-surveyjs-quickstart@1.0.0~prestart: angular-surveyjs-quickstart@1.0.0
6 verbose lifecycle angular-surveyjs-quickstart@1.0.0~prestart: unsafe-perm in lifecycle true
7 verbose lifecycle angular-surveyjs-quickstart@1.0.0~prestart: PATH: /usr/share/npm/bin/node-gyp-bin:/home/rafal/PhpstormProjects/quickstart/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
8 verbose lifecycle angular-surveyjs-quickstart@1.0.0~prestart: CWD: /home/rafal/PhpstormProjects/quickstart
9 silly lifecycle angular-surveyjs-quickstart@1.0.0~prestart: Args: [ '-c', 'npm run build' ]
10 silly lifecycle angular-surveyjs-quickstart@1.0.0~prestart: Returned: code: 1  signal: null
11 info lifecycle angular-surveyjs-quickstart@1.0.0~prestart: Failed to exec prestart script
12 verbose stack Error: angular-surveyjs-quickstart@1.0.0 prestart: `npm run build`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
12 verbose stack     at emitTwo (events.js:87:13)
12 verbose stack     at EventEmitter.emit (events.js:172:7)
12 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
12 verbose stack     at emitTwo (events.js:87:13)
12 verbose stack     at ChildProcess.emit (events.js:172:7)
12 verbose stack     at maybeClose (internal/child_process.js:821:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
13 verbose pkgid angular-surveyjs-quickstart@1.0.0
14 verbose cwd /home/rafal/PhpstormProjects/quickstart
15 error Linux 4.10.0-37-generic
16 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
17 error node v4.2.6
18 error npm  v3.5.2
19 error code ELIFECYCLE
20 error angular-surveyjs-quickstart@1.0.0 prestart: `npm run build`
20 error Exit status 1
21 error Failed at the angular-surveyjs-quickstart@1.0.0 prestart script 'npm run build'.
21 error Make sure you have the latest version of node.js and npm installed.
21 error If you do, this is most likely a problem with the angular-surveyjs-quickstart package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     npm run build
21 error You can get information on how to open an issue for this project with:
21 error     npm bugs angular-surveyjs-quickstart
21 error Or if that isn't available, you can get their info via:
21 error     npm owner ls angular-surveyjs-quickstart
21 error There is likely additional logging output above.
22 verbose exit [ 1, true ]

OS: Ubuntu 16.4
Browser: FF 56 (64-bit)
npm 3.5.2
node 4.2.6

OS: Windows 10
Browser: FF, Chrome, Edge (all latest)

**Comment by tsv2013** [comment]
I've bumped up the TSC version - now works ok for me. @rafalzmuda - Please check it works for you.

**Comment by rafalzmuda** [comment]
npm start works fine now, but I still have some css problems 
https://screenpresso.com/=dMSSd this is what edit question modal looks like. Also notice the look of  property filter and three dots button next to Edit button. Should I crete a separate issue for this?

**Comment by andrewtelnov** [comment]
@rafalzmuda We are working on this issue. @dmitrykurmanov is removing bootstrap script dependency from the Editor. It creates the issue.

Thank you,
Andrew
