### ISSUE TITLE
Matrix Array label_name per column and per rows 

### ISSUE THREAD

**Issue by rhalp10** [surveyjs/editor#181]
### Are you requesting a feature, reporting a bug or ask a queation?

Features, or something

### What is the current behavior?

![image](https://user-images.githubusercontent.com/13925864/31986414-fccbe74e-b99a-11e7-818f-84f6389febd6.png)

### What is the expected behavior?
Uhm

![image](https://user-images.githubusercontent.com/13925864/31986497-4fbd427c-b99b-11e7-8eae-c8c48df7eae4.png)
maybe it can be shorter like simple output titles,
![image](https://user-images.githubusercontent.com/13925864/31986784-54aa8582-b99c-11e7-8f6b-1bdaf1c7d13a.png)

**Comment by andrewtelnov** [comment]
@rhalp10 You may write choices like this:
choices: ["1|Value 1", "2|Value 2"]

Thank you,
Andrew
