### ISSUE TITLE
Cannot delete question from dynamic panel

### ISSUE THREAD

**Issue by muhfred** [surveyjs/editor#184]
### Are you requesting a feature, reporting a bug or ask a queation?

bug

### What is the current behavior?

If I inserted a question in dynamic panel, I cannot delete it.

### What is the expected behavior?

Delete question from dynamic panel.

### How would you reproduce the current behavior (if this is a bug)?

[https://surveyjs.io/Editor/Editor/](url)
Please insert a question in a dynamic panel then try to delete it.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: chrome latest
* editor version: latest

**Comment by andrewtelnov** [comment]
@muhfred The bug has been fixed. The fix will be available in the next minor update.

Thank you,
Andrew
