### ISSUE TITLE
mode display not disable Question Multiple Text

### ISSUE THREAD

**Issue by cracki** [surveyjs/editor#186]
### Are you requesting a feature, reporting a bug or ask a queation?
reporting a bug

### What is the current behavior?
set mode:display but QuestionMultipleText is editable

### What is the expected behavior?
setting mode to display must disable QuestionMultipleTextrows

### How would you reproduce the current behavior (if this is a bug)?
set mode:display and add QuestionMultipleText

thank you

**Comment by cracki** [comment]
and i think , it is better to remove submit button in display mode

**Comment by andrewtelnov** [comment]
@cracki I could not reproduce this behavior for any 
platform: https://surveyjs.io/Examples/Library/?id=survey-displaymode
and in Editor as well: https://surveyjs.io/Editor/Editor/ (drop multiple text on designer and set display mode to the survey).
Text boxes are read only and there is no submit button.

Thank you,
Andrew

**Comment by cracki** [comment]
oh excuse me
no problem 

thank you
