### ISSUE TITLE
How to load survey from another backend?

### ISSUE THREAD

**Issue by legreco** [surveyjs/editor#187]
When i use 
```
editor.loadSurvey("some_uuid");
```
the request url is:
```
https://dxsurveyapi.azurewebsites.net/api/Survey/getSurvey?surveyId=d5220f76-4802-40cf-ad67-61d7e55608e5
```
How to load survey from another url?

**Comment by andrewtelnov** [comment]
@legreco You may load survey json as a text from your back-end and then set it to editor:
editor.text = yourJsonAsText;

You may take a look at two our back-end examples:
https://github.com/surveyjs/surveyjs-php
https://github.com/surveyjs/surveyjs-aspnet-mvc

Thank you,
Andrew

**Comment by legreco** [comment]
Thanks. It works!

**Comment by rajat29gupta** [comment]
> @legreco You may load survey json as a text from your back-end and then set it to editor:
> editor.text = yourJsonAsText;
> 
> You may take a look at two our back-end examples:
> https://github.com/surveyjs/surveyjs-php
> https://github.com/surveyjs/surveyjs-aspnet-mvc
> 
> Thank you,
> Andrew



> @legreco You may load survey json as a text from your back-end and then set it to editor:
> editor.text = yourJsonAsText;
> 
> You may take a look at two our back-end examples:
> https://github.com/surveyjs/surveyjs-php
> https://github.com/surveyjs/surveyjs-aspnet-mvc
> 
> Thank you,
> Andrew

Thanks :)
