### ISSUE TITLE
HOW TO SHOW ONLY THE SURVEY?

### ISSUE THREAD

**Issue by legreco** [surveyjs/editor#189]
Is there any options to hide toolbox and property viewer in the Survey Designer? i want to show only a non-editable version of the survey.

**Comment by andrewtelnov** [comment]
@legreco use this options: {showPropertyGrid: false}, to hide property viewer. However, there is no option to hide the toolbox yet. 
In fact, if you want to show the survey only with all pages, then you may run survey and show pages toolbar:
https://plnkr.co/edit/0vI5Xx?p=preview

You may set the survey in designer mode: survey.setDesignMode(true);

Thank you,
Andrew
