### ISSUE TITLE
Ability to customize the html in testSurvey (preview) tab

### ISSUE THREAD

**Issue by ahtsei** [surveyjs/editor#194]
Hi there,

Is it currently possible to customize the layout of the contents in the testSurvey (preview) tab?

For example, would it be possible to add a custom header and/or footer within that tab? The use case being if you wanted to see how the survey would look like with a custom themed header and footer.

Thanks,
Aleks

**Comment by andrewtelnov** [comment]
@ahtsei Unfortunately, we do not have this functionality yet. If you need it urgent, I may fork the repo and modify the html template. I may help you with it.

Thank you,
Andrew

**Comment by ahtsei** [comment]
Thanks for the quick reply. It's not urgent, but I appreciate the offer. I'm sure you're quite busy with more useful/common issues, so I might might try it myself and if I get stuck maybe re-open this issue for some assistance? Thanks again @andrewtelnov.

**Comment by bach-sctv** [comment]
hello!

Is it currently possible to customize the layout of the contents in the  Choose device ?
For example, Is it possible to add more devices or reduce the number of devices?
Thanks,
bach
