### ISSUE TITLE
Optional "Add to toolbox" dropdown option

### ISSUE THREAD

**Issue by ahtsei** [surveyjs/editor#195]
Is it possible to somehow not show the "Add to toolbox" option in this dropdown? 

<img width="208" alt="screen shot 2017-11-15 at 4 29 06 pm" src="https://user-images.githubusercontent.com/3906239/32826140-3be72474-ca22-11e7-80c8-05062b210023.png">

**Comment by andrewtelnov** [comment]
@ahtsei Please take a look at this demo: https://surveyjs.io/Examples/Editor/?id=elementmenu

Thank you,
Andrew

**Comment by ahtsei** [comment]
Thanks @andrewtelnov, but I'm struggling to get the removal of "Add to toolbox" working. I'm trying something like this, but can't even get the console.log output:

```
this.editor.onDefineElementMenuItems.remove(function(editor, options) {
    console.log('options', options.items);
});
```

**Comment by andrewtelnov** [comment]
@ahtsei Here is the example with minimum code: https://plnkr.co/edit/v58JEYPXATkFM5Y1WDgh?p=preview

Thank you,
Andrew

**Comment by ahtsei** [comment]
Thanks for that @andrewtelnov. I understand that part ie. adding a new option with a custom click handler. But how do I remove one of the default ones? ie. Remove "Add to toolbox" and leave the "Copy" and "Delete question" in there.

**Comment by andrewtelnov** [comment]
@ahtsei You may do an indexOf by name and simply remove them, I have updated the example: https://plnkr.co/edit/v58JEYPXATkFM5Y1WDgh?p=preview

Thank you,
Andrew

**Comment by ahtsei** [comment]
Awesome, thank you for the quick response.

**Comment by mkopinsky** [comment]
Just a side note, we experienced a regression because of the `splice(0,1)` in that code sample. The fixed code is (depending on whether you need to support IE):
```javascript
  editor.onDefineElementMenuItems.add(function(editor, options) {
    // Better version, not compatible with IE :-(
    var indexToDelete = options.items.findIndex(function(element, index, array) {
        return element.name == 'addToToolbox';
    });
    // IE compatible version:
    var indexToDelete = -1;
    for (var i = 0; i < options.items.length; ++i) {
        if (options.items[i].name == 'addToToolbox') {
            indexToDelete = i;
            break;
        }
    }
    options.items.splice(indexToDelete, 1);
  });
```
@andrewtelnov FYI in case you want to update any docs
