### ISSUE TITLE
Question - Is there a way to select question div ?

### ISSUE THREAD

**Issue by traquall** [surveyjs/editor#196]
### Are you requesting a feature, reporting a bug or ask a queation?

Question

In order to change the css of some specific question div, I would like to select a question div from my object 'editor.survey.currentPage.element[i]' , for example doing like this "document.getElementById('divOfMyQuestion'+id)".
Is this possible for the moment ?

Thank you 

Traquall

**Comment by andrewtelnov** [comment]
@traquall Here is the example: https://plnkr.co/edit/y4Yunm?p=preview

Thank you,
Andrew

**Comment by traquall** [comment]
@andrewtelnov Thank you !

Traquall

**Comment by traquall** [comment]
@andrewtelnov I got the same question but with the edit modal.

Thank you

Traquall

**Comment by andrewtelnov** [comment]
@traquall by edit model, do you mean the editor for "default value" property?

Thank you,
Andrew

**Comment by traquall** [comment]
@andrewtelnov I mean the modal which open when I click on the 'edit button' of a question.

Thank you

**Comment by andrewtelnov** [comment]
@traquall I guess you are talking about Question/Panel/Page/Survey Editors.
Could you please describe your task? Probably we will provide an API for this task.

Thank you,
Andrew

**Comment by traquall** [comment]
@andrewtelnov Here is an example : I need to add an image to this editor

![capture_d ecran_2017-12-01_a_11 25 22](https://user-images.githubusercontent.com/11782554/33875570-ec83a81a-df22-11e7-850c-b6125bf6350a.png)


Thank you,
Traquall

**Comment by andrewtelnov** [comment]
@traquall Do you want to have it for specific question, by question name for example. Am I right?


Thank you,
Andrew

**Comment by traquall** [comment]
@andrewtelnov Yes totally
