### ISSUE TITLE
Survey editor pages removal and customisation

### ISSUE THREAD

**Issue by ahtsei** [surveyjs/editor#198]
Hi again,

Is it possible to remove an empty page while building the survey? eg. if a user adds a new page but then realises they don't need it.

Also, is it possible to customise the page labels? Something similar to `editor.onQuestionAdded` functionality possibly.

Many thanks.

**Comment by andrewtelnov** [comment]
@ahtsei There is a delete button near to dropbox on the right. Select the page and click on it.
I think we will add element menu for the page as well. 

Just select the page and change the page name or do you want to change the name in the code?

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@ahtsei I have added onPageAdded event, here is the example of using:
```
editor.onPageAdded.add(function(editor, options){ 
  alert(options.page.name);
});

```
It will be in the next minor update.

Thank you,
Andrew

**Comment by ahtsei** [comment]
Thanks @andrewtelnov,

Ah I see, it's in the properties grid. I didn't see it because I'm hiding the properties grid in my project. An element menu decoupled from the properties grid would be ideal. 👍

**Comment by andrewtelnov** [comment]
@ahtsei We will work on this: https://github.com/surveyjs/editor/issues/200

Thank you,
Andrew
