### ISSUE TITLE
Multiple editors on the same page

### ISSUE THREAD

**Issue by korosaitama** [surveyjs/editor#209]
### Are you requesting a feature, reporting a bug or ask a question?

Bug

### What is the current behavior?

After the creation of different editor on the same page, i can edit ONLY the questions of the first editor.
I cannot modify one of the question of the second editor, third editor, and so on ...(the question editor ALWAYS shows me the information of the question selected at the first editor)

### What is the expected behavior?

View the correct information for the current selected question to edit

### How would you reproduce the current behavior (if this is a bug)?

Create many editor on the same page.
Then:
  - Create different questions on different editor
  - Select a question at the first editor
  - Try to edit a question on an editor different than the first

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
var survey1 = new SurveyEditor.SurveyEditor("div1", {});
var survey2 = new SurveyEditor.SurveyEditor("div2", {});
var survey3 = new SurveyEditor.SurveyEditor("div3", {});
...

```

### Specify your

* browser: All
* editor version:

**Comment by andrewtelnov** [comment]
@korosaitama  I will work on the fix. It is a known issue and it is time to fix it!

**Comment by andrewtelnov** [comment]
@korosaitama I have fixed the issue. The fix will be available in the next minor.

Thank you,
Andrew

**Comment by korosaitama** [comment]
Thanks you too

**Comment by mkopinsky** [comment]
Awesome! I came across this issue yesterday as well. What is the approximate timeframe for the next minor release? (No rush, I just want to know what to communicate to my stakeholders.)
