### ISSUE TITLE
load editor with html question

### ISSUE THREAD

**Issue by cracki** [surveyjs/editor#210]
### Are you requesting a feature, reporting a bug or ask a queation
ask a queation

### What is the current behavior?
loading survey text with .text method include html question get error

### What is the expected behavior?
init editor

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
https://plnkr.co/edit/S7iLlC2APugzTBBp5RdS?p=preview

**Comment by tsv2013** [comment]
You are using double quotes inside double quotes - this breaks the string.
Inner double quotes should be preceeded with the backslash in this case:
`"<img src=\"https://placehold.it/300x100\" alt=\"test\"/>"`

**Comment by cracki** [comment]
No currently double quotes added with the backslash (line 33)
The JSON is exactly same as editor get text methode and is valid
http://jsoneditoronline.org/?id=9a3fc752e5bc4776a005ce61c202efa0

**Comment by tsv2013** [comment]
I'm not sure I've understood you right. I open your link to the "Json Editor Online", it contains the JSON with backslashed double quotas. If I remove backslash, it complains on the wrong JSON. Hence backslashes are required.
So - what's the problem? Who gives wrong JSON?

**Comment by cracki** [comment]
json string that is valid and contain backslash is passed to survey.text but editor remove backslash

**Comment by tsv2013** [comment]
In this case it's a bug. We'll fix it.

**Comment by cracki** [comment]
Thank you
another similar bug:
https://plnkr.co/edit/Q4JeWutIjrTmEx0m7k2y?p=preview
**using new line in title

**Comment by tsv2013** [comment]
@cracki I've wrote this unit test:

```JavaScript
QUnit.test("Escape HTML question string", function (assert) {
    var jsonText = JSON.stringify({"pages":[{"name":"page1","elements":[{"type":"html","name":"question3","html":"<img src=\"https://placehold.it/300x100\" alt=\"test\"/>"}]}]});
    //var jsonText = '{\"pages\":[{\"name\":\"page1\",\"elements\":[{\"type\":\"html\",\"name\":\"question3\",\"html\":\"<img src=\\\"https://placehold.it/300x100\\\" alt=\\\"test\\\"/>\"}]}]}'; 
    var editor = new SurveyEditor();
    editor.text = jsonText;
    assert.equal(editor.survey.getAllQuestions().length, 1);
    var q3 = editor.survey.getQuestionByName("question3");
    assert.ok(!!q3);
    assert.equal((<Survey.QuestionHtml>q3).html, "<img src=\"https://placehold.it/300x100\" alt=\"test\"/>");
    assert.equal(editor.text.replace(/\s+|\t+|\n+/g, ""), jsonText.replace(/\s+|\t+|\n+/g, ""));
});
```

I passed correctly escaped JSON to the editor, check HTML question's html property value and then got whole JSON back. Both JSONs are equal (I removed spaces, tabs and new lines).

Am I missing something? Probably I don't understand your case right...
