### ISSUE TITLE
Ability to change the Type of any Question

### ISSUE THREAD

**Issue by elkinporras** [surveyjs/editor#212]
### Are you requesting a feature, reporting a bug or ask a queation?

Feature

### What is the current behavior?

Only Checkbox, RadioButton and Checkbox could change between them,  

### What is the expected behavior?

In many cases the user add a Single Input but in some time they discover that making it a Checkbox or other item could be better.   At this time the user have to delete and create a new one.   

It should be possible in both ways .

The option should be visible on the top of the parameters and not on the end.

### How would you reproduce the current behavior (if this is a bug)?

Any Survey

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:  any
* editor version:   any

**Comment by andrewtelnov** [comment]
@elkinporras To be honest, I can't say I like this idea
I have just change the UI. Now the "Convert to [Question Type Name]" items are shown in the question menu, together with Add to Toolbox, Copy and Delete. People do not find the "Change to [Question Type Name]" dropdown on the bottom.
I have added convertion comment into text and vice versa.
I do not think that somebody would really like to convert text to checkbox or radiogroup.

Anyway, there will be an API, so you will be able to add any conversion you want, like:
```
SurveyEditor.QuestionConverter.addConvertInfo("text", "dropdown");
SurveyEditor.QuestionConverter.addConvertInfo("dropdown", "text");

```
Thank you,
Andrew


Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@elkinporras You may use the code above and setup any conversion you want in your Editor.

Thank you,
Andrew
