### ISSUE TITLE
angular 2 SurveyJS Editor Within Modal. Everything Greyed Out

### ISSUE THREAD

**Issue by OmarBelguith** [surveyjs/editor#220]
### Are you requesting a feature, reporting a bug or ask a queation?
A bug.
### Problem
If i'm adding the survey-editor.css file to my angular-cli.json once modal is triggered the screen is greyed out if i'm not adding the file everything works fine but the survey editor will be without it's css

**Comment by tsv2013** [comment]
@OmarBelguith Could you give us a project or sandbox in order to reproduce the issue on our side and fix it?

You can modify one of our samples:
http://plnkr.co/edit/xOtZkj?p=preview
https://github.com/surveyjs/surveyjs_angular_cli
https://github.com/surveyjs/angular-seed
or create your own one.

**Comment by OmarBelguith** [comment]
https://github.com/SwatMedtech/InteractiveInterface

**Comment by tsv2013** [comment]
`ng serve` command (after `npm i`) from the `angular-src` folder gives the following errors (you can easily reproduce it via trying to start from cloning into new folder):

```
ERROR in C:/Temp/InteractiveInterface/angular-src/src/app/app.module.ts (23,31): Cannot find module 'ng2-bs3-moda
l'.

ERROR in C:/Temp/InteractiveInterface/angular-src/src/polyfills.ts (1,25): Cannot find module 'jquery'.

ERROR in Error encountered resolving symbol values statically. Could not resolve ng2-bs3-modal relative to C:/Tem
p/InteractiveInterface/angular-src/src/app/app.module.ts., resolving symbol AppModule in C:/Temp/InteractiveInter
face/angular-src/src/app/app.module.ts, resolving symbol AppModule in C:/Temp/InteractiveInterface/angular-src/sr
c/app/app.module.ts

ERROR in C:/Temp/InteractiveInterface/angular-src/src/polyfills.ts (1,25): Cannot find module 'jquery'.

ERROR in C:/Temp/InteractiveInterface/angular-src/src/app/app.module.ts (23,31): Cannot find module 'ng2-bs3-moda
l'.

ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'jquery' in 'C:\Temp\InteractiveInterface\angular-src\src'
 @ ./src/polyfills.ts 1:0-33
 @ multi ./src/polyfills.ts

ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve 'ng2-bs3-modal' in 'C:\Temp\InteractiveInterface\angular-src\src\app'
 @ ./src/app/app.module.ts 28:0-46
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
```

**Comment by OmarBelguith** [comment]
I reproduced the Angular_CLI of Survey Editor and added a modal and the same problem occurs in this repository
https://github.com/OmarBelguith/IssueSurveyJS

**Comment by tsv2013** [comment]
Thank you. I'll check it.

**Comment by tsv2013** [comment]
It looks like in the v0.97.0 this issue was fixed. It was discussed in this thread -
 https://surveyjs.answerdesk.io/internal/ticket/details/T246.
I've updated your project.json file, delete 'node_modules' folder and reinstall them.
After that modal works fine for me.
I've attached the 'package.json' file.
[package.zip](https://github.com/surveyjs/editor/files/1518043/package.zip)
