### ISSUE TITLE
Delete Page from the context menu

### ISSUE THREAD

**Issue by dmitrykurmanov** [surveyjs/editor#221]
### Are you requesting a feature, reporting a bug or ask a queation?
bug

### What is the current behavior?
if delete page from the context menu it is still selected in the property editor

### What is the expected behavior?
page in property editor will change

**Comment by mkopinsky** [comment]
Related to this - is there a way to rename a page? I see in the schema that it's a variable, but can't find a place in the UI to rename it.

**Comment by dmitrykurmanov** [comment]
sure, please check 
![image](https://user-images.githubusercontent.com/22315929/33477090-65526ee8-d695-11e7-962f-a5608c0b08d4.png) in the
https://surveyjs.io/Editor/Editor/

**Comment by mkopinsky** [comment]
Thanks. I never noticed that context menu before.

**Comment by dmitrykurmanov** [comment]
we've implemented it several days ago

**Comment by mkopinsky** [comment]
Awesome. I just upgraded to 0.97 and there it is!

As I'm implementing this, it seems that every minor limitation I bump into is solved within a couple days. Thanks for all the continued development!

**Comment by dmitrykurmanov** [comment]
@mkopinsky and thanks to you for suggestions and bug reports, it helps us to make the SurveyJS better
