### ISSUE TITLE
choices_Item (item1, item2, item3) is not working in localization for editor page

### ISSUE THREAD

**Issue by Yaowenjie** [surveyjs/editor#222]
### Are you requesting a feature, reporting a bug or ask a queation?

reporting a bug.

### What is the current behavior?

In editor page, no matter what locale you use, the default options (for RadioGroup & CheckBox) value is `item1` `item2` `item3`, which is from the default value of  ***choices_item*** parameter in surveyjs

### What is the expected behavior?

When I use some other languages as locale, like 'zh-cn', 'romanian', etc, the default options value should works as corresponding  ***choices_item*** parameter for corresponding language of surveyjs. For example, if `SurveyEditor.editorLocalization.currentLocale = "zh-cn"`, the default options value should be `选项1` `选项2` `选项3`. 

### How would you reproduce the current behavior (if this is a bug)?

As above.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: [plnkr case](https://plnkr.co/edit/HAjj8KxBahcJNYjPz1in?p=preview)

### Specify your

* editor version: 0.96.3

**Comment by andrewtelnov** [comment]
@Yaowenjie You have to change the default locale for survey as well.
Please use the following code: 
```
SurveyEditor.editorLocalization.currentLocale = "zh-cn";
Survey.surveyLocalization.defaultLocale = "zh-cn";
```
Here is the example:
https://plnkr.co/edit/U9KHKjFBPCxspb75Suvq?p=preview

Thank you,
Andrew

**Comment by Yaowenjie** [comment]
@andrewtelnov Thank you so much! This is exactly what I need. I'll close it.
