### ISSUE TITLE
Question - How to force AfterRenderQuestion ?

### ISSUE THREAD

**Issue by traquall** [surveyjs/editor#223]
### Are you requesting a feature, reporting a bug or ask a queation?

Question

### What is the current behavior?

I add a function to 'onAfterRenderQuestion' and questions are already rendered when I open a survey, so the function doesn't execute before I modify a question

### What is the expected behavior?

I want to force the 'onAfterRenderQuestion' event in order to execute the function when I open a survey.

Thanks,

Traquall

**Comment by andrewtelnov** [comment]
@traquall Does survey.render(); work for you?

Thank you,
Andrew

**Comment by traquall** [comment]
@andrewtelnov yes ! 

Thank you,
Traquall
