### ISSUE TITLE
How to add a third party html componenet, like a different checkbox from https://lokesh-coder.github.io/pretty-checkbox/#basic-checkbox

### ISSUE THREAD

**Issue by tjtaojiang** [surveyjs/editor#232]
### Are you requesting a feature, reporting a bug or ask a queation?
Request a feature. I need to replace the default html componenet, like checkbox with a third party one from https://lokesh-coder.github.io/pretty-checkbox/#basic-checkbox.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by dmitrykurmanov** [comment]
We will create a widget for that. I've created an issue in widgets repo https://github.com/surveyjs/widgets/issues/12

**Comment by tjtaojiang** [comment]
Is there any online doc to show how developers can implement such widget themselves?

**Comment by andrewtelnov** [comment]
@tjtaojiang Sure, here is the code for iCheck: https://github.com/surveyjs/widgets/blob/master/src/icheck.js
and here is the example of using: https://surveyjs.io/Examples/Library/?id=custom-widget-icheck

Thank you,
Andrew

**Comment by tjtaojiang** [comment]
Can't follow it. We are testing to see how easily to customize a html component using surveyjs library.

My goal is very simple.

How do I make all my checkbox in surveyjs to use this:

(https://lokesh-coder.github.io/pretty-checkbox/#basic-checkbox)

"Svg" "Recurring" checkbox style:


<div class="pretty p-svg p-curve">
        <input type="checkbox" />
        <div class="state p-success">
            
            <svg class="svg svg-icon" viewBox="0 0 20 20">
                <path d="M7.629,14.566c0.125,0.125,0.291,0.188,0.456,0.188c0.164,0,0.329-0.062,0.456-0.188l8.219-8.221c0.252-0.252,0.252-0.659,0-0.911c-0.252-0.252-0.659-0.252-0.911,0l-7.764,7.763L4.152,9.267c-0.252-0.251-0.66-0.251-0.911,0c-0.252,0.252-0.252,0.66,0,0.911L7.629,14.566z" style="stroke: white;fill:white;"></path>
            </svg>
            <label>Recurring</label>
        </div>
    </div>

**Comment by tjtaojiang** [comment]
I have a solution for this.  Check the code here.  Pay attention to addCustomWidgetForPrettyCheckbox() and how to use it:

Survey.Survey.cssType = "bootstrap";
Survey.defaultBootstrapCss.navigationButton = "btn btn-green";

var json = {
    questions: [
        {
            type: "checkbox",
            name: "car",
            title: "What car are you driving?",
            isRequired: true,
            colCount: 4,
            choices: [
                "None",
                "Ford",
                "Vauxhall",
                "Volkswagen",
                "Nissan",
                "Audi",
                "Mercedes-Benz",
                "BMW",
                "Peugeot",
                "Toyota",
                "Citroen"
            ]
        }
    ]
};

window.survey = new Survey.Model(json);

survey.onComplete.add(function (result) {
        document.querySelector('#surveyResult').innerHTML = "result: " + JSON.stringify(result.data);
    });

function onAngularComponentInit() {
    addCustomWidgetForPrettyCheckbox();
    Survey.SurveyNG.render("surveyElement", {model: survey});
}

function addCustomWidgetForPrettyCheckbox() {
    var prettyCheckboxwidget = {
        name: 'checkbox',
        isFit: function (question) {
            return ['checkbox'].indexOf(question.getType()) > -1;
        },
        isDefaultRender: false,
        afterRender: function (question, el) {

            var outputHTML = '';
            var allCheckboxes = question.choices;

            var counter = 0;
            allCheckboxes.forEach(function (row, index, rows) {
                if (counter === 0) {
                    outputHTML = outputHTML +
                        '<div>' +
                        '<div class="pretty p-svg p-curve">' +
                        '<input type="checkbox" name=' + row.value + '""/>' +
                        '<div class="state p-success">' +
                        '' +
                        '<svg class="svg svg-icon" viewBox="0 0 20 20">' +
                        '<path d="M7.629,14.566c0.125,0.125,0.291,0.188,0.456,0.188c0.164,0,0.329-0.062,0.456-0.188l8.219-8.221c0.252-0.252,0.252-0.659,0-0.911c-0.252-0.252-0.659-0.252-0.911,0l-7.764,7.763L4.152,9.267c-0.252-0.251-0.66-0.251-0.911,0c-0.252,0.252-0.252,0.66,0,0.911L7.629,14.566z" style="stroke: white;fill:white;">' +
                        '</path>' +
                        '</svg>' +
                        '<label>' + row.text + '</label>' +
                        '</div>' +
                        '</div>';
                } else {
                    outputHTML = outputHTML +
                        '<div class="pretty p-svg p-curve">' +
                        '<input type="checkbox" name=' + row.value + '""/>' +
                        '<div class="state p-success">' +
                        '' +
                        '<svg class="svg svg-icon" viewBox="0 0 20 20">' +
                        '<path d="M7.629,14.566c0.125,0.125,0.291,0.188,0.456,0.188c0.164,0,0.329-0.062,0.456-0.188l8.219-8.221c0.252-0.252,0.252-0.659,0-0.911c-0.252-0.252-0.659-0.252-0.911,0l-7.764,7.763L4.152,9.267c-0.252-0.251-0.66-0.251-0.911,0c-0.252,0.252-0.252,0.66,0,0.911L7.629,14.566z" style="stroke: white;fill:white;">' +
                        '</path>' +
                        '</svg>' +
                        '<label>' + row.text + '</label>' +
                        '</div>' +
                        '</div>';
                }

                if ((counter === (question.colCount - 1)) || (index === (allCheckboxes.length - 1))) {
                    if ((question.colCount === 1) || (allCheckboxes.length === 1)) {
                        outputHTML = outputHTML + '</div>';
                    } else {
                        outputHTML = outputHTML + '</div>' + '<div class="empty-space-div"></div>';
                    }
                    counter = 0;
                } else {
                    counter++;
                }
            });
            el.innerHTML = outputHTML;
        }
    };

    Survey.CustomWidgetCollection.Instance.addCustomWidget(prettyCheckboxwidget);
}

var HelloApp = ng.core.Component({
        selector: 'ng-app',
        template: '<div id="surveyContainer" class="survey-container contentcontainer codecontainer"><div id="surveyElement"></div></div> '
    })
    .Class({
        constructor: function () {
        },
        ngOnInit: function () {
            onAngularComponentInit();
        }
    });
document.addEventListener('DOMContentLoaded', function () {
    ng.platformBrowserDynamic.bootstrap(HelloApp);
});

**Comment by tsv2013** [comment]
@tjtaojiang I've just finished with pretty-checkbox custom widget implementation. You can find it in this commit: https://github.com/surveyjs/widgets/commit/4c0c5d9ebd91de315e708301e7e95c065182f9d1
It will be available in the nearest update (0.98.4) or you can build the https://github.com/surveyjs/widgets repo.
We can discuss additional options to fit your scenario.

**Comment by tjtaojiang** [comment]
Thanks.  What do you think my approach?

**Comment by tjtaojiang** [comment]
@tsv2013, I can't make your version of the widget to work for my case. I am not sure what I miss.

I attached a simplified version of my code, "suyveyjs-form.html" and "surveyjs-form.js" below, to show how it works for my case.

Please advise.

**Comment by tjtaojiang** [comment]
@tsv2013, "suyveyjs-form.html":
--------------------------------------------------------------------------

<!DOCTYPE html>
<html>

<head>
    <link href="https://cdn.datatables.net/v/bs-3.3.7/dt-1.10.15/fc-3.2.2/fh-3.1.2/r-2.1.1/sc-1.4.2/se-1.2.2/datatables.min.css" rel="stylesheet" type="text/css"/>
    <link href="https://cdn.jsdelivr.net/npm/pretty-checkbox@3.0/dist/pretty-checkbox.min.css" rel="stylesheet">

    <script src="https://surveyjs.azureedge.net/0.97.0/survey.angular.js" type="text/javascript"></script>

    <script src="https://npmcdn.com/zone.js@0.8.17/dist/zone.js"></script>
    <script src="https://npmcdn.com/core-js/client/shim.min.js"></script>
    <script src="https://npmcdn.com/rxjs@5.0.0-beta.6/bundles/Rx.umd.js"></script>
    <script src="https://npmcdn.com/@angular/core@2.0.0-rc.5/bundles/core.umd.js"></script>
    <script src="https://npmcdn.com/@angular/common@2.0.0-rc.5/bundles/common.umd.js"></script>
    <script src="https://npmcdn.com/@angular/compiler@2.0.0-rc.5/bundles/compiler.umd.js"></script>
    <script src="https://npmcdn.com/@angular/platform-browser@2.0.0-rc.5/bundles/platform-browser.umd.js"></script>
    <script src="https://npmcdn.com/@angular/platform-browser-dynamic@2.0.0-rc.5/bundles/platform-browser-dynamic.umd.js"></script>

    <script src="surveyjs-forms.js" type="text/javascript"></script>

</head>

<body>

<ng-app></ng-app>
<div id="surveyResult"></div>

</body>
</html>

**Comment by tjtaojiang** [comment]
@tsv2013, I can't make your version of the widget to work for my case. I am not sure what I miss.

I attached a simplified version of my code, "suyveyjs-form.html" and "surveyjs-form.js" below, to show how it works for my case.

Please advise.
[surveyjs-widget.zip](https://github.com/surveyjs/editor/files/1568909/surveyjs-widget.zip)

**Comment by tsv2013** [comment]
Lets continue discussion in this thread - https://github.com/surveyjs/widgets/issues/12 due to it related to the custom widgets.
