### ISSUE TITLE
"Locked edits" mode

### ISSUE THREAD

**Issue by mkopinsky** [surveyjs/editor#234]
### Are you requesting a feature, reporting a bug or ask a queation?

Feature

### What is the current behavior?

When editing a survey, all fields are editable. If there are already some survey responses, or there are things in the application that expect the returned data to look a specific way, that has potential to disrupt those. For example, in our research application, researchers can configure logic like "If response to `question4` was `Yes`, then mark the participant as Ineligible for the study.

### What is the desired behavior?

Once that logic is set up, we would want to allow researchers to edit only things that don't change how the response data would come back. For example, they should be able to add or edit a question title but not the question name. Same for choices in a dropdown, and so on.

**Comment by andrewtelnov** [comment]
@mkopinsky Are you looking for this code?
```
Survey.JsonObject.metaData.findProperty("questionbase", "name").readOnly = true;
Survey.JsonObject.metaData.findProperty("selectbase", "choices").visible = false;
Survey.JsonObject.metaData.findProperty("selectbase", "choicesByUrl").visible = false;
```
Here is the example: https://plnkr.co/edit/oFrhiNdzobQJ8G0Yykxh?p=info

Thank you,
Andrew

**Comment by mkopinsky** [comment]
Thanks! I will give that a try.

**Comment by andrewtelnov** [comment]
@mkopinsky Forgot to mention the [editor.onCanShowProperty event](https://surveyjs.io/Documentation/Editor/?id=surveyeditor#onCanShowProperty)
It can work better for your task.

Thank you,
Andrew

**Comment by buddhika23** [comment]
Is there a way that I can lock a predefined question in the editor (i think i can inject this particular question when the designer get initialized) ? for an example, each survey i want to have predefined question like title and i don't want other users to change or remove this particular question in the editor (i can prevent it removing using "editor.onElementDeleting" event, but need a way to prevent from editing it.

Thank you,
Buddhika

**Comment by andrewtelnov** [comment]
@buddhika23 It is a good scenario. Do you want to show the properties grid on the right (you may hide it), so the user will be able to modify questions in Editor Window only?
In this case you will have to disable the "Editor" button only.

As I told the scenrio makes sense to me. Unfortunately we do not have API to implement it yet. We must add it. It should not be hard to do though. 

Thank you,
Andrew

**Comment by buddhika23** [comment]
@andrewtelnov Thank you very much Andrew, for the moment I will go with edit button disable option, yeah I can hide properties of the properties grid or  hide it completely, at the moment I am not sure how I can achieve this, but I think there must be an example around.

Thank you,
Buddhika

**Comment by andrewtelnov** [comment]
@buddhika23  You may set set showPropertyGrid to false.
```
var editorOptions = { showPropertyGrid: false};
var editor = new SurveyEditor.SurveyEditor("editorElement", editorOptions);
```
You will be able to disable these operations from the next minor update. We will release it on the next week: https://github.com/surveyjs/editor/issues/249

Thank you,
Andrew

**Comment by buddhika23** [comment]
Thank you very much :+1: @andrewtelnov

**Comment by suhailamir** [comment]
@buddhika23 how you were able to disable edit button?
