### ISSUE TITLE
Multiple text with number fields: validation fails

### ISSUE THREAD

**Issue by sco2tbold** [surveyjs/editor#239]
I've got a simple "Multiple text" field with 2 items; both are of type "Numeric". When I test this config and enter numbers, I get a validation error "Should be numeric".

![image](https://user-images.githubusercontent.com/7213039/33945684-fed3ab16-e01f-11e7-8670-478407068523.png)

Here's the config. 

`{
 "pages": [
  {
   "elements": [
    {
     "type": "multipletext",
     "isRequired": true,
     "items": [
      {
       "name": "count",
       "inputType": "number",
       "title": "Number involved"
      },
      {
       "name": "total",
       "inputType": "number",
       "title": "Total number found"
      }
     ],
     "name": "sugery_pathology_number_positive_lymph_nodes",
     "title": "Number of positive lymph nodes",
     "validators": [
      {
       "type": "numeric",
       "text": "asdf",
       "maxValue": 100
      }
     ]
    }
   ],
   "name": "page1"
  }
 ]
}`

**Comment by andrewtelnov** [comment]
@sco2tbold You add validator to the multiple text question. It is an array of text question and it can't be numeric.
Here is the corrected JSON:
```
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "multipletext",
     "name": "sugery_pathology_number_positive_lymph_nodes",
     "title": "Number of positive lymph nodes",
     "isRequired": true,
     "items": [
      {
       "name": "count",
       "inputType": "number",
       "title": "Number involved",
       "validators": [
        {
         "type": "numeric",
         "text": "asdf",
         "maxValue": 100
        }
       ]
      },
      {
       "name": "total",
       "inputType": "number",
       "title": "Total number found",
       "validators": [
        {
         "type": "numeric",
         "text": "asdf",
         "maxValue": 100
        }
       ]
      }
     ]
    }
   ]
  }
 ]
}
```

Thank you,
Andrew

**Comment by sco2tbold** [comment]
Thanks. That basically works. 

But I expected to have a "minValue" property, as the maxValue. But it get's stripped out after editing the JSON on surveyjs.io.

**Comment by sco2tbold** [comment]
In the UI you've tho the "minValue" field

![image](https://user-images.githubusercontent.com/7213039/34152955-9a8f35fe-e4b0-11e7-8936-616e60c83851.png)

**Comment by andrewtelnov** [comment]
@sco2tbold We could not reproduce the issue :-( Probably specific steps are required. Do you get this issue all the time?
I did the following on https://surveyjs.io/Editor/Editor/:
1) Drop a multiple text item
2) Create a numeric validator and set maxValue to 222 and minValue to 11
3) go to json editor and change 11 to 111
4) go to editor and look at minValue, it is 111

Thank you,
Andrew

**Comment by sco2tbold** [comment]
Thanks Andrew. Found the problem after re-testing it. As soon as I set the minValue to 0 it get stripped out.  But we need a min value of 0.

**Comment by andrewtelnov** [comment]
@sco2tbold The issue has been fixed.

Thank you,
Andrew

**Comment by sco2tbold** [comment]
Awesome! Thanks!
