### ISSUE TITLE
Bug - Translation goes wrong with 0 or false value

### ISSUE THREAD

**Issue by traquall** [surveyjs/editor#240]
### Are you requesting a feature, reporting a bug or ask a question?

Reporting a bug

### What is the current behavior?

I have a boolean property showDetails with 2 choices : true and false

`
Survey.JsonObject.metaData.addProperty("questionbase", {name: "showDetails", choices: [true, false]});
`

I added translation for the true and false like this:  
`
SurveyEditor.defaultStrings.pv["true"] = "Oui";
SurveyEditor.defaultStrings.pv["false"] = "Non";
`

But if the property is false, it isn't translated in the property toolbar.
same behavior with 0 instead of false.

### What is the expected behavior?

false is translated to "Non"

### How would you reproduce the current behavior (if this is a bug)?

Add a property with a false or 0 choice and add a defaultString translation.
Then put the property to false or 0, click on another question and click on the first question.

![capture d ecran 2017-12-14 a 09 43 41](https://user-images.githubusercontent.com/11782554/33983430-73a91f86-e0b4-11e7-8510-f8ae2795ab57.png)
![capture d ecran 2017-12-14 a 09 43 51](https://user-images.githubusercontent.com/11782554/33983431-73beb56c-e0b4-11e7-84e5-8e34dc123dcf.png)

**Comment by andrewtelnov** [comment]
@traquall I have fixed the issue.

Thank you,
Andrew
