### ISSUE TITLE
Manual "Other" option

### ISSUE THREAD

**Issue by sco2tbold** [surveyjs/editor#242]
We need a single selection list with a manual "Other" option. I set up the question and added a item with the text "other|Other". When I choose this other item the validation fails with the hint "Please enter the other value". 

Expected behaviour: this "Other" item is treated as any other option. 

I'd expect this behaviour only if I check the "Has other item" property of the question (which is not checked in my example).

Please see the following screenshots:
![image](https://user-images.githubusercontent.com/7213039/34147760-1a85ffe8-e49f-11e7-922d-1850b1106ec8.png)

**Comment by andrewtelnov** [comment]
@sco2tbold Sounds like a bug to me.
SurveyJS beleives that 'other' has been choose and end-user have to enter the data into the other textbox.
I will fix it today.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@sco2tbold It has been fixed, unit test has been added.

Thank you,
Andrew

**Comment by sco2tbold** [comment]
Awesome service! Thanks!
