### ISSUE TITLE
How to show custom error message  in question .

### ISSUE THREAD

**Issue by ak34504** [surveyjs/editor#245]
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by andrewtelnov** [comment]
@ak34504 Have you seen validation examples: https://surveyjs.io/Examples/Library/?id=validators-event?

PS: Please use [this repo](https://github.com/surveyjs/surveyjs) to ask questions about the library.

Thank you,
Andrew
