### ISSUE TITLE
Need the model for the survey

### ISSUE THREAD

**Issue by healkar01** [surveyjs/editor#248]
I have a question.

We have a current survey system and we need to convert OUR surveys to your survey format.  Do you have a model that would fully describe your survey?  I've looked through the code a bit and can't seem to find it.

Thank you,

Karen Healey

**Comment by healkar01** [comment]
If you don't have that, can you provide me with a sample JSON that covers every type of question and attribute you might have?  I can derive the class from that.

**Comment by andrewtelnov** [comment]
@healkar01 There are two ways of doing this you may go to the documentation page: https://surveyjs.io/Documentation/Library/?id=surveymodel and in dropdown filter change the value from "Show All" to "Show Properties".
You may go through all objects then "Page", "Panel" and so on. They are on the left.

Another way is to go to the editor and start to create the survey you need: https://surveyjs.io/Editor/Editor/. You may add new pages, panels, questions, change their properties and then go to the "JSON Editor" tab. You will see the survey declaration in JSON. 

Please let me know if it helps.

Thank you,
Andrew

**Comment by healkar01** [comment]
Thank you... I'm sure that between those two options, I'll be able to come up with what I need.  I really only need to match up your attributes with the ones in our survey JSON, which will simplify things.

Karen Healey
