### ISSUE TITLE
Move 'hasOther' checkbox from General Tab to Choices Tab

### ISSUE THREAD

**Issue by mkopinsky** [surveyjs/editor#250]
### Are you requesting a feature, reporting a bug or ask a question?

Feature

### What is the current behavior?

The 'hasOther' checkbox ("Has other item" in the default strings) is on the General Tab. My users found it a bit confusing, and weren't sure what the checkbox was.

### What is the expected behavior?
I renamed it to "Add option for 'Other'", but I think it would be even more intuitive if I could move it to the bottom of the choices tab. I can't figure out how to do that though.
### Specify your

* browser: Chrome
* editor version: 0.97.0

**Comment by andrewtelnov** [comment]
@mkopinsky Unforrtunately, it will be hard to implement this on your side.
However, I would totally agree that it makes more sence to have it in the choices property editor.
We will think about it.

**Comment by mkopinsky** [comment]
Thanks for the quick response. I'm glad I asked rather than bashing my head against the methods in surveyeditor.js. :-)

**Comment by mkopinsky** [comment]
This looks great how you guys implemented this. Thanks!!
