### ISSUE TITLE
Improve Expression Editor

### ISSUE THREAD

**Issue by dmitrykurmanov** [surveyjs/editor#251]
* add available questions list
* add available signs list
* add validatin of the expression with showing an error message
* show `row.columnName` (for columns) and  `panel.questionName` (for dynamic panels)

**Comment by dmitrykurmanov** [comment]
form the #258 

> What is the current behavior?
> Normal users are more familiar with GREATER, EQUAL TO GREATER, SMALLER... rather than >, >=, <..., so let them manually type those math symbol are not very user-friendly.
> 
> What is the expected behavior?
> A way that allow developers to inject a simple GUI assistant into expression/visibleIf editors. Such as a dropdown or checkbox...
> I was trying to insert some elements and inject changes to those editors but no luck. Do we allow that extend? Please let me know what you think.

**Comment by mkopinsky** [comment]
I want to give this a huge +1. We're integrating SurveyJS to replace a certain unnamed commercial survey tool, and while there are GUI differences, this is the one area where I had to admit to my tester/product person that "when you get it for free, unfortunately in certain areas it might not be as good." Which means on the flip side that building out this visual expression builder really makes SurveyJS competitive with those commercial solutions.

I will ask that tester/product person if she has specific things she'd want from this builder or any other design feedback.

**Comment by andrewtelnov** [comment]
@mkopinsky We worked on this functionality for some time ago. We did not like the result and rollback our changes. You may see commits in this issue.
We want to show errors/warnings if there are some and question list to insert them into the expression.
In fact, our SurveyJS Editor is a commercial product. We decided to go Open Source to get the attention of the community faster.
There are 3 professional developers, inclulding me, who works on this project full time. We have some additional resources.

Do you have some specific GUI in minde?

Thank you,
Andrew

**Comment by tsv2013** [comment]
From the https://github.com/surveyjs/surveyjs/issues/887:

> What is the expected behavior?
> If there was functionality in the visibleIf parameter to determine if question9 is visible (e.g. "{question9} isVisible"), then the rule would become a lot simpler and more robust to future changes in question definitions.
> 
> Provide the test code and the tested page URL (if applicable)
> Here is the JSON for an example. What I'm looking to do is only display one question at a time. If you answer "Yes" to questions 1-4 then change the answer to question1 to "No", you'll see that question5 is still visible. It would be nice if there was a way to make it only visible if question4 is visible and equals "Yes" without having to reference all the other questions. The conditions don't get too long or horrible here but imagine extending it by 20 questions and it gets to be a pain to manage.

**Comment by tsv2013** [comment]
From the https://github.com/surveyjs/surveyjs/issues/887:

> What is the current behavior?
> Questions require very long visibleIf queries where there is a tall tree of questions.
> 
> For example, if question2 is visible depending on the answer to question1 and question3 is visible depending on the answer to question2 etc.... See example survey JSON below. In this case, the visibleIf query for question10 has to be exactly the same as question9, with the addition of the clause for question9's value. If this isn't done, changing the value of question1 will turn question2 invisible but not any subsequent questions.
> 
> What is the expected behavior?
> If there was functionality in the visibleIf parameter to determine if question9 is visible (e.g. "{question9} isVisible"), then the rule would become a lot simpler and more robust to future changes in question definitions.
> 
> Provide the test code and the tested page URL (if applicable)
> Here is the JSON for an example. What I'm looking to do is only display one question at a time. If you answer "Yes" to questions 1-4 then change the answer to question1 to "No", you'll see that question5 is still visible. It would be nice if there was a way to make it only visible if question4 is visible and equals "Yes" without having to reference all the other questions. The conditions don't get too long or horrible here but imagine extending it by 20 questions and it gets to be a pain to manage.

**Comment by tsv2013** [comment]
We've implemented autocomplete feature for visibleIf, enableIf and expression in the SurveyJS Builder (Editor) via Ace editor + ext language tools. You can try this feature in the [Online Survey Builder](https://surveyjs.io/Survey/Builder/) on our site. You feedback is hightly appreciated.
