### ISSUE TITLE
Modify PropertyGrid List

### ISSUE THREAD

**Issue by puntnomads** [surveyjs/editor#252]
I will like to display the PropertyGrid but only include the correctAnswer and remove all other options. I would also like to get rid of the button "Edit selected object" and the dropdown next to it.

**Comment by andrewtelnov** [comment]
@puntnomads Here is the example: https://plnkr.co/edit/x1yTUx?p=preview

Thank you,
Andrew

**Comment by puntnomads** [comment]
@andrewtelnov Thank you very much. You have made my day!

**Comment by puntnomads** [comment]
I have tried to integrate that example into my react app. My editor object doesn't have the onElementAllowOperations method. I have used the surveyjs_react_quickstart to integrate Survey JS into my app. That example also doesn't have onElementAllowOperations method.

**Comment by puntnomads** [comment]
@andrewtelnov In your example the functionality for editing questions completely broke. I got around this by using css to hide all elements in the list. I have also hidden the button and dropdown. I have used onSetPropertyEditorOptions to reveal the correctAnswer element.

**Comment by andrewtelnov** [comment]
@puntnomads Could you please describe what does not work?
I have disabled everything in the example, including drag&drop. You may see it in the code. What functionality do you want to keep?

Thank you,
Andrew
