### ISSUE TITLE
ckeditor no longer working

### ISSUE THREAD

**Issue by mkopinsky** [surveyjs/editor#256]
### Are you requesting a feature, reporting a bug or ask a question?

Bug

### What is the current/expected behavior?

On ckeditor example page (https://surveyjs.io/Examples/Editor/?id=ckeditorpropertyeditor), HTML editor tab should use ckeditor. If I edit via plunkr (https://plnkr.co/edit/K9wVjuZps7JAjdPnt1At?p=preview) and change the version of included surveyeditor.js to 1.0.1 it works; on 1.0.2 it's broken.

**Comment by andrewtelnov** [comment]
@mkopinsky Yes, thank you- Incorrect template has been used. I  have fixed it.

Thank you,
Andrew

**Comment by mkopinsky** [comment]
Awesome, thanks. Can you release to npm?

**Comment by andrewtelnov** [comment]
@tsv2013 @dmitrykurmanov Let's make an update on Monday.

Thank you,
Andrew
