### ISSUE TITLE
Editor | GUI assistant for building expression/visibleIf logic

### ISSUE THREAD

**Issue by tucq88** [surveyjs/editor#258]
### Are you requesting a feature, reporting a bug or ask a question?
Feature

### What is the current behavior?
Normal users are more familiar with `GREATER, EQUAL TO GREATER, SMALLER...` rather than `>, >=, <...`, so let them manually type those math symbol are not very user-friendly.

### What is the expected behavior?
A way that allow developers to inject a simple GUI assistant into expression/visibleIf editors. Such as a `dropdown` or `checkbox`... 
I was trying to insert some elements and inject changes to those editors but no luck. Do we allow that extend? Please let me know what you think.

**Comment by dmitrykurmanov** [comment]
Thank you for the feature request. We already have it in our tast list. We will update this thread after it will be implemented.

**Comment by tsv2013** [comment]
We've implemented autocomplete feature for visibleIf, enableIf and expression in the SurveyJS Builder (Editor) via Ace editor + ext language tools. You can try this feature in the [Online Survey Builder](https://surveyjs.io/Survey/Builder/) on our site. You feedback is hightly appreciated.
