### ISSUE TITLE
Need to customize style layout for custom question properties

### ISSUE THREAD

**Issue by res63661** [surveyjs/editor#261]
### Are you requesting a feature, reporting a bug or ask a question?
I need to be able to categorize custom question properties and be able to set those custom properties apart in the property editor list.  How do I dynamically style each individual row in the properties list?

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: ie 11+, chrome, ff, safari
* editor version:

**Comment by andrewtelnov** [comment]
@res63661 There is no functionality that would allow you to customize a property styles or sort order. I think your scenario is a good one.
I have a question, As I understand, you need two additional events:
1) onPropertiesCustomSort event - it would allow you to make a custom sorting. Right now, they are sort by names.
2) onPropertyRender event - it will pass options.property object and options.htmlElement. It would allow you to apply any style/css to the htmlElement, based on options.property (options.property.name for example).
Will it work for you?

Thank you,
Andrew

**Comment by res63661** [comment]
Andrew - thanks for getting right back.  I had to try out a few things to get you a good answer so you don't waste your time ;) - hence the delay responding.  I was able to get what I need working using react to dynamically add the custom properties  and some jquery magic to re-arrange the UI so now I have the subcategories.  I am getting a few issues with the json survey saving  correctly, though.  Are those known issues or is it my code?  The sort is not critical at this time either since I can always apply a sort on the nodes in jQuery when I move them.
To answer you, #2 would likely be the "right" way to do this so if you want to implement that way go for it.

Very best, res63661

**Comment by andrewtelnov** [comment]
@res63661 [on custom property sort](https://github.com/surveyjs/editor/issues/265)  is implemented. 

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@res63661 and [editor.onPropertyAfterRender event](https://github.com/surveyjs/editor/issues/266). It will be available from the next minor release.

Thank you,
Andrew

**Comment by res63661** [comment]
Fantastic!  Thanks Andrew!  Anything special I need to know to integrate it into the react quickstart?  Thanks!
