### ISSUE TITLE
Hiding the title property of a matrixdropdown column

### ISSUE THREAD

**Issue by maria-negrea** [surveyjs/editor#262]
### Are you requesting a feature, reporting a bug or ask a question?

Bug

### What is the current behavior?

After setting it's visibility to false, the title property still shows up in the Columns tab of a matrixdropdown.

![title](https://user-images.githubusercontent.com/6886765/35865071-37965658-0b5c-11e8-89b0-874cdd0e4fe2.JPG)

### What is the expected behavior?

I would like to be able to hide the title property of a matrixdropdown column. It may confuse the end users(the non-technical category) that may not understand the difference between "Name" and "Title".

### How would you reproduce the current behavior (if this is a bug)?

Setting the visibility of the title property of the matrixdropdown column to false.

#### Provide the test code and the tested page URL (if applicable)

Test code

Survey.JsonObject.metaData.findProperty("matrixdropdowncolumn", "title").visible = false;

### Specify your

* browser: Google Chrome Version 63.0.3239.132
* editor version: 1.0.6

**Comment by andrewtelnov** [comment]
@maria-negrea How urgent do you need this?
I have looked at code. The grid columns in the Editor for matrix columns are hard coded.
It will take some time to do implement something similar as for choices property, or create a generic solution.

Thank you,
Andrew

**Comment by maria-negrea** [comment]
For the moment, it is not urgent, but it would help me a lot if it will be implemented in the future. Thank you!

**Comment by BabuBahir** [comment]
any progress on this ???? I still have my title displayed even if the column is set visible=false :(
