### ISSUE TITLE
The timer of a survey doesn't start when the firstPageIsStarted is set to false

### ISSUE THREAD

**Issue by maria-negrea** [surveyjs/editor#264]
### Are you requesting a feature, reporting a bug or ask a question?

Feature

### What is the current behavior?

The timer of a survey doesn't start when the firstPageIsStarted is set to false.

### What is the expected behavior?

On display mode/test survey mode, when the maxTimeToFinish property is set, I would like the timer to start automatically if the firstPageIsStarted property is set to false.

### How would you reproduce the current behavior (if this is a bug)?

Set firstPageIsStarted to false, set maxTimeToFinish and run the survey in display mode/test survey mode from the builder.

* browser: Google Chrome Version 63.0.3239.132
* editor version: 1.0.6

**Comment by andrewtelnov** [comment]
@maria-negrea Have you call `survey.startTimer();`?

Thank you,
Andrew

**Comment by maria-negrea** [comment]
After setting survey.showTimerPanel="top"; or survey.showTimerPanel="bottom"; and then calling survey.startTimer();, it works. Thank you!
