### ISSUE TITLE
React Editor example with barrating custom widget

### ISSUE THREAD

**Issue by chambleton** [surveyjs/editor#270]
Hi - i'm posting this example for React on how to add a custom widget (barrating) to both the Editor and the Survey. This wasn't clear from the docs but might save someone else several hours of googling and trial and error. Thanks for making a great library! 

https://stackblitz.com/edit/react-barrating-widget

**Comment by andrewtelnov** [comment]
@chambleton Thank you for sharing this to us and the community!

Andrew

**Comment by tsv2013** [comment]
We've added corresponding sample in the react boilerplate repo - https://github.com/surveyjs/surveyjs_react_quickstart via the https://github.com/surveyjs/surveyjs_react_quickstart/commit/baa5d009e42974974f1557488c92b211fcdefc8a commit
Thanks again
