### ISSUE TITLE
Issue when adding more than 3 question choices (responses)

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/editor#276]
Cloned from the https://github.com/surveyjs/surveyjs/issues/947

When filling out the possible answers to a survey question, when I click 'add new', the Value field doesn't update. So the 1st three Value fields will have item1, item2, item3. I'll add another line, and the Value field will be blank, when it should say item4. 

See attachment for screenshot. Thank you!
![survey value field issue](https://user-images.githubusercontent.com/20865786/36482307-de80c810-16e0-11e8-83f0-88287e7ff66a.jpg)

**Comment by tsv2013** [comment]
@healkar01 Thank you for the suggestion. We've added it in our TODO list.

**Comment by dmitrykurmanov** [comment]
We've implemented this siggestion, it will be available in the nearest update.

**Comment by healkar01** [comment]
@dmitrykurmanov, thank you!
