### ISSUE TITLE
It's hard to understand how to add your first question

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/editor#277]
Add some interaction on hover to toolbox, probably tooltips or small pics

**Comment by mkopinsky** [comment]
+1. In my SurveyJS editor integration, I added the following line to make this clearer to my users:

`SurveyEditor.defaultStrings.survey.dropQuestion = "Please drop a question here from the toolbox on the left.";`

As a side note re usability, when I was developing this, I instinctually was dragging questions from the toolbox into the survey. When some other people on my team were testing, they instinctually were clicking on the toolbox questions to add them, and some were confused then about how to change the order of questions. I wonder if a CSS `cursor: grab` would help people with that.

**Comment by andrewtelnov** [comment]
@mkopinsky Thank you very much for sharing this to us. 
Changing cursor to grab is a good idea as well.
If you have done any other improvements or some other ideas, We would love to hear them. We are going to work on Editor usability.


Thank you,
Andrew

**Comment by mkopinsky** [comment]
I'm happy to share the tweaks we made. See https://gist.github.com/mkopinsky/3424d56b96ce751b3d67230f9e5ae8a9 . Some of those are for usability, some are to match the context of our PHP app and/or schema.

**Comment by dmitrykurmanov** [comment]
work for the issue: e6b947ba1e41078d3c95c308d5f4404243054616 282e6bf30eb4640067c003a60d52ed1777bad64b f2aa704d2d7bc0ed7d551d6c47d92efb6bf8b844 15626068f64f4d44b651bf8c53110eb1c352ac2f 805938e6bcddfb2268d90d7ffe0cf396bd8f1e94 ad6ad02c74980fc103f2b5aefe4e1fd65c576ccf 4be3eb26a02c61b859704f6fa2a8815f7d43468c
