### ISSUE TITLE
Add context actions to the selected question on hover

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/editor#279]
We should not force user to press settings
Delete - by the keyboard
Edit title/item/othertext - inplace

**Comment by mkopinsky** [comment]
Ooh, that would be cool if you could edit question titles etc in-place without going into the modal. +1.

As a related note, even if inline editing isn't implemented, I wish there were a way to see the options in a dropdown without either opening the modal or going to Test Survey.

**Comment by tsv2013** [comment]
@mkopinsky We've implemented basic inline editing functionality for titles and choices including: adding, deleting, reordering and text editing. It will be available in the nearest update.

**Comment by tsv2013** [comment]
We've desided to implement a "toolbar" for each question with the context actions currently placed in the question context menu. We'll update this thread when prototype will be implemented.
