### ISSUE TITLE
Add options to show/hide tabs: JSON Editor, Test Survey, Embeded Survey

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/editor#28]
Additionally make Embeded Survey turned off by default.

**Comment by andrewtelnov** [comment]
Implemented

**Comment by vimalavinisha** [comment]
Hi,
      I  installed serveyjs-editor module and then try to disable TestSurveyTab using the below options
 let options = {
        showTestSurveyTab:false
      };
      this.SJEditor = new SurveyEditor.SurveyEditor('editor',options);

But It does not work..Still it showing the testSurveyTab in the editor..While i check your committ, it had done before 6 days. but npm is published 2 weeks ago..Can you publish the recent code in the NPM

**Comment by andrewtelnov** [comment]
@vimalavinisha The new version is in npm.

Thank you,
Andrew
