### ISSUE TITLE
Introduce "simple" editing tools for question - edit title, and items without names

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/editor#280]

**Comment by mkopinsky** [comment]
I showed my team the inline editing stuff during our review meeting today, and they were really impressed. Even though we are still non-commercial, I believe my boss will be purchasing a license within the next few weeks.

Thanks as always for your great work (and product)!

**Comment by andrewtelnov** [comment]
@mkopinsky Thank you for kind words!
We are going to work further on inline editing. We will release these changes every week. We are not sure about some of our current decisions and your feedback is really appreciated.

Thank you,
Andrew
