### ISSUE TITLE
Hidden attributes 

### ISSUE THREAD

**Issue by thawkins** [surveyjs/editor#286]
### Are you requesting a feature, reporting a bug or ask a question?
Question and feature request if not supported. 

### What is the current behavior?
Unknown

### What is the expected behavior?
we would like to add tbe ability to add and set hidden attributes on each question, for example being able to set a weighting factor on each question to be used in analyzing the results. 

If there is not a way to add a bag of properties that can be set in tbe editor,  what would be the potential for adding it?

We would consider developing this if we felt it could be contributed back and maintained in future versions. 

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by andrewtelnov** [comment]
@thawkins You can add/remove any property to any SurveyJS object. Here is [the example](https://surveyjs.io/Examples/Builder/?id=addproperties)

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
I guess the issue has been solved and I am closing it.

Thank you,
Andrew
