### ISSUE TITLE
Survey builder remove renderAs attribute

### ISSUE THREAD

**Issue by xiuzhen1103** [surveyjs/editor#287]
### Are you requesting a feature, reporting a bug or ask a question?

ask a question

### What is the current behavior?

I have type: "dropdown" and "renderAs": "imagepicker" in survey builder, when I switch it to Test Survey tab then come back to survey editor, "renderAs": "imagepicker" have been removed in JSON Editor. 

### What is the expected behavior?
"renderAs": "imagepicker" should stay in survey builder

### How would you reproduce the current behavior (if this is a bug)?
//please copy following JSON into survey editor
```

{
 pages: [
  {
   name: "page1",
   elements: [
    {
     type: "checkbox",
     name: "question1",
     choices: [
      "item1",
      "item2",
      "item3"
     ]
    },
    {
     type: "radiogroup",
     name: "question2",
     choices: [
      "item1",
      "item2",
      "item3"
     ]
    },
    {
     type: "dropdown",
     name: "question3",
     "renderAs": "imagepicker",
     choices: [
      "item1",
      "item2",
      "item3"
     ]
    }
   ]
  }
 ]
}
```
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
https://surveyjs.io/Survey/Builder/

your_code_here
Please copy above code into survey builder

```

**Comment by dmitrykurmanov** [comment]
Hello! Questions has no `renderAs` property by default, please check the [documentation](https://surveyjs.io/Documentation/Library/?id=QuestionBase).

In case of you want to use imagepicker widget it works with `type` property and our [custom widgets](https://github.com/surveyjs/widgets), the json: 
```
    {
     "type": "imagepicker",
     "name": "question1"
    },
```
the example:  https://surveyjs.io/Examples/Builder/?id=customwidgets

In case of  you need to your own custom property  "renderAs", you should register it in the Survey or (optionally) in the Editor:

```
Survey
    .JsonObject
    .metaData
    .addProperty("questionbase", {
        name: "renderAs",
        default: ""
    });

SurveyEditor
    .SurveyQuestionEditorDefinition
    .definition["questionbase"]
    .properties = [
      "name",
      "title",
      {
        name: "renderAs",
        title: "Render As"
      }
    ];
```

If I don't understand you correctly, please describe your use case.

**Comment by xiuzhen1103** [comment]
Thanks for replying, where should I register it in editor? where should I replace following code? I copy it into editor and complain Json is not valid. 

 SurveyEditor
    .SurveyQuestionEditorDefinition
    .definition["questionbase"]
    .properties = [
      "name",
      "title",
      {
        name: "renderAs",
        title: "Render As"
      }
    ];

**Comment by xiuzhen1103** [comment]
I also tried following code, when I copy it into surveyJs, then click 'test survey' tab, it automatically wiped away my question. 

```
{
     "type": "imagepicker",
     "name": "question1"
    },
```

**Comment by tsv2013** [comment]
You sould add a custom property to a question base type, as described in this thread - https://surveyjs.answerdesk.io/ticket/details/T443

```JS
SurveyKo.JsonObject.metaData.addProperty("questionbase", "renderAs");
```

**Comment by xiuzhen1103** [comment]
is it add to editor?

https://surveyjs.io/Survey/Builder/

**Comment by andrewtelnov** [comment]
@xiuzhen1103 Here is [the example to add the property into the builder](https://surveyjs.io/Examples/Builder/?id=addproperties)

Thank you,
Andrew

**Comment by xiuzhen1103** [comment]
Hi Andrew, it dosen't make sense, I am not able to edit JavaScript code to add 
SurveyJs.JsonObject.metaData.addProperty("questionbase", "renderAs");
Especially in https://surveyjs.io/Survey/Builder/

**Comment by andrewtelnov** [comment]
@xiuzhen1103 Unfortunately  we do not support plug-ins and extensions for Survey Builder on our web site at the current moment.

Thank you,
Andrew
