### ISSUE TITLE
Bug : onQuestionAdded callback firing when moving a question

### ISSUE THREAD

**Issue by fastclemmy** [surveyjs/editor#297]
### Are you requesting a feature, reporting a bug or ask a question?

Reporting a bug.

### What is the current behavior?

When you drag a question to reorder it in a page, the onQuestionAdded callback is fired. Even if technically, you didn't _add_ a question but only move one.

### What is the expected behavior?

The callback shouldn't be fired. Maybe another event could be, like `onQuestionMoved` or `onQuestionReordered`.

The problem is that right now I use this callback to perform some actions that shouldn't occur when a question is moved.

Thanks!

### How would you reproduce the current behavior (if this is a bug)?

See pen below.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
https://codepen.io/fastclemmy/pen/ZxzYqg

### Specify your

* browser: Firefox 58.0.2
* editor version: 1.10.13

**Comment by andrewtelnov** [comment]
@fastclemmy I have fixed the issue. We have [onModified event](https://surveyjs.io/Documentation/Builder/?id=surveyeditor#onModified) and has type: DO_DROP.

Thank you,
Andrew

**Comment by qcnguyen** [comment]
Hi team, I think this bug happen again on SurveyCreator V2. can you double check please. 
Plunker: https://plnkr.co/edit/wvBo04G8dGoJkuTh
Thank you.

**Comment by novikov82** [comment]
For Creator V2 we create issue in Survey Library repository - https://github.com/surveyjs/survey-library/issues/4151
