### ISSUE TITLE
Show items in toolbar by categories (optional)

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/editor#300]
In some real world application, there can be over 100 different type of questions in toolbox. The only good solution here, is to categorized them and display items in toolbox in some accordion control.

UPD: Here is [the example](https://surveyjs.io/Examples/Builder/?id=toolboxcategories).

**Comment by andrewtelnov** [comment]
a catetory: string attribute is added into toolbox item. It can be empty/underfined if you want to leave the item in the General category or do not need to have categories at all.
And two new functions have been added:
```
/**
   * Change the category of the toolbox item
   * @param name the toolbox item name
   * @param category new category name
   */
  public changeCategory(name: string, category: string);
  /**
   * Change categories for several toolbox items.
   * @param changedItems the array of objects {name: "your toolbox item name", category: "new category name"}
   */
  public changeCategories(changedItems: Array<any>);
  
```

**Comment by mkopinsky** [comment]
This looks great! It would be nice if there were a way to specify a) that opening one category shouldn't close the other, and/or b) which categories should be expanded initially.

**Comment by andrewtelnov** [comment]
@mkopinsky Here is a new API that will be in the next version:
```
        editor.toolbox.allowExpandMultipleCategories = true;
        editor.toolbox.collapseAllCategories();
        editor.toolbox.expandCategory("Panels");
```

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@mkopinsky I am not sure about the title. We have a title attribute on image. Browser will show title, event the toolbox item is not truncated...

Thank you,
Andrew

**Comment by souareas** [comment]
How we can show the toolbox title general above the tools categories => toolbox: "Toolbox" ?
