### ISSUE TITLE
tsconfig.json : "noImplicitAny": false, ? Really ? Compilation problem with angular 5.

### ISSUE THREAD

**Issue by rlouissidney** [surveyjs/editor#301]
### Are you requesting a feature, reporting a bug or ask a question?

Ask a question : Why don't you compile with noImplicit to true ?
Can you suppress thes two errors of compilation ?
My typescript version  is 2.6

### What is the current behavior?
Compilation error

### What is the expected behavior?
Compilation pass

### How would you reproduce the current behavior (if this is a bug)?
Compile your angular project with : 
tsconfig.json : "noImplicitAny": true,

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code
Compilation error in surveyeditor.d.ts
export declare class TitleInplaceEditor {

Line 1701 : Parameter 'el' implicitly has an 'any' type
protected forNeibours(func: (el) => void): void;

Line 1703 : Parameter 'any' implicitly has an 'any' type
 valueChanged: (any) => void;

}
### Specify your

* browser:
* editor version: 1.0.12/1.0.13

**Comment by tsv2013** [comment]
Thank you for the contribution. Fix will be available in the nearest minor update. Most likely in a day or two.
