### ISSUE TITLE
Ratings question not working properly

### ISSUE THREAD

**Issue by healkar01** [surveyjs/editor#302]
Ratings questions that use text for the choices, rather than numbers display correctly in "Test Survey", but not correctly  when actually taking the survey.  Pictures below should help clarify the issue.

![rating survey preview](https://user-images.githubusercontent.com/20865786/37303760-d50191b4-2605-11e8-859b-e68bffad139d.jpg)
![rating test survey](https://user-images.githubusercontent.com/20865786/37303761-d50d38fc-2605-11e8-9577-374b8d8dd422.jpg)
![survey - rating choices](https://user-images.githubusercontent.com/20865786/37303763-d51aad5c-2605-11e8-98be-5a096ed4e370.jpg)

Thank you,

Karen Healey

**Comment by tsv2013** [comment]
I've reproduced the issue. We'll work on the fix.

**Comment by tsv2013** [comment]
Test JSON:
```
{
 pages: [
  {
   name: "page1",
   elements: [
    {
     type: "rating",
     name: "question3",
     rateValues: [
      {
       value: "1",
       text: "Not Satisfied"
      },
      {
       value: "2",
       text: "Somewhat Satisfied"
      },
      {
       value: "3",
       text: "Satisfied"
      },
      {
       value: "4",
       text: "Very Satisfied"
      }
     ]
    }
   ]
  }
 ]
}
```

**Comment by tsv2013** [comment]
I've fixed the issue. Fix will be available in the nearest minor update, most likely today or tomorrow.

**Comment by healkar01** [comment]
Thank you for the prompt fix!
