### ISSUE TITLE
Override default printed message when a Test Survey is completed.

### ISSUE THREAD

**Issue by puntnomads** [surveyjs/editor#305]
### Are you requesting a feature, reporting a bug or ask a question?

Asking a question

### What is the current behavior?

I can't modify the default printed message when a Test Survey is completed.

### What is the expected behavior?

A method that allows me to put my own custom message when Test Survey is completed.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by dmitrykurmanov** [comment]
Hello, please check the `completedHtml` setting of the Survey

![image](https://user-images.githubusercontent.com/22315929/37529929-71315cae-2949-11e8-8b8a-64a848d3cd3c.png)

Thanks.
