### ISSUE TITLE
Multiple text question - items tab - doesn't fit within box

### ISSUE THREAD

**Issue by Mille22r** [surveyjs/editor#310]
Hi, I tried two different browsers, doesn't look any different. See picture. Thanks!

![surveyjs - multiple text q - text doesn t fit](https://user-images.githubusercontent.com/35344899/37913399-c98e94d4-30e2-11e8-98c7-f2c5d15107e7.jpg)

**Comment by dmitrykurmanov** [comment]
Hello! I can't reproduce the bug. In chrome and firefox it looks ok:
![image](https://user-images.githubusercontent.com/22315929/37958764-047dff08-31ba-11e8-9bde-5904d2bda4d9.png)

It may be the problem in the environment, some additional css styles or scripts... What browser and survey-editor versions do you use? 
Could you please share an example to reproduce the bug. Thanks.
