### ISSUE TITLE
1.0.15 Typescript compilation errors

### ISSUE THREAD

**Issue by rlouissidney** [surveyjs/editor#311]
* editor version: 1.0.15 and Typescript 2.6.2
List of errors in surveyjseditor.d.ts
Severity	Code	Description		Line
Error		Build:Cannot redeclare block-scoped variable 'Version'. 	15	
Error		Build:Cannot redeclare block-scoped variable 'Version'.		15	
Error		Build:Cannot redeclare block-scoped variable 'Version'.		2450	
Error		Build:Cannot redeclare block-scoped variable 'Version'.     2450	
Error		Build:Cannot redeclare exported variable 'createAddItemHandler'.	2404	
Error		Build:Cannot redeclare exported variable 'createAddItemHandler'.	2404	
Error		Build:Cannot redeclare exported variable 'createAddItemHandler'.	2440	
Error		Build:Cannot redeclare exported variable 'createAddItemHandler'.	2440	
Error		Build:Subsequent variable declarations must have the same type.  Variable 'createAddItemHandler' must be of type '(question: QuestionSelectBase, onItemAdded: (itemValue: ItemValue) => void) => () => void', but here has type '(question: QuestionRating, onItemAdded: (itemValue: ItemValue) => void) => () => void'.	2440	
Error		Build:Subsequent variable declarations must have the same type.  Variable 'createAddItemHandler' must be of type '(question: QuestionSelectBase, onItemAdded: (itemValue: ItemValue) => void) => () => void', but here has type '(question: QuestionRating, onItemAdded: (itemValue: ItemValue) => void) => () => void'.	2440

**Comment by andrewtelnov** [comment]
@rlouissidney FYI: we are working on this issue.

Thank you,
Andrew

**Comment by kelinwu** [comment]
@andrewtelnov Just an FYI - this issue is not exit if pull the code and build it in windows environment, its only impact if ng build the code in Linux box.

**Comment by andrewtelnov** [comment]
@kelinwu Hm, ok, we will try to find out, what is going on.

Thank you,
Andrew

**Comment by dmitrykurmanov** [comment]
@kelinwu,  @kelinwu, I've reproduced it in Windows environment with our angular-cli. May be the problem with another environment.

**Comment by dmitrykurmanov** [comment]
we've fixed the bug, fix will be available in the next patch release. Or you could just use this bundle:  https://gist.github.com/dmitrykurmanov/db0d8e9bbb592dbd474abdf5a379cc7a
