### ISSUE TITLE
Event for Complete Test Survey

### ISSUE THREAD

**Issue by ltrtuan** [surveyjs/editor#312]
Are there events for Complete button in Test Survey tab ?
My purpose is super admin save test survey data when he build the survey. When he edit the survey, the saved data will populated in Test Survey field again (like onComplete and survey.data of surveyjs)

Thanks so much

**Comment by andrewtelnov** [comment]
@ltrtuan You may use the following code:
```
        editor.onTestSurveyCreated.add(function (editor, options) {
            options.survey.onComplete.add(function(testSurvey, options){
               //testSurvey.data = test survey results
            });
        });
```

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@ltrtuan There is no such a property at the current moment. I would agree that it makes sense to introduce it. I would do it on survey level and for text/comment questions.
About others and comments input text for other questions - I would introduce it on survey level only.
survey.maxTextLength (0 - no limits, for text and comment questions), survey.maxOthersLength (0 - no limits, for others and comments inputs in question)
Additionally, QuestionText and QuestionComment, maxLength (-1 - default,  gets the value from survey, 0 - no limits).
Will it work for you?

Thank you,
Andrew

**Comment by ltrtuan** [comment]
Awesome. It works perfect.
```
editor.onTestSurveyCreated.add(function(survey, options){ 
            var _valResults = $('#ipt-results').val();//This is my results from database

            /* Populate saved data to Test Survey form*/
            if(_valResults)
                options.survey.data = JSON.parse(_valResults);

           /* Event for clicking Complete button in Test survey form*/
            options.survey.onComplete.add(function(testSurvey, options){
                $('#ipt-results').val(JSON.stringify(testSurvey.data));
            });
        });
```
