### ISSUE TITLE
get Question Type as a value, not a class type.

### ISSUE THREAD

**Issue by puntnomads** [surveyjs/editor#318]
### Are you requesting a feature, reporting a bug or ask a question?

ask a question

### What is the current behavior?

I am getting options on onSetPropertyEditorOptions and getting question type by using options.obj.constructor.name. The problem is that when it is minified all constructors become t. 

### What is the expected behavior?

On the options.obj there a key( nested is okay) that tells me what type of question I am looking at.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by tsv2013** [comment]
Each survey object has `getType` function that returns string with the object type name.
So you can call 
```JS
options.obj.getType()
```

**Comment by tsv2013** [comment]
We'll check the reasen why this method is not described in the documentation.
Chrome browser console shows it in the autocomplete hint:
![image](https://user-images.githubusercontent.com/3013415/38791581-4b04d22a-4151-11e8-9c75-33b74eec330a.png)

**Comment by dmitrykurmanov** [comment]
We've added `getType` to the doc
