### ISSUE TITLE
RadioGroup: colCount is not respected if it comes after choices

### ISSUE THREAD

**Issue by jbryson3** [surveyjs/editor#319]
### Are you requesting a feature, reporting a bug or ask a question?
Reporting a bug

### What is the current behavior?
When adding a radiogroup question to the designer using the api, if the colCount comes after the choices are defined, the colCount is ignored.

```js
var q2 = editor.survey.pages[0].addNewQuestion('radiogroup');
q2.title = 'What is your favorite ice cream flavor?';
q2.choices = ['Chocolate', 'Vanilla', 'Banana', 'Strawberry'];
q2.colCount = 2;
```

![image](https://user-images.githubusercontent.com/675098/38709729-96befb74-3e8a-11e8-9932-60055caa2467.png)

### What is the expected behavior?
I see that colCount takes affect if defined after the choices. Property definition is order invariant when it comes to rendering any question.

![image](https://user-images.githubusercontent.com/675098/38709733-9d70e0fe-3e8a-11e8-9ab2-462d6d99713a.png)

### How would you reproduce the current behavior (if this is a bug)?
http://plnkr.co/edit/hvs67HXSButTzMv6gkH6?p=preview

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
http://plnkr.co/edit/hvs67HXSButTzMv6gkH6?p=preview

Test code

```js
var editorOptions = { };
var editor = new SurveyEditor.SurveyEditor("editorElement", editorOptions);

// Survey Builder lays the choices correctly in a 2 column format
var q1 = editor.survey.pages[0].addNewQuestion('radiogroup');
q1.title = 'What is your favorite ice cream flavor?';
q1.colCount = 2;
q1.choices = ['Chocolate', 'Vanilla', 'Banana', 'Strawberry'];

// Survey Builder incorrectly lays out the choices as 1 col
var q2 = editor.survey.pages[0].addNewQuestion('radiogroup');
q2.title = 'What is your favorite ice cream flavor?';
q2.choices = ['Chocolate', 'Vanilla', 'Banana', 'Strawberry'];
q2.colCount = 2;
```

### Specify your

* browser: Chrome 65
* editor version: 1.0.16

**Comment by tsv2013** [comment]
You need to tell editor that property has been changed:
```JS
var property = Survey.JsonObject.metaData.findProperty(
  q2.getType(),
  "colCount"
);
editor.onPropertyValueChanged(property, q2, q2.colCount);
```
Here is the updated fork of your plunk - http://plnkr.co/edit/tkWpRrjZvKHfTYhjcGYJ?p=preview

**Comment by jbryson3** [comment]
Under what scenarios would I have to tell the editor that the property has changed? It seems to react to some property changes, and not others?

**Comment by tsv2013** [comment]
@jbryson3 Some options are designed to be changeable during runtime (and these changes are immediately reflected in UI), some are not. I'm afraid I can't give you a list. Yes, the best way is always call `onPopertyValueChanged` if anything changed.
