### ISSUE TITLE
bug (surveyeditor.min.js, knockout_min.js)

### ISSUE THREAD

**Issue by Nuadire** [surveyjs/editor#320]
### Are you requesting a feature, reporting a bug or ask a question?
bug 

### What is the current behavior?
Uncaught TypeError: Unable to process binding "template: function (){return { name:'objecteditorproperty',afterRender:$parent.koAfterRender} }"
Message: Unable to process binding "click: function (){return $parent.changeActiveProperty($data) }"
Message: Illegal invocation
    at t.setTimeout (surveyeditor.min.js:12)
    at t.e.activate (surveyeditor.min.js:12)
    at e.set [as isActive] (surveyeditor.min.js:12)
    at a.zc.jb (surveyeditor.min.js:12)
    at Function.notifySubscribers (knockout_min.js:37)
    at Function.ha (knockout_min.js:41)
    at e.c [as koActiveProperty] (knockout_min.js:40)
    at e.changeActiveProperty (surveyeditor.min.js:12)
    at click (eval at parseBindingsString (knockout_min.js:68), <anonymous>:3:73)
    at knockout_min.js:104
    at init (knockout_min.js:90)
    at init (knockout_min.js:104)
    at knockout_min.js:72
    at Object.w (knockout_min.js:40)
    at knockout_min.js:72
    at Object.r (knockout_min.js:11)

* browser:
Google Chrome
Version 65.0.3325.181 (Official Build) (64-bit)
* editor version:
1.0.17
knockout_min.js - v3.4.2

**Comment by Nuadire** [comment]
`<!DOCTYPE html>
<html lang="en">
    <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Survey</title>
    <script src="/WebResources/cp_JS/jQuery2/jquery2Latest.js"></script>
    <script src="/WebResources/cp_survey/survey/editor/knockout_min.js"></script>
    <script src="/WebResources/cp_survey/survey/editor/survey.ko.min.js"></script>
    <script src="/WebResources/cp_survey/survey/editor/surveyeditor.min.js"></script>
    
    <link href="/WebResources/cp_JS/bootstrap4/css/bootstrap.min.css" type="text/css" rel="stylesheet">
    <link href="/WebResources/cp_survey/survey/editor/css/surveyeditor.css" type="text/css" rel="stylesheet">
    <script src="/WebResources/cp_survey/survey/widgets/select2.full.min.js" type="text/javascript"></script>
    <link href="/WebResources/cp_survey/survey/widgets/css/select2.min.css" type="text/css" rel="stylesheet">

    <script src="/WebResources/cp_XrmWebApiClient/WebApiClient.js" type="text/javascript"></script>

    <script src="/WebResources/cp_survey/survey/widgets/surveyjs_widgets.js" type="text/javascript"></script>
    <meta><style type="text/css">P { margin: 0; }</style>
</head>
<body  style="word-wrap: break-word;" class="vsc-initialized">
    <div id="surveyContainer" style="font-family: undefined;">
        <div id="editorElement"></div>
    </div>
    <script type="text/javascript" src="/WebResources/cp_survey/survey/editor/cp_surveyEditor.js"></script>

</body></html>`
`var editorOptions = {
		showJSONEditorTab: false,
		showTestSurveyTab: false,
		showEmbededSurveyTab : false,
		isAutoSave: true
	};
var editor = new SurveyEditor.SurveyEditor("editorElement", editorOptions);`

**Comment by Nuadire** [comment]
[cp_surveyEditor.txt](https://github.com/surveyjs/editor/files/1926605/cp_surveyEditor.txt)
[index.txt](https://github.com/surveyjs/editor/files/1926606/index.txt)

**Comment by tsv2013** [comment]
This is caused by https://github.com/surveyjs/surveyjs-nodejs/issues/4

**Comment by dmitrykurmanov** [comment]
we've released new 1.0.18
