### ISSUE TITLE
Change OrderedQuestions

### ISSUE THREAD

**Issue by FranGhe** [surveyjs/editor#321]
Hi,
can I change the ordered question dynamically?

**Comment by dmitrykurmanov** [comment]
Hello! Please describe your use case in greater details. Do you want to reorder questions by js before show the suvery?

**Comment by FranGhe** [comment]
Yes. Excuse my question, but I have starded to use SurveyEditor today...
I have seen this code in examples:
editor
    .onCanShowProperty
    .add(function (sender, options) {
        if (options.obj.getType() == "survey") {
            options.canShow = options.property.name == "title";
        }
    });
but it work only before showing a property, not before show the suvery.
Another question... I need to show multiple options, not only "title"

**Comment by tsv2013** [comment]
Each time property editor is being rendered the `onCanShowProperty` event is fired. Different objects and properties are passed in the `options` object. You can check the property and set the `canShow` flag to `true` if you want to see this property or to `false` if you don't want to see it.
The sample above hides all properties except the `title` for an object of type `survey`. You can change the logic according your requirements.

**Comment by tsv2013** [comment]
I'm sorry but I'm afraid I don't understand you. `onCanShowProperty` affects property editors in property grid in the right panel and properties in the modal editor. They are always available after survey appears.

**Comment by FranGhe** [comment]
I would like to have this screen as soon as I call the page
![schermata del 2018-04-19 11-42-21](https://user-images.githubusercontent.com/35761071/38984473-0d7b4e3e-43c7-11e8-9813-c7f4628bb045.png)

**Comment by tsv2013** [comment]
Thanks for the clarfication. I've understood.
Initally properties are visible unless you change the selection.
The `onCanShowProperty` event should fire befor the first selection.
It's a bug. We'll fix it.

**Comment by FranGhe** [comment]
... the beginner's luck ;)
