### ISSUE TITLE
Reorder Items/Properties in toolbox

### ISSUE THREAD

**Issue by FranGhe** [surveyjs/editor#322]
Can I reorder items/properties in their toolbox?
I would like to reorder them by my order... with array for example

**Comment by andrewtelnov** [comment]
@FranGhe You have to use (editor.onCustomSortProperty)[https://surveyjs.io/Documentation/Builder/?id=surveyeditor#onCustomSortProperty] event.

Thank you,
Andrew

**Comment by FranGhe** [comment]
onCustomSortProperty it's a event, so it's called multiple times in use.
Is it possible set it only the first time... as soon as I call the page, Like:
     survey
        .toolbox
        .orderedQuestions=[
            "text",
            "checkbox",
            "radiogroup",
            "boolean",
            "dropdown",
            "comment",
            "rating",
            "html"
        ];

If is not possible... I have tried more time and I can't figure out how to use onCustomSortProperty and sort the property.
I would like ordered them tilte - locale - isSinglePage - showProgressBar - showQuestionNumbers

Excuse me... but I'm a student.

http://plnkr.co/edit/RYuRnev3JqL7JWbxSOp5?p=preview

**Comment by andrewtelnov** [comment]
@FranGhe I have update the plunker: http://plnkr.co/edit/mZxBWtkmUU47cEmd9ZHl?p=preview
You should set options.result, 0 items are equal, -1 the first is less (shows higher), 1 the first is bigger (shows below).

Thank you,
Andrew
