### ISSUE TITLE
Default value for storeDataAsText 

### ISSUE THREAD

**Issue by sam031026** [surveyjs/editor#324]
### Are you requesting a feature, reporting a bug or ask a question?

Question

### What is the current behavior?

By default storeDataAsText for a file control is true

### What is the expected behavior?

How to set storeDataAsText = false by default?

#### Provide the test code and the tested page URL (if applicable)
I tried with findProperty, but we have only "questionbase" initialized and file instance is null.
Survey
            .JsonObject
            .metaData
            .findProperty("file", "storeDataAsText")

Also I tried with onModified event, but didn't work for me.

Thank you,
Alexander

**Comment by tsv2013** [comment]
I think you need to redeclare the property - remove it first and add again:
```JS
Survey.JsonObject.metaData.removeProperty("file", "storeDataAsText");
Survey.JsonObject.metaData.addProperty("file", {
                            name: "storeDataAsText",
                            default: false
                        });
```

**Comment by andrewtelnov** [comment]
@sam031026 You may use findProperty function:
`Survey.JsonObject.metaData.findProperty("file", "storeDataAsText").defaultValue = false;`

Thank you,
Andrew

**Comment by sam031026** [comment]
Hi, I still have the issue with set default for storeDataAsText, it doesn't work for me

This is a link on plunker 
https://plnkr.co/edit/xAYBdZI0LQlQ64VK933h?p=preview

Thanks

**Comment by andrewtelnov** [comment]
@sam031026 Aha, then please review [this example](https://plnkr.co/edit/r2uxsY?p=info)
It does exactely what you need.

Thank you,
Andrew

**Comment by sam031026** [comment]
@andrewtelnov Thanks a lot! it works for me now.

var editorOptions = {};
var editor = new SurveyEditor.SurveyEditor("editorElement", editorOptions);

var file = editor.toolbox.getItemByName("file");
file.json = {type: "file", storeDataAsText: "false"};

Спасибо!

**Comment by agustinparamio** [comment]
It also worked for me using @sam031026 response.
Added the next part to hide option:
```
SurveyJSCreator.SurveyQuestionEditorDefinition.definition[
      "file"
    ].properties.push({ name: "storeDataAsText", visible: false });
```
And then
```
surveyCreator = new SurveyJSCreator.SurveyCreator(
      "surveyCreatorContainer",
      options
    );
var file = surveyCreator.toolbox.getItemByName("file");
file.json = { type: "file", storeDataAsText: false };
```
