### ISSUE TITLE
How to call Function on click on "Next" button In form pagination .

### ISSUE THREAD

**Issue by ak34504** [surveyjs/editor#327]
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by tsv2013** [comment]
A survey model has [onCurrentPageChanged](https://surveyjs.io/Documentation/Library/?id=surveymodel#onCurrentPageChanged) event.
If you are working with an editor, it has the [survey](https://surveyjs.io/Documentation/Builder/?id=surveyeditor#survey). And here you can subscribe the mentioned event.
