### ISSUE TITLE
"onModified" event does not trigger upon question focus loss

### ISSUE THREAD

**Issue by dmykra** [surveyjs/editor#328]
### Are you requesting a feature, reporting a bug or ask a question?
Reporting a bug.

### What is the current behavior?
The "onModified" event does not trigger on changes made through inline editing.

### What is the expected behavior?
The event should trigger, as it does when modifying properties through the "Edit" dialog.

### How would you reproduce the current behavior (if this is a bug)?
Subscribe to the "onModified" event, then add a question. Change the title and optionally any visible properties using the inline edit, then click outside the question to lose focus.

#### Provide the test code and the tested page URL (if applicable)
```
        this.editor.onModified.add(() => {
            console.log("onModified");
        });
```

### Specify your

* browser: firefox
* editor version: 1.0.13

**Comment by tsv2013** [comment]
I've just checked this saple - https://plnkr.co/edit/ykJ5r6?p=preview in Chrome and Firefox - and alert popup is shown ok for me on each modification. Please check if I miss something.

**Comment by dmykra** [comment]
Upgraded to version 1.0.20 and can no longer reproduce the issue 👍
