### ISSUE TITLE
Configure allowed depth of nested elements

### ISSUE THREAD

**Issue by Ewilliams90** [surveyjs/editor#331]
### Are you requesting a feature, reporting a bug or ask a question?

Asking a question

### What is the current behavior?

Panels can be infinitely nested  

### What is the expected behavior?

I would like to only allow one level of nesting 

i.e. Page > Panel > Questions

Not

Page > Panel > Panel > Questions

Is there a way I can achieve this now? Maybe by way of the callbacks triggered when a panel is added?

**Comment by andrewtelnov** [comment]
@Ewilliams90 @tsv2013 We are missing onAllowDrop event. It makes sense to add it.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@Ewilliams90 onAllowDrop was not easy to implement & it would be hard to use. Since the only scnenario that came into mine mind is to forbidden the nested panels. So from the next version, that we will likely release it tomorrow, you will be able:
```
//do not allow to put panel into panel
SurveyEditor.DragDropHelper.nestedPanelDepth = 0;
//allow put panel into panel, but not allow panel->panel->panel
SurveyEditor.DragDropHelper.nestedPanelDepth = 1;
//nested panels can be unlimited
SurveyEditor.DragDropHelper.nestedPanelDepth = -1;
```

Thank you,
Andrew
