### ISSUE TITLE
Hidden question different from previous versons

### ISSUE THREAD

**Issue by xiuzhen1103** [surveyjs/editor#333]
### Are you requesting a feature, reporting a bug or ask a question?
Ask a question

### What is the current behavior?
I was using this version: "survey-react": "0.12.18",
I have updated latest version of survey-jquery, it cause issue for me. 

In old version, I have using customized class for hidden HTML by JQuery selector
Currently if it is not visible, it broken my function as following:
`<!-- ko if: row.koVisible -->`

In my version,it was following HTML element for hidden question. 
`style="display: none;"`

### What is the expected behavior?
Is there any chance I could roll back to previous hidden question format, but keep latest version, please?

### How would you reproduce the current behavior (if this is a bug)?
This is old version survey-jquery
https://plnkr.co/edit/PojiUA?p=preview
![image](https://user-images.githubusercontent.com/6764095/39256180-23cf9b48-48a6-11e8-9542-7385c0f976f9.png)

This is latest version
https://plnkr.co/edit/5taWGy9xKfgLqw2SIbFu?p=preview
![image](https://user-images.githubusercontent.com/6764095/39256314-7acf63d8-48a6-11e8-861c-2dd615630cea.png)

**Comment by tsv2013** [comment]
@xiuzhen1103 This issue is related to the editor repo. I've created clone - https://github.com/surveyjs/surveyjs/issues/1063
Closing this
