### ISSUE TITLE
Customize modal of a new question

### ISSUE THREAD

**Issue by ma7moudNabil** [surveyjs/editor#334]
### Are you requesting a feature, reporting a bug or ask a question?
Asking a question

Added a question named 'branching' as an html question, how can i change "Visible if" text in the editor modal to "If GO" and how to remove the html editor in the modal

thanks

```
    editor
    .toolbox
    .addItem({
        name: "branch",
        isCopied: true,
        iconName: "fa fa-share-alt",
        title: "Branching",
        json: {
            "type": "html"
        }
    });

```

### Specify your

* editor version:v0.98.1

**Comment by andrewtelnov** [comment]
@ma7moudNabil I would suggest to go to the latest version. v0.98.1 is a beta version.
1) SurveyEditor.defaultStrings.tabs.visibleIf = "If GO";
2) editor.toolbox.removeItem("html"); Here is [the docs](https://surveyjs.io/Examples/Builder/?id=toolboxcustomization#content-docs)

Thank you,
Andrew

**Comment by ma7moudNabil** [comment]
@andrewtelnov  your input is highly appreciated! :))

**Comment by andrewtelnov** [comment]
@ma7moudNabil Here is [the example](https://plnkr.co/edit/1Y3icfDb02UaOvyke3CS?p=preview)

Thank you,
Andrew

**Comment by ma7moudNabil** [comment]
Thank you @andrewtelnov, this is really useful but that will be applied for all html questions

my question was for this question 
 editor
    .toolbox
    .addItem({
        name: "branch",
        isCopied: true,
        iconName: "fa fa-share-alt",
        title: "Branching",
        json: {
            "type": "html"
        }
    });

is there a way to apply the changes you shared on plunker only on that question type "branch" ? 

Thanks a million in advance!

**Comment by andrewtelnov** [comment]
@ma7moudNabil I am completely lost. What is your scenario. You have removed the standard html toolbox item and add your own. The better way is to find the item 
```
var item = editor.toolbox.findItem("html");
item.json = {your new json};
item.title = "Branching";
```
So you have a template that you may drop on survey several times. What is your next task? What do you try to implement.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
Oh, do you want to have a branch question type?
Then add the following code:
`Survey.JsonObject.metaData.addClass("branch, {}, null, "html");`
Then add this class into toolbox and customize it's tabs in question editor.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@ma7moudNabil Here is [the example](https://plnkr.co/edit/lDPUJgT3tFsnJ9YvLR2R?p=preview)

Thank you,
Andrew
