### ISSUE TITLE
Styling the default editor color

### ISSUE THREAD

**Issue by leksinteractive** [surveyjs/editor#337]
### Are you requesting a feature, reporting a bug or ask a question?

Question: I can see that we can apply a theme to the survey, however is there a way to style the editor color? What would be the best approach of doing this (overriding CSS?) ? The color that I am referring to is the default greenish/turquoise one on all the elements and icons.

Also this page in the documentation gives me an error:
https://surveyjs.io/Examples/Builder/?id=orange-theme&theme=bootstrap

![screen shot 2018-05-03 at 12 29 10 pm](https://user-images.githubusercontent.com/3906239/39560081-9e937d5e-4ecd-11e8-91be-ca3058674800.png)

**Comment by andrewtelnov** [comment]
@leksinteractive Forgot to add, you may find [this example](https://surveyjs.io/Examples/Builder/?id=editor-custom-theme) useful.

Thank you,
Andrew

**Comment by leksinteractive** [comment]
Thanks @andrewtelnov 👍 That works now.

Follow up question regarding the property editor... if I set `showPropertyEditor=false` the property editor is not visible which is as expected, however there seems to be some css classes overriding the width of the other two panels so it looks like this.

![screen shot 2018-05-07 at 11 50 10 am](https://user-images.githubusercontent.com/3906239/39684224-da3db6fe-51ec-11e8-9b95-b9300aa99d1c.png)

It looks like these two rules are overriding the bootstrap `col-*` classes.

```
.svd_container.sv_default_css .svd_toolbox {
    float: left;
    width: 15%;
}
```

```
.svd_container.sv_default_css .svd_editors {
    display: inline-block;
    width: 60%;
    padding: 0 15px;
}
```

**Comment by andrewtelnov** [comment]
@leksinteractive Yes, we will work on the fix.

Thank you,
Andrew

**Comment by dmitrykurmanov** [comment]
We've fixed the ptoblem with "width". And what about `showPropertyEditor` property ? In our doc and sources I found only the `showPropertyGrid` property...

**Comment by leksinteractive** [comment]
Sorry, `showPropertyEditor` was a typo mistake on my end, I am actually using `showPropertyGrid`.

**Comment by andrewtelnov** [comment]
@leksinteractive No problem, the more important, we have fixed the bug :)

Thank you for let us know about the issue,
Andrew
