### ISSUE TITLE
Question limit per page and non-editable questions

### ISSUE THREAD

**Issue by leksinteractive** [surveyjs/editor#340]
### Are you requesting a feature, reporting a bug or ask a question?

Couple of questions:
1. Is it possible to limit the number of questions per page?
2. How would you achieve the ability to let certain questions not be editable? 

These two are related in my use case in the following way. I need the ability for user to create template questions, one at a time (basically allow them to add a single question and then save that, no need for pages)... and later be able to use those when creating surveys after we've made them available in the question toolbox. Ideally the user should be able to specify if the question is editable. 

Hope that makes sense - thanks in advance.

**Comment by tsv2013** [comment]
1. SurveyJS Editor has the following events:
- [onQuestionAdded](https://surveyjs.io/Documentation/Builder/?id=surveyeditor#onQuestionAdded)
- [onPanelAdded](https://surveyjs.io/Documentation/Builder/?id=surveyeditor#onPanelAdded)
- [onPageAdded](https://surveyjs.io/Documentation/Builder/?id=surveyeditor#onPageAdded)
You can handle them and inform user about the questions limit is reached and remove just added question.
Probably an event like `beforeQuestionAdded` would be more useful in this case, but we haven't such an event for a while. It's a matter of a discussion with the team (@andrewtelnov, @dmitrykurmanov)

2.
- The [onElementAllowOperations](https://surveyjs.io/Documentation/Builder/?id=surveyeditor#onElementAllowOperations) event allows to disable context question actions.
- The [onCanShowProperty](https://surveyjs.io/Documentation/Builder/?id=surveyeditor#onCanShowProperty) event allows to hide propetyies in the property grid

If you need I can create a sample for you in a couple of days.
