### ISSUE TITLE
Custom items in element menu have no visible icons

### ISSUE THREAD

**Issue by rygler** [surveyjs/editor#343]
### Are you requesting a feature, reporting a bug or ask a question?
Reporting a bug.

### What is the current behavior?
When a custom item is added to the element menu, because it is missing an icon, it is not visible. The item is clickable, and the title appears on hover, but there is no icon.

### What is the expected behavior?
Allow an icon to be set. Or display the custom elements in a dropdown, similar to the old behavior, which would expose the items by title instead of by icons.

### How would you reproduce the current behavior (if this is a bug)?
1) Add a custom item into the element menu as shown [here](https://surveyjs.io/Examples/Builder/?id=elementmenu&theme=bootstrap).
2) Observe that the result places the new item on the left of the default edit item, but is invisible due to the lack of an icon, though it is clickable.

* editor version: 1.0.22

**Comment by rygler** [comment]
@andrewtelnov I am referring to the element menu not the toolbox.

See the screenshot below. This is what happens when you use [this example](https://surveyjs.io/Examples/Builder/?id=elementmenu&theme=bootstrap) and hover over the area left of the edit icon where the arrow is pointed. 

![Screenshot](https://user-images.githubusercontent.com/16928457/40136654-62678bba-5916-11e8-9998-5922c3a68198.jpg)

**Comment by andrewtelnov** [comment]
@rygler Yes. you are right. We have changed UI and forgot about this demo.
We will fix it.

Thank you,
Andrew

**Comment by tsv2013** [comment]
You can do it via SVG image or CSS. Here is updates sample - https://plnkr.co/edit/Ecm8aen9q4GIEBeO3Tqg?p=preview

```JS
// Add a new item into element menu
editor
    .onDefineElementMenuItems
    .add(function (editor, options) {
        options
            .items
            .unshift({
                name: "addtosharedrepo",
                text: "Add Into Shared Repository",
                onClick: function (obj) {
                    addIntoCustomItems(obj);
                }
            });
    });
```

SVG Image:
```HTML
<svg style="display: none;">
    <symbol viewBox="0 0 16 16" id="icon-actionaddtosharedrepo"><path d="M7.3 8H1v2h5.2c.2-.7.6-1.4 1.1-2zM10 6.2V5H1v2h7.3c.5-.3 1.1-.6 1.7-.8zM1 2h9v2H1zM11.5 7C9 7 7 9 7 11.5S9 16 11.5 16s4.5-2 4.5-4.5S14 7 11.5 7zm2.5 5h-2v2h-1v-2H9v-1h2V9h1v2h2v1z"></path></symbol>
</svg>
```
CSS rule:
```CSS
.icon-actionaddtosharedrepo::before {
  content: "+";
  font-size: 20px;
  position: absolute;
  top: -2px;
}
```

I've also fixed the sample on our site. It will be updated soon.

**Comment by rygler** [comment]
@tsv2013 Thanks. This works for me
