### ISSUE TITLE
Can "single input" 'date' & 'time' types have a restriction on minumum and maximum

### ISSUE THREAD

**Issue by rangasurendra** [surveyjs/editor#346]
### Are you requesting a feature, reporting a bug or ask a question?
Question

### What is the current behavior?

Hi ,
For a 'date' or 'time' type in a "single input" question, can we set min and max date ? Or do I have to write a custom widget for that ?

### What is the expected behavior?

Setting min max from properties window to right hand side(for date input types may be)

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by tsv2013** [comment]
You can validate value in the [onValidateQuestion](https://surveyjs.io/Documentation/Library/?id=surveymodel#onValidateQuestion) event handler.
I've created a sample for you - https://plnkr.co/edit/pRkkJ84TYWeOrDsTOxF9?p=preview

**Comment by rangasurendra** [comment]
This is even possible in adding validator with an expression, your option is fine. looking for option to disable range of dates using min max properties, so user cannot select invalid dates in first place.

**Comment by andrewtelnov** [comment]
@rangasurendra Here is another example: https://plnkr.co/edit/GaJsolwKtSKdr85yjTbc?p=preview
It uses an expression validator and s custom function.

Thank you,
Andrew

**Comment by rangasurendra** [comment]
Thanks @andrewtelnov and @tsv2013 for the examples, managed to go ahead with validators
Ranga
