### ISSUE TITLE
Integration of the builder with the library

### ISSUE THREAD

**Issue by JEricaM** [surveyjs/editor#348]
### Are you requesting a feature, reporting a bug or ask a question?
Question

### What is the current behavior?
Hi.
I want to develop a website for creating surveys and I thought about starting experimenting with the survey.js library. If I decide later to use the builder, it's easy to integrare the builder to the project that use the library only? Is there any documentation about it?
Hope that my question it's understandable.

Thank you in advance.

**Comment by tsv2013** [comment]
The SurveyJS library and builder can be integrated separately in the same project.
There is no special documentation concerning the parts integration.

We have sample repos illustrating this:
https://github.com/surveyjs/surveyjs_angular_cli
https://github.com/surveyjs/surveyjs_vue_quickstart
https://github.com/surveyjs/surveyjs_react_quickstart

Also we have server-side examples:
https://github.com/surveyjs/surveyjs-php
https://github.com/surveyjs/surveyjs-nodejs
https://github.com/surveyjs/surveyjs-aspnet-mvc

Please feel free to contact us in case of any further difficulties

**Comment by JEricaM** [comment]
Thank you for your answer, I will check the links :)
