### ISSUE TITLE
How to Remove Other Option from Selection Questions 

### ISSUE THREAD

**Issue by nrhoffmann** [surveyjs/editor#356]
### Quick Question

What are the properties that I need to remove to remove the other option?

**Comment by andrewtelnov** [comment]
@nrhoffmann Do you mean from Editor?
Here is [help topic](https://surveyjs.io/Documentation/Builder/#removeproperties)

Thank you,
Andrew

**Comment by nrhoffmann** [comment]
Yes... But I looked at the [docs](https://surveyjs.io/Documentation/Library/?id=QuestionSelectBase) and could not identify the appropriate properties.

**Comment by andrewtelnov** [comment]
@nrhoffmann "hasOther", "otherErrorText" and "otherText"

Thank you,
Andrew

**Comment by nrhoffmann** [comment]
Thank **you**!
