### ISSUE TITLE
Error on removing answers

### ISSUE THREAD

**Issue by mstoecke** [surveyjs/editor#357]
### Are you requesting a feature, reporting a bug or ask a question?

Bug

### What is the current behavior?

Removing answers from Checkboxes or Radiogroups causes an error and autosave is not triggered.

### What is the expected behavior?

The error should not occur and autosave should work.

### How would you reproduce the current behavior (if this is a bug)?

Create Checkbox or Radiogroup and remove one of the answers.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjs.io/Survey/Builder/

### Specify your

* browser: Chrome 67
* editor version: 1.0.27

![image](https://user-images.githubusercontent.com/32272176/41644758-52716e8c-746f-11e8-931f-40a6ca16d021.png)

**Comment by dmitrykurmanov** [comment]
@mstoecke it is a bug, we will fix it as soon as possible, thank you.

**Comment by dmitrykurmanov** [comment]
fixed, the fix will be available in the next patch release (today)

**Comment by mstoecke** [comment]
Thanks a lot! I highly appreciate your work!
