### ISSUE TITLE
DefaultValue for radiogroup not removable

### ISSUE THREAD

**Issue by mstoecke** [surveyjs/editor#358]
### Are you requesting a feature, reporting a bug or ask a question?

Feature

### What is the current behavior?

If you set the defaultValue for a radiogroup, it seems to be impossible to remove it again. You can only remove it in the JSON Editor.

### What is the expected behavior?

I think there should be an option to remove the defaultValue on the modal.

### How would you reproduce the current behavior (if this is a bug)?

Set the defaultValue for a radiogroup and try to remove it.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjs.io/Survey/Builder/

### Specify your

* browser: Chrome 67
* editor version: 1.0.28

![image](https://user-images.githubusercontent.com/32272176/41718648-d6a9c49e-755d-11e8-953a-3b95947dd0b0.png)

**Comment by andrewtelnov** [comment]
@mstoecke The clear button will be available in the next minor update on the next week.
See the [related issue in the library repo](https://github.com/surveyjs/surveyjs/issues/1176)

Thank you,
Andrew

**Comment by mstoecke** [comment]
Well done! Thanks!
