### ISSUE TITLE
Sort the user entries in a matrix (dynamic rows)

### ISSUE THREAD

**Issue by brundles** [surveyjs/editor#359]
### Are you requesting a feature, reporting a bug or ask a question?

This is a **question** (or a feature-request if not possible to solve using some JS):

### What is the current behavior?

I've build a matrix with dynamic rows, where i ask users to input som CV information. They enter start-year, end-year, and a description.

If i enter the years in wrong chronological order they (of course ;-) stay like that.

### What is the expected behavior?

I would like to somehow be able to sort the entry in chronological order, ie. based on each year. 

How can this be done?

Any help / pointers will be greatly appreciated :)

### Current JSON

```
{
 "pages": [
  {
   "name": "PAGE",
   "elements": [
    {
     "type": "matrixdynamic",
     "name": "EDUCATION",
     "titleLocation": "hidden",
     "columns": [
      {
       "name": "YEAR_FROM",
       "title": "YEAR FROM",
       "cellType": "text"
      },
      {
       "name": "YEAR_TO",
       "title": "YEAR TO",
       "cellType": "text"
      },
      {
       "name": "INSTITUTION",
       "title": "INSTITUTION",
       "cellType": "text"
      }
     ],
     "cellType": "text",
     "rowCount": 1,
     "minRowCount": 1,
     "addRowText": "ADD",
     "removeRowText": "REMOVE"
    }
   ]
  }
 ],
 "showPageTitles": false,
 "showQuestionNumbers": "off"
}
```

**Comment by andrewtelnov** [comment]
@brundles Do you want to sort them visually or do you want to have results sorted?
If you are talking about results, then please use onComplete event:
```
survey.onComplete.add(function(survey, options) {
  var matrixValue = survey.getValue("matrixQuestionName");
  if(!matrixValue || !Array.isArray(matrixValue)) return;
  //matrixValue is array
  //Sort it as needed
  //put the correct data
  survey.setValue("matrixQuestionName", matrixValue);
});
```

Thank you,
Andrew

**Comment by brundles** [comment]
This way is very good, thanks! 

I can see the results will be sorted. But actually I also wanted to sort them visually, if in any way possible? 

Ie. when i click next, but then go back it would "show me what would get saved"?

**Comment by andrewtelnov** [comment]
@brundles You may use [onCurrentPageChanged event](https://surveyjs.io/Documentation/Library/?id=surveymodel#onCurrentPageChanged)

Thank you,
Andrew

**Comment by brundles** [comment]
Superb - checking it now, thanks :) :)

**Comment by andrewtelnov** [comment]
@brundles Forgot to say, you may use the same code.

Thank you,
Andrew

**Comment by brundles** [comment]
Super! Thank you. Still reading up on it :)

**Comment by brundles** [comment]
Works - closing this ticket :)
