### ISSUE TITLE
Style of trigger modal

### ISSUE THREAD

**Issue by siskender** [surveyjs/editor#36]
Using bootstrap v3.3.7 the layout of the modal when pressing on the "trigger" button is really messed up.

* The dropdown is visible from start and is not toggled when pressing on the add button
* The add button and the remove buttons are not correctly aligned to the dropdown field
* The add button for adding a page or question (visible trigger) is invisible

![modal](https://cloud.githubusercontent.com/assets/8503234/22201507/385634b4-e164-11e6-80f9-485942ca5c71.PNG)
![visible](https://cloud.githubusercontent.com/assets/8503234/22201508/3867a938-e164-11e6-837f-ceddfade8772.PNG)

**Comment by andrewtelnov** [comment]
@siskender  Yes, it doesn't look good :(

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@siskender I have fixed the issues and updated it on http://surveyjs.org/builder/
Could you please check it out?

Thank you,
Andrew

**Comment by siskender** [comment]
It looks good now. Thanks!
