### ISSUE TITLE
Expressions in a dynamic matrix - how to know current row?

### ISSUE THREAD

**Issue by brundles** [surveyjs/editor#360]
### Are you requesting a feature, reporting a bug or ask a question?

First, i really have to stress that I'm a HUGE fan of the work you've done so far. Its nothing short of amazing!

I have a **question**:

I'm doing a dyamic matrix where the user is adding multiple rows.

Here i would initially just like to number each of these dynamically, so that each row has the columns "row number" and "contents".

I thought i could just use the first column as being an expression, and here just somehow refer to the current rownumber. 

Is there any way to do that?

Or am i approaching the question wrongly?

**Comment by andrewtelnov** [comment]
@brundles I am not sure I got you correctly.
There are several events that should allow to implement what you need:
[onMatrixCellCreated](https://surveyjs.io/Documentation/Library/?id=surveymodel#onMatrixCellCreated)
and [onMatrixAfterCellRender](https://surveyjs.io/Documentation/Library/?id=surveymodel#onMatrixAfterCellRender)
Let me know if it helps.

Thank you,
Andrew

**Comment by brundles** [comment]
Ok - i can see the explanation was not super.

Here is a screenshot that might be better:

![image](https://user-images.githubusercontent.com/6731143/41783260-b9a0afae-763c-11e8-8bc0-1abc3fee6563.png)

Ie i want each row to have an automated number (so users dont have to fill it in manually).

When i read the two events you suggest above it could seem like "rowValue" was the answer.

In that case i would expect to be able to add a column as an expression with this value = "{row. rowValue}" - only that does not work, so i'm somehow referring to it wrongly

**Comment by andrewtelnov** [comment]
@brundles Yes, I was trying to implement it myself and I did not find any good solution for the current version. I will take care about this scenario.

Thank you,
Andrew

**Comment by brundles** [comment]
Hi @andrewtelnov - ok thank you so much. Still looking at it here, let me know if you have thoughts on direction, then i will post any solution found here.

**Comment by andrewtelnov** [comment]
@brundles I have implemented the [following functionality](https://github.com/surveyjs/surveyjs/issues/1193).
It will be available in the next minor release on the next week.

Thank you,
Andrew

**Comment by brundles** [comment]
@andrewtelnov - This absolutely fantastic!!! - A huge thank you! So there will be a "RowIndex" variable to be used in expressions?

As i can see you already did the commit, can i try to take src/question_matrixdropdownbase.ts and play with it myself?

:)

**Comment by andrewtelnov** [comment]
@brundles You may build surveyjs from sources. Here is [the instruction](https://github.com/surveyjs/surveyjs#building-surveyjs-from-sources)

Thank you,
Andrew

**Comment by brundles** [comment]
Superb!

Thank you so much :) 👍 👍 👍
