### ISSUE TITLE
Remove survey settings button in builder

### ISSUE THREAD

**Issue by testweird123** [surveyjs/editor#361]
### Are you requesting a feature, reporting a bug or ask a question?
Question

Is there a way to hide/remove the survey settings button in the builder?
Also it may be a good idea to add all the properties which can be hidden, into the documentation.

Thank you.

### Specify your

- browser: Chrome 67
- editor version: 1.0.28

**Comment by tsv2013** [comment]
You can do it via toolbox items customization.
Here is the sample - https://plnkr.co/edit/oTp93bPNGckQ96fvw5ev?p=preview
Here is the basic sample + documentation - https://surveyjs.io/Examples/Builder/?id=toolbarcustomization&theme=bootstrap

**Comment by testweird123** [comment]
Thanks a lot!!!
Is there a way to remove the option to add, remove and navigate between pages which is present below the toolbar? It is not part of the toolbarItems().

Thank you.

**Comment by tsv2013** [comment]
I think this was discussed here - [disable/enable ability to add new page](https://github.com/surveyjs/editor/issues/344)
Does it fit your needs?

**Comment by testweird123** [comment]
Thank you, This does fit my needs.

**Comment by moussa-b** [comment]
> You can do it via toolbox items customization.
> Here is the sample - https://plnkr.co/edit/oTp93bPNGckQ96fvw5ev?p=preview
> Here is the basic sample + documentation - https://surveyjs.io/Examples/Builder/?id=toolbarcustomization&theme=bootstrap

You can also pass a function to `remove` method in order to avoid to create an intermediary variable :

`editor.toolbarItems.remove(function(item) {
    return item.id === "svd-survey-settings";
  });`
