### ISSUE TITLE
hidden question values are not included in json

### ISSUE THREAD

**Issue by mkgn** [surveyjs/editor#363]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
hidden question values are not included in json after completing the survey

### What is the expected behavior?
Have an option to include values in hidden fields when submitting data

### How would you reproduce the current behavior (if this is a bug)?
Create a survey with a hidden text field having a default value (Let's say that this is the unique-id for the entire survey)

When completing the survey above data is not included in the json

If we have a similar feature or a way to do something like that, we can keep other data related to the survey also saved in the database. When transforming the JSON  to other formats, having these type of data with the json helps to avoid unnecessary pre-parsing.

**Comment by tsv2013** [comment]
I guess you should play with the [clearInvisibleValues](https://surveyjs.io/Documentation/Library/?id=surveymodel#clearInvisibleValues) option of the survey object.

P.S. Could you please post the questions about the library in the corresponding repo - https://github.com/surveyjs/surveyjs
