### ISSUE TITLE
Example  for addProperty in Angular 6

### ISSUE THREAD

**Issue by NikolaMalezanoski** [surveyjs/editor#365]
### Are you requesting a feature, reporting a bug or ask a question?
- Question / Bug

Please, Is it possible for someone to post workable example fo **addProperty** in **Angular 6**

Seams like addProperty in Angular 6 version doesn't work as expected

Example
Survey.JsonObject.metaData.addProperty("survey", "description:html");
Survey.JsonObject.metaData.addProperty("questionbase", { name: "tag:number", default: 0 });

Custom Property is visible in edit question Modal or only is visible in Property Grid?

Kind Regards

**Comment by tsv2013** [comment]
SurveyJS Builder uses the KnockoutJS version of the library. That's why for the builder you should add properties to the corresponding library. You can chech the https://github.com/surveyjs/surveyjs_angular_cli/blob/master/src/app/survey.editor.component.ts file for example:

```JS
    import * as SurveyKo from "survey-knockout";

    // some other code

    SurveyKo.JsonObject.metaData.addProperty(
      "questionbase",
      "popupdescription:text"
    );
    SurveyKo.JsonObject.metaData.addProperty("page", "popupdescription:text");
```

**Comment by NikolaMalezanoski** [comment]
Thanks @tsv2013 , all work now as expected
