### ISSUE TITLE
Conditions / VisibleIf Property Editor doesn't work correctly if question name has dot '.' symbol

### ISSUE THREAD

**Issue by Ewilliams90** [surveyjs/editor#367]
### Are you requesting a feature, reporting a bug or ask a question?
Reporting bugs / requesting a feature

### What is the current behavior?

VisibleIf logic is great, however:

1. Is tied to the target questions name (as it's set at the time a condition is added), allowing for a break in the logic should the target question name later change.
2. When the target question name contains a period, the condition appears not to apply in any case

### What is the expected behavior?

1. Rules should be tied to the question "id" (or even better - optionally to a custom property like "questionId" that I've added onto our usage of the builder & library.)

I could see something like this where you specify a `visibleIfProperty` in `editorOptions`

```javascript 
new SurveyEditor.SurveyEditor("element", {
	visibleIfProperty: "questionId" // default "name"
})
```

Given the following element: 

```json
{
 "type": "radiogroup",
 "name": "What's your favorite pet?",
 "id": "sq_170",
 "questionId": "Lac8P",
 "title": "What's your favorite pet?",
 "choices": [
  { "value": "dogs", "text": "Dogs" },
  { "value": "cats", "text": "Cats" },
  { "value": "birds", "text": "Birds" }
 ]
}
```

Currently, if you created a condition against the above element, the result would be:

`{What's your favorite domesticated animal} = "cats"`

Now some work would be required to keep the current UI/UX in the editor the same (as in the drop down still shows the question name and the text editor shows the name as well but the end result in the survey JSON is:

`{sq_170} = "cats" `

or

`{Lac8P} = "cats"`

### How would you reproduce the current behavior (if this is a bug)?

Take the following JSON and try to test:

```json
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "radiogroup",
     "name": "Pick a number.",
     "title": "Pick a number.",
     "choices": [
      {
       "value": "1",
       "text": "1"
      },
      {
       "value": "2",
       "text": "2"
      },
      {
       "value": "3",
       "text": "3"
      }
     ]
    }
   ]
  },
  {
   "name": "page2",
   "elements": [
    {
     "type": "rating",
     "name": "question2"
    }
   ],
   "visibleIf": "{Pick a number.} <= \"2\""
  }
 ]
}
```

* browser: chrome
* editor version: latest

**Comment by andrewtelnov** [comment]
@Ewilliams90 @nperryEG
There is no a quick fix here. There are several classes and functions that are not aware about question object. For example condition parsers and runner. They have hash of objects and expression. For example hash of object can be as:
{ q1: "val1", q2: { q3: "val3", q4: "val4"}, q5: [{ col1: 11, col2: 12 }, { col1: 21, col2: 22 }] };
It can run expression as:
"{q1} = 'val1' or ({q2.q3} != 'val3' and {q5.length} > 1 and {q5[0].col1} > 10"
Parser create the be-tree (logical tree) based on the expression without knowing about values at all. After it creates the be-tree, it can run condition. It provides to this be-tree hash of values.
There is no way we can learn our parser to understand that {Pick a number. Please} is a one question name.
The solution is: do not use period in the name. I think the best way is to remove '.' from the name on assign. You may use the title.
Another solution is to use the valueName property. If it is not empty, then valueName property is used in the expression, for example: name: "Pick a number.", valueName: "pickNumber". Here is more about [this topic](https://surveyjs.io/Documentation/Library/?id=LibraryOverview#data).

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@Ewilliams90 @nperryEG
I have implemented the [following functionality](https://github.com/surveyjs/surveyjs/issues/1220) in the library. I found that Condition Property Editor doesn't use valueName properly. I will fix it as well.

**Comment by andrewtelnov** [comment]
@Ewilliams90 @nperryEG I have fixed the bug in the Editor as well. Unit test has been added and old one is updated.

Thank you,
Andrew
