### ISSUE TITLE
VisibleIf with questions that end with a period

### ISSUE THREAD

**Issue by nperryEG** [surveyjs/editor#368]
### Are you requesting a feature, reporting a bug or ask a question?

Bug

### What is the current behavior?

When editing a question.  When the user is configuring the VisibleIf, a choice based question (dropdown, radiogroup, etc...) that ends with a period will fail to provide its choices to the user.

#### Question with period in name
![Question with period in name](https://user-images.githubusercontent.com/38434405/42393280-ddc97da6-8123-11e8-9bed-a070da9087d1.png)
#### Question without period in name
![Question without period in name](https://user-images.githubusercontent.com/38434405/42393315-f8272568-8123-11e8-9e9d-22ccf358608c.png)

### What is the expected behavior?

I would expect that a question that ends with a period would provide the choices for the given question.

### How would you reproduce the current behavior (if this is a bug)?

Using the below survey config via the example editor here https://surveyjs.io/Survey/Builder

Add a visible if condition on either a page or question element you will notice that the choices for questions do not show up as expected. 

Example survey config
```
{
 pages: [
  {
   name: "page1",
   elements: [
    {
     type: "panel",
     name: "panel1",
     elements: [
      {
       type: "radiogroup",
       name: "Example Question Text? Select One.",
       title: "Example 1? Select One.",
       choices: [
        {
         value: "Test 1",
         text: "Test 1"
        },
        {
         value: "Test 2",
         text: "Test 2"
        },
        {
         value: "Test 3",
         text: "Test 3"
        },
        {
         value: "Test 4",
         text: "Test 4"
        }
       ]
      }
     ],
     title: "Example Panel 1"
    }
   ]
  },
  {
   name: "page2",
   elements: [
    {
     type: "panel",
     name: "panel2",
     elements: [
      {
       type: "checkbox",
       name: "Example question text 2? Select One.",
       title: "Example 2? Select One.",
       hasOther: true,
       choices: [
        {
         value: "Test1",
         text: "Test1"
        },
        {
         value: "Test2",
         text: "Test2"
        },
        {
         value: "Test3",
         text: "Test3"
        },
        {
         value: "Test4",
         text: "Test4"
        }
       ]
      }
     ],
     title: "Example Panel 2"
    }
   ]
  }
 ]
}
```

I believe this is caused by the method [here](https://github.com/surveyjs/editor/blob/308af70e29e8fbb51b2a529b05edf0c23f22cabf/src/propertyEditors/propertyConditionEditor.ts#L189) which results in the question with the period not being found. 

### Specify your versions

* browser: Chrome Version 67.0.3396.99 (Official Build)
* editor version: 1.0.30

**Comment by nperryEG** [comment]
Closely related to #367

**Comment by andrewtelnov** [comment]
@nperryEG The bug has been fixed, https://github.com/surveyjs/editor/issues/367

Thank you,
Andrew
