### ISSUE TITLE
Property Panel Dropdown not working

### ISSUE THREAD

**Issue by ACD7** [surveyjs/editor#371]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
Property Panel Dropdown at top of page does not change the the property panel to selected item.

i.e changing from question1, back to Survey properties does not work without clicking 'Survey Settings' button.

### What is the expected behavior?
Survey properties should change to the selected property when the dropdown is used.

### How would you reproduce the current behavior (if this is a bug)?
Just load any survey builder/

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjs.io/Survey/Builder/

Test code

```
your_code_here

```

### Specify your

* browser: Chrome
* editor version: 1.0.30

**Comment by tsv2013** [comment]
Thank you for the report, the bug is related to the surveyjs.io site environment. It isn't reproduced with the pure SurveyJS Builder.

**Comment by ACD7** [comment]
I am also getting the issue within my own site. I only used your site as the reference. Do you know what is causing the issue?

**Comment by tsv2013** [comment]
We don't know for a while. We are working on the issue.

**Comment by tsv2013** [comment]
The problem was related to the select2 integration. Fixed. Fix will be available in the nearest update.
