### ISSUE TITLE
Conditions (VisibleIf) - notcontains doesn't work for strings/substrings

### ISSUE THREAD

**Issue by nperryEG** [surveyjs/editor#372]
### Are you requesting a feature, reporting a bug or ask a question?

bug

### What is the current behavior?

When picking the last answer for question one "Question 1 Answer 4 test", page 3 is still visible in the example provided below.

### What is the expected behavior?

I would expect page 3 to not be visible when selecting an answer on question that contains 'test'

### How would you reproduce the current behavior (if this is a bug)?

see below survey config

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjs.io/Survey/Builder/

survey config
```
{
 pages: [
  {
   name: "page1",
   elements: [
    {
     type: "panel",
     name: "panel1",
     elements: [
      {
       type: "checkbox",
       name: "Question 1",
       title: "Question 1",
       choices: [
        "Question 1 Answer 1",
        "Question 1 Answer 2",
        "Question 1 Answer 3",
        {
         value: "Question 1 Answer 4 test",
         text: "Question 1 Answer 4 test"
        }
       ]
      }
     ],
     title: "Tell us about yourself"
    }
   ]
  },
  {
   name: "page2",
   elements: [
    {
     type: "panel",
     name: "panel2",
     elements: [
      {
       type: "radiogroup",
       name: "Question 2",
       title: "Question 2",
       choices: [
        "Question 2 Answer 1",
        "Question 2 Answer 2",
        "Question 2 Answer 3",
        "Question 2 Answer 4"
       ]
      }
     ],
     title: "Tell us about yourself"
    }
   ]
  },
  {
   name: "page3",
   elements: [
    {
     type: "panel",
     name: "panel3",
     elements: [
      {
       type: "checkbox",
       name: "Question 3",
       visibleIf: "{Question 1} notcontains \"test\" and {Question 2} <> [\"Question 2 Answer 4\"]",
       title: "Question 3",
       choices: [
        "Question 3 Answer 1",
        "Question 3 Answer 2",
        "Question 3 Answer 3",
        "Question 3 Answer 4"
       ]
      }
     ],
     title: "Tell us about yourself"
    }
   ]
  },
  {
   name: "page4",
   elements: [
    {
     type: "panel",
     name: "panel4",
     elements: [
      {
       type: "checkbox",
       name: "Question 4",
       visibleIf: "{Question 1} notcontains \"test\" and {Question 2} = [\"Question 2 Answer 4\"]",
       title: "Question 4",
       choices: [
        "Question 4 Answer 1",
        "Question 4 Answer 2",
        "Question 4 Answer 3"
       ]
      }
     ],
     visibleIf: "{Question 1} notcontains \"test\" and {Question 2} = [\"Question 2 Answer 4\"]",
     title: "Tell us about yourself"
    }
   ]
  }
 ]
}

```

### Specify your 

* browser: N/a
* editor version: 1.0.30

**Comment by andrewtelnov** [comment]
@nperryEG notcontains and contains is created for arrays. 
However, I think it makes sense to add this functionality to string/substring.

**Comment by andrewtelnov** [comment]
@nperryEG Everything works as expected. The issue was in your code. You were comparing radiogroup (single choice) with array.
Incorrect:
`visibleIf: "{Question 1} notcontains \"test\" and {Question 2} <> [\"Question 2 Answer 4\"]"`
correct:
`visibleIf: "{Question 1} notcontains \"test\" and {Question 2} <> \"Question 2 Answer 4\""`
Same for others expressions.

Thank you,
Andrew

**Comment by nperryEG** [comment]
@andrewtelnov I now see that the question 2 condition was incorrect but the notcontains still does not seem to work correctly. 

For example if you instead just used the following condition in place of my previous configs visibleIf for question 3/4. 

`visibleIf: "{Question 1} notcontains \"test\""`

You will see that page 3/4 will never not be visible if you pick the question 1 answer that contains 'test'. When the expected behavior is that they are no longer visible.

**Comment by andrewtelnov** [comment]
@nperryEG {Question 1} is a checkbox. You should change it to radiogroup, then it start to work. 
Your checkbox result is array of strings. notcontains in this case try to find a value in your array. You are expecting that notcontains will peform for all strings in the array.

You may still have this functionality by writting a custom function.
Here is [the example](https://plnkr.co/edit/tbSBFXiunLq8d5n18SVP?p=preview) of custom function I wrote yesterday.

Here is your [example with Question 1 as radiogroup](https://plnkr.co/edit/gnTmTmH1gL4pJ7JQOCMm?p=preview)

Thank you,
Andrew

**Comment by nperryEG** [comment]
@andrewtelnov what if the user should be allowed to select multiple choices. You are correct in that I am expecting the noncontains to perform for each choice for a checkbox. If this is not the default behavior, what is difference between equal/not equals vs contains/notcontains in the context of a question with a array of 0..n responses (checkbox or matrix(multiple choice))?

**Comment by andrewtelnov** [comment]
@nperryEG We can't implement in the way you want it. Let's say you have the following checkbox question:
`{ type: "checkbox", name: "q1", choices: ["Item1", "Item2", "Item10", "Item11"] }`
You visibleIf is: "{q1} noncontains 'Item1'"
Everybody would expect that if user select "Item10" and "Item11" then the expression should return true. However, if we implement it in your way, it would return false, since "Item1" is substring for "Item10"
 and "Item11".

Here is the difference between contain and equals. Here is two expression for the question above:
`"{q1} contains 'Item1'"` and `"{q1} = ['Item1']"`
The first expression returns true, if a user select Item1 (it doesn't matter, if he selects other items or not)
The second expression returns false, if a user seelct Item1 ONLY. If he selects Item2 as well, then the expression returns false.

I hope that makes sense.
Let me know if you need help in writting the custom function. We may include it into our built-in functions. The only problem I have is the name, `hasStrInArray({arrayValueName}, 'string')`. What do you think?

Thank you,
Andrew

**Comment by nperryEG** [comment]
@andrewtelnov 

So if you take a text based question (single input, comment, etc..) and do a notcontains/contains it works in the way I described. `{ type:  'text', name 'q1' }` and `visibleIf: "{q1} notcontains 'Item1'"` then this will infact return true as long as no substring contains 'Item1'. 

I definitely see the usage of having the behavior you describe here
>{ type: "checkbox", name: "q1", choices: ["Item1", "Item2", "Item10", "Item11"] }
and visibleIf is: "{q1} noncontains 'Item1'"
Everybody would expect that if user select "Item10" and "Item11" then the expression should return true.

I think it would make sense to add a default condition specifically for questions that can have multiple answers. The condition being for if one or more of the answer's strings contains the specified string. I think a good name for this condition could be `answercontains` or `answernotcontains`

If this is not something that you want to support by default. Is there a mechanism to add/remove conditions for say certain questions so that I could add my own conditions with their own validation method? I would like to do this because I want to enable the user building the survey to actively choose to use this condition.

For example something like this at a high level 
```
//ex: Add a condition to the base type of a question
questionBase.addCondition(exampleValidationQuestion)

// Function where i create my own custom behavior for doing the evaluation if the condition 
// These functions should always return true or false 
function AnswerContainsConditionValidation(question, answers): boolean{
     // loop through answers
             // If answer substring contains my set visibleIf return true
    // if not answer contains my set visibleIF then return false
}

```

**Comment by andrewtelnov** [comment]
@nperryEG You can override contains and noncontains operators now. We have this functionality.
It should be:
```
function yourFunction(left, right) {
 ....
 return true/false;
}
Survey.Condition.setOperator("contains", yourFunction);
```
You may look at [source code](https://github.com/surveyjs/surveyjs/blob/master/src/conditions.ts) to get better understanding. Please search for class Condition.

About adding support for new operators. They are hardcoded now. Theoretically we may create a plugin system for them, so you may add/remove operator. It may even improve the code.
Do you need this or ability to override the current operators behavior will work for you?
Right now we are suggesting to use custom functions, that were built with plug-in support from the beginning.

Thank you,
Andrew

**Comment by nperryEG** [comment]
@andrewtelnov I think this is enough for me to be able to add the conditions within our codebase for the moment. I think it would be beneficial to create a plugin system around the operators to allow developers to provide the extensibility of being able to change, remove, add conditions. It would be also nice if there was the ability to

**Comment by andrewtelnov** [comment]
@nperryEG I have added a card of refactoring operators in expression into our TODO list. It combines with cards for operators localization/alternative names.

Let me know if you need any help of solving your task.

Thank you,
Andrew
