### ISSUE TITLE
Wrong status when save fails

### ISSUE THREAD

**Issue by montrueque** [surveyjs/editor#375]
### Are you requesting a feature, reporting a bug or ask a question?

Bug

### What is the current behavior?

When saving function via AJAX using this example of the [docs](https://surveyjs.io/Documentation/Builder/) and error is thrown, the survey status is marked as saved
```
editor.saveSurveyFunc = function (saveNo, callback) {
    $.ajax({
        url: "UrlToYourWebService",
        type: "POST",
        data: {
            surveyId: yourEditUniqueSurveyI,
            surveyText : editor.text
        },
        success: function (data) {
            callback(saveNo, data.isSuccess);
        },
        error: function (xhr, ajaxOptions, thrownError) {
            callback(saveNo, false);
            alert(thrownError);
        }
    });
}
```
### What is the expected behavior?
The status next to the "Save survey" button should be "Error" instead of "Saved".

### How would you reproduce the current behavior (if this is a bug)?
I put a breakpoint in [this line of the code](https://github.com/surveyjs/editor/blob/7f18feeb9f45225ceecb98f5c55c3af777a770de/src/editor.ts#L923).

### Specify your

* browser: Chrome 67.0.3396.99
* editor version: 1.0.32

**Comment by tsv2013** [comment]
Thank you for the report. I've fixed the issue. Fix will be available in the nearest update.
