### ISSUE TITLE
Error changing checkbox/radio question to image picker

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/editor#376]
Cloned from https://github.com/surveyjs/surveyjs/issues/1232

Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug

What is the current behavior?
If you add a checkbox/radio question to the page and then change it to an image picker it throws an error.

What is the expected behavior?
Either there should be no option to change it to an image picker or it should be able to change to an image picker with no errors.

How would you reproduce the current behavior (if this is a bug)?
Provide the test code and the tested page URL (if applicable)
Tested page URL:

Test code

your_code_here

Specify your
browser:
browser version:
surveyjs platform (angular or react or jquery or knockout or vue):
surveyjs version: 1.0.32

**Comment by tsv2013** [comment]
@rabberbock It's defenitaly a bug. We'll fix it

**Comment by rabberbock** [comment]
@tsv2013  Thanks!

**Comment by tsv2013** [comment]
We've fixed the issue. Fix will be available in the nearest update
