### ISSUE TITLE
Glyphicon is not displayed in "Edit question" modal alerts

### ISSUE THREAD

**Issue by spyninja** [surveyjs/editor#377]
I found a bug in **"Edit question"** modal. The glyphicon is not displayed next to the alert message as expected when one leaves (for example) the name field empty and presses the "OK" button.

In more detail, when a new question is added, one may press the "Edit" button to open the "Edit question" modal. The first input field found in "General" tab is the "Name" field. When deleting the name and leaving the field empty, when the "OK" is pressed, it displays an alert message as expected. 

The problem seems to be that the glyphicon will not be found, to be displayed next to the message. You may try it even at your Builder example: https://surveyjs.io/Survey/Builder/

The bug exists in both **Firefox (v. 61.0)** and **Google Chrome (v. 67.0.3396.99)**.

**Note:** In my project, I can use the glyphicons outside the Survey Builder container, but not inside.

**Comment by tsv2013** [comment]
Actually we are not using glyphicon in our project. We got rid of it in favour of the SVG icons and unicode symbols. It was missed override for it. Thank you for the report. I've added unicode symbol override. Fix will be available in the nearest update, most likely tomorrow.
