### ISSUE TITLE
Ability to trigger the adding of a survey question via an external element

### ISSUE THREAD

**Issue by leksinteractive** [surveyjs/editor#378]
### Are you requesting a feature, reporting a bug or ask a question?

Question to see if there's a way to do this currently, or if there are plans to implement something like it in the future.

At the moment when building a survey the toolbox seems to be the only way to add a question to the _svd_questions_editor_ panel. I have a requirement to trigger the addition of a question from an external custom element.

To be more specific I have a custom form which should contain a standard select dropdown with a few different question types. When the user selects a question type this will trigger the addition of that question type to the survey editor which is also part of the original form (but with the toolbox hidden in this case)

I couldn't find anything in the documentation along these lines, but maybe I missed it.

Thanks,
Aleks

**Comment by andrewtelnov** [comment]
@leksinteractive There are two ways of doing it.
1) You may handle [onQuestionAdded](https://surveyjs.io/Documentation/Builder/?id=surveyeditor#onQuestionAdded) event
2) You have a toolbox item, for example a panel, with several questions in it, by using editor.toolbox.addItem function. Here is [the documentation about toolbox customization](https://surveyjs.io/Documentation/Builder/?id=Survey-Builder-Overview#toolbox)

Thank you,
Andrew

**Comment by leksinteractive** [comment]
Thanks for the quick reply @andrewtelnov.

Yeah I saw the toolbox customization example, but in my case I don't deal with the toolbox at all. Basically I need a way to trigger an event to add the question to the survey itself (not the toolbox), so triggered from an external element totally independent of any surveyjs elements.

Something like this would be ideal:

var editor = new SurveyEditor.SurveyEditor("editorElement", editorOptions);
editor.addQuestion(questionDefinitionJson); // this could be triggered via any external element or means

Hope that makes sense.

**Comment by andrewtelnov** [comment]
@leksinteractive To add a new text question, you may use the following code:
`editor.survey.currentPage.addNewQuestion("text", "myQuestionName");`

Thank you,
Andrew

**Comment by leksinteractive** [comment]
Awesome, thanks @andrewtelnov, that's what I was after 👍
