### ISSUE TITLE
Best way to find out if the survey is empty?

### ISSUE THREAD

**Issue by leksinteractive** [surveyjs/editor#381]
### Are you requesting a feature, reporting a bug or ask a question?
**Question:** What would be the best way to find out if the survey in the editor is empty?

For example when editor is first initialised there is the first page there by default, but if there have been no questions added it would be considered empty I suppose?

After initialising the editor I tried using something like `editor.survey.isEmpty`, but this seems to be always set to `false` regardless of number of questions added.

Would the only option then be to simply count the elements via `editor.survey.pages` ?

My specific use case is to do form validation to make sure there's at least one question added.

**Comment by andrewtelnov** [comment]
@leksinteractive editor.survey.getAllQuestions().length > 0 should do the trick.

Thank you,
Andrew

**Comment by leksinteractive** [comment]
Perfect, thank you @andrewtelnov.
