### ISSUE TITLE
Custom question added to toolbox isn't retaining it's name

### ISSUE THREAD

**Issue by leksinteractive** [surveyjs/editor#383]
### Are you requesting a feature, reporting a bug or ask a question?
Hi team, another question. (sorry for the barrage of questions lately)

I'm adding some custom questions to the toolbox, and these question have a 'name', 'type' and 'title' properties set as a minimum. However, when I add them to the survey and then fill out a response it seems that the 'name' value is lost. It just defaults to 'question1' etc.

Hope that makes sense, and thanks in advance for your fast responses.

**Comment by andrewtelnov** [comment]
@leksinteractive name is just a unique name inside the toolbox.
You can control a name creation by handling [onQuestionAdded event](https://surveyjs.io/Documentation/Builder/?id=surveyeditor#onQuestionAdded)

Thank you,
Andrew

**Comment by leksinteractive** [comment]
Hi @andrewtelnov ,

I have a very specific case. In our software where surveyjs is integrated we allow users to create a library of custom questions. This library stores the custom questions in surveyjs friendly format in our database, so that we can load them into the editor later, when the user wants to build a survey. They are sort of like template questions.

As part of the process when they create these questions we assign unique names to them because we actually need to do some processing on the responses later. So that's why i'm wondering if when we load these custom questions in the toolbox and we pass it this unique name, along with the other attributes, could we retain it when the user adds that question to the survey (and this will in turn make sure it comes through in the responses)

The onQuestionAdded event is only useful if we want to generate a new name at the time the question is added to the survey, but we have no way of knowing the original name that was assigned to it in our library this way.

Hope that makes sense.

Thanks,
Aleks

**Comment by andrewtelnov** [comment]
@leksinteractive I have created the [example](https://plnkr.co/edit/4LzSUW3PSI6D9Xlw4MOR)
It has question "country" and on dropping this question it would have the same question name: "country".

Thank you,
Andrew

**Comment by leksinteractive** [comment]
Gotcha, thanks @andrewtelnov
