### ISSUE TITLE
How I can add anchors to long assessment?

### ISSUE THREAD

**Issue by NafanyaVictorovna** [surveyjs/editor#386]
Hello. 
I have a question first, but it can be feature.
The question is: how I can add anchors to the assessment top if it is really long and looks like a sheet?
Current: the assessment (more 100 questions are divided to several pages by 20 questions per one) is long and it is not usability.
I want to add anchors to the top of each page, for each 5 questions, for example.

* Chrome on Windows 10
Survey JavaScript library v1.0.16

**Comment by andrewtelnov** [comment]
@NafanyaVictorovna Probably you have found the solution already.
You may add anchors by using [onAfterRenderQuestion event](https://surveyjs.io/Examples/Library/?id=survey-afterrender)

Thank you,
Andrew
