### ISSUE TITLE
Reordering pages bug

### ISSUE THREAD

**Issue by rabberbock** [surveyjs/editor#394]
###

 Are you requesting a feature, reporting a bug or ask a question?
Reporting a bug

### What is the current behavior?
When I reorder the pages  (onthe top bar) in the editor by dragging, after some time there is an error thrown in the javascript. The error prevents the onEditorChanges from being called.

Is this a surveyjs bug or sortable bug?

### How would you reproduce the current behavior (if this is a bug)?
Try reordering the pages 5-10 times.

![capture](https://user-images.githubusercontent.com/3247622/44684106-316c8c80-aa16-11e8-91a3-16c7025f76af.PNG)

Thanks,

Raffi

**Comment by andrewtelnov** [comment]
@rabberbock We have tried to reproduce the issue using the react quickstart app, but failed :(
Could you please provide more information to let us reproduce the issue?

Thank you,
Andrew

**Comment by rabberbock** [comment]
Here is a screen recording of the bug.

[Drag Error.zip](https://github.com/surveyjs/editor/files/2327923/Drag.Error.zip)

Thanks for all your help!

**Comment by dmitrykurmanov** [comment]
I am sorry but we can't reproduce the issue. Could you please try to reproduce it in other browser or on another computer (OS) ? May be the problem with one of extensions which affect to browser Drag And Drop mechanism.

**Comment by dmitrykurmanov** [comment]
same issue: https://surveyjs.answerdesk.io/ticket/details/T1052

**Comment by dmitrykurmanov** [comment]
@rabberbock thank you for the reporting

We''ve reproduced and fixed the issue. Fix will be available in the next minor update.

Problem reproduce if we have dropdown question in the first page. Thanks to Hendrik Hansmeier: https://surveyjs.answerdesk.io/ticket/details/T1052
