### ISSUE TITLE
Text strings with {varname} directives being processed in editor controls...

### ISSUE THREAD

**Issue by aachalat** [surveyjs/editor#396]
### Are you requesting a feature, reporting a bug or ask a question?

Bug?

### What is the current behavior?

Question title with text processing variables are processed when
editing survey, removing text processing directives.

Possibly occurring in other text processed strings??

### What is the expected behavior?

Do not process text strings when displaying values in input controls....

### How would you reproduce the current behavior (if this is a bug)?
 using online survey editor with the following json:
{
 pages: [
  {
   name: "page1",
   elements: [
    {
     type: "text",
     name: "question1"
    },
    {
     type: "text",
     name: "question2",
     title: "{question1} test"
    }
   ]
  }
 ]
}

Question 2's title is reduced to " test" in the editor, loosing the {question1} processing directive.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:  latest chrome and firefox browsers
* editor version: 1.0.41

**Comment by andrewtelnov** [comment]
@aachalat Yes, it is a bug. I have added a unit test and fixed it.
The fix will be available in the next minor update, next week.

Thank you,
Andrew

**Comment by aachalat** [comment]
That was fast! Thanks!
