### ISSUE TITLE
h5.title_editable input wiggles while typing characters

### ISSUE THREAD

**Issue by andrewhartwig** [surveyjs/editor#400]
### Are you requesting a feature, reporting a bug or ask a question?

Reporting a bug

### What is the current behavior?

When inputting characters, the auto-sizing input does not take into account the size of the characters.

### What is the expected behavior?

When inputting characters, the auto-sizing input should take into account the size of the characters, and regardless of input, should not wiggle.

### How would you reproduce the current behavior (if this is a bug)?

https://surveyjs.io/Survey/Builder/

In the builder, edit anything that is a 'click-to-edit' text field. 

Input a string of `i`'s and you'll see that the input works as expected.
Input a string of `w`'s and you'll see the text jumble around and get hidden.

### Specify your

* browser: Chrome, mac Version 68.0.3440.106 (Official Build) (64-bit)
* editor version: Whatever is hosted

**Comment by andrewhartwig** [comment]
I wouldn't mind offering a PR but I am completely unfamiliar with TS and knockout, and in our project I'm using the react-editor. If you could point me in the right direction I'd take a gander!

**Comment by andrewhartwig** [comment]
Yeah those, they wiggle around and don't size properly when typing larger characters `w` vs smaller characters `i`

**Comment by dmitrykurmanov** [comment]
@andrewhartwig Thank you for the feedback. We've found the problem:

```js
function resizeInput(target) {
  target.size = target.value.length || 5;
}
```

It looks like this works bad in case of non monospaced fonts. We will think how to improve this behaviour.

**Comment by andrewhartwig** [comment]
using the `measureText` method on a canvas' `getContext("2d")` has been proven to be successful for me, though it may get difficult if someone themes/changes the font they're using. (Which wouldn't be the case for me)

```javascript
/**
 * Uses canvas.measureText to compute and return the width of the given text of given font in pixels.
 * 
 * @param {String} text The text to be rendered.
 * @param {String} font The css font descriptor that text is to be rendered with (e.g. "bold 14px verdana").
 * 
 * @see https://stackoverflow.com/questions/118241/calculate-text-width-with-javascript/21015393#21015393
 */
function getTextWidth(text, font) {
    // re-use canvas object for better performance
    var canvas = getTextWidth.canvas || (getTextWidth.canvas = document.createElement("canvas"));
    var context = canvas.getContext("2d");
    context.font = font;
    var metrics = context.measureText(text);
    return metrics.width;
}

console.log(getTextWidth("hello there!", "bold 12pt arial"));  // close to 86
```

Taken from https://stackoverflow.com/questions/118241/calculate-text-width-with-javascript
