### ISSUE TITLE
Validation alerts

### ISSUE THREAD

**Issue by leksinteractive** [surveyjs/editor#403]
Hi @andrewtelnov ,

Quick question regarding the above validation logic.

I'm trying out the first code snippet you posted here: https://github.com/surveyjs/editor/issues/350#issuecomment-395150677

Functionally it works, but i'm getting an additional alert showing up. Here's the plunkr: https://plnkr.co/edit/ScFTOsC1RUxoTxDtYaiU?p=preview

![screen shot 2018-09-06 at 5 18 30 pm](https://user-images.githubusercontent.com/3906239/45148107-19a4bd80-b1f9-11e8-8d35-932ce32c7797.png)

Do you know if there's a way to either:
- Hide the alert at the very top above the options, as it doesn't display a message
- Or hide the alerts on each of the options fields but only show the single alert at the top, with the specified message and not blank obviously (preferred option, because there's more space for the message text)

Many thanks,
Aleks

**Comment by andrewtelnov** [comment]
@leksinteractive I will have to add one more property to onPropertyValidationCustomError, like showFirstErrorOnly, or something like this. I will finish the functionality I am currently working on and come back to this issue.
Additionally, the tab with an error should be expanded. User may not understand why "OK" doesn't work.

Thank you,
Andrew

**Comment by leksinteractive** [comment]
Thanks for the quick response @andrewtelnov - looking forward to it.

**Comment by andrewtelnov** [comment]
@leksinteractive It is fixed and the tab with error will be expanded.

Thank you,
Andrew

**Comment by leksinteractive** [comment]
@andrewtelnov you are too quick :) thank you.

Can I sneak in one more question before closing the issue. Is it possible to somehow activate and display the title field for the html question type? I can add it and it works in the question edit modal but I'm wondering if it's possible to make the title visible in the panel itself.

![screen shot 2018-09-08 at 4 08 20 pm](https://user-images.githubusercontent.com/3906239/45251975-c14cf780-b381-11e8-873e-ac99d06a41ef.png)

This is what I tried, but this just adds it in the modal. 
(I was hoping the second line would make it show up but no luck)

```
SurveyKo.JsonObject.metaData.addProperty('html', { name: 'title', default: 'Title test' });
SurveyKo.JsonObject.metaData.findProperty('html', 'title').visible = true;
```

**Comment by andrewtelnov** [comment]
@leksinteractive Let's create a different issue and discuss it there. Why do you need a title property for html question. I am thinking about some refactoring, remove questionbase from where html question is derived. questionbase doesn't have value and title. Anyway this issue has nothing to do with validation alerts :)

Thank you,
Andrew
