### ISSUE TITLE
Validation for unique option values

### ISSUE THREAD

**Issue by leksinteractive** [surveyjs/editor#404]
Hi again @andrewtelnov ,

Question: How would you implement validation to make sure that each value in the options is unique?

It seems onPropertyValidationCustomError is called individually for each option (and option field), so there isn't a way to evaluate the options for duplicates in an obvious/grouped way. If you have any ideas on this it would be much appreciated.

I imagine this is a common scenario because if we let the user enter the same value more than once, we are not able to distinguish the exact value the user has selected when filling out the survey. eg. we get the responses in the format { value: answer }, so there's no way to know which 'value' was selected if there's more than 1 occurrence of it.

Thanks again!

**Comment by andrewtelnov** [comment]
@leksinteractive Yes, I will think about implementing this functionality as well. I will be back to this issue as well.

**Comment by leksinteractive** [comment]
Thanks for the quick response @andrewtelnov , I appreciate it.

**Comment by andrewtelnov** [comment]
@leksinteractive The following code will work from the next version:
```
editor.onPropertyValidationCustomError.add(function (editor, options) {
    if (options.propertyName !== "choices") return;
    var items = options.value;
    if (!items || !Array.isArray(items)) return;
    var hash = {};
    for (var i = 0; i < items.length; i++) {
        var val = !!items[i].value ? items[i].value : items[i];
        if (!val) continue;
        if (hash[val]) {
            options.error =
                "The value '" + val + "' is not unique. Please correct it";
            return;
        }
        hash[val] = 1;
    }
});    
```

Thank you,
Andrew

**Comment by NikolaMalezanoski** [comment]
Thanks @andrewtelnov 
This code work for Checkbox...
