### ISSUE TITLE
Javascript error when adding JQuery version to page.

### ISSUE THREAD

**Issue by DouglasHammon** [surveyjs/editor#406]
### Are you requesting a feature, reporting a bug or ask a question?
Bug / Question

### What is the current behavior?
When adding script tags to include JQuery of survey and surveyeditor I see javascript error in the console.
Error:
```
Uncaught TypeError: Cannot read property 'options' of undefined
    at Object.<anonymous> (VM2650 surveyeditor.min.js:12)
    at t (VM2650 surveyeditor.min.js:7)
    at Object.<anonymous> (VM2650 surveyeditor.min.js:12)
    at t (VM2650 surveyeditor.min.js:7)
    at VM2650 surveyeditor.min.js:7
    at VM2650 surveyeditor.min.js:7
    at VM2650 surveyeditor.min.js:7
    at VM2650 surveyeditor.min.js:7
```
### What is the expected behavior?
No javascript error

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: http://plnkr.co/edit/sXCyXRjvKdK7JXu1wEqT?p=preview

Test code

```
<!DOCTYPE html>
<html>
<head>
   <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <link href="https://surveyjs.azureedge.net/1.0.42/surveyeditor.css" type="text/css" rel="stylesheet" />
  <link rel="stylesheet" href="style.css">
  <script src="script.js"></script>
</head>
<body>
  <h1>Hello Plunker!</h1>
  <script src="https://surveyjs.azureedge.net/1.0.42/survey.jquery.min.js"></script>
  <script src="https://surveyjs.azureedge.net/1.0.42/surveyeditor.min.js"></script>
</body>
</html>
```
### Specify your

* browser: Chrome

**Comment by DouglasHammon** [comment]
@andrewtelnov Ok. Didn't realize that. I'm creating a single page app using Aurelia.. don't really want to include knockout. 

Thanks for the info.
-Douglas

**Comment by dmitrykurmanov** [comment]
@DouglasHammon thank you for the interest.

If I understand you correctly you will not use SurveyJS Builder because of knokcoutjs dependency.
Is the problem in KnockoutJS size? 

Could you please tell, what if SurveyJS Builder were created in pure JavaScript. Would you use it?

**Comment by DouglasHammon** [comment]
Hi @dmitrykurmanov,

Correct. I don't want to include KnockoutJS because of the size. For now, I have added KnockoutJS to my project so I can test SurveyJS, but it would be really nice if I didn't need to include this dependency. 

A possible work around is to host the builder in a iframe, and only include the knockoutjs dependency on that page (separate from the rest of the SPA).  Do you think that would work fine? We're storing the template JSON in our application database, not the SurveyJs Service. 

Thanks.

**Comment by dmitrykurmanov** [comment]
@DouglasHammon Thank you for the clarification. We will discuss it with the team. 

As for iFrame it would work, because of the Builder is just js library. Theoretically it will work everywhere in the web. But if you care about the Builder size user need to load js files anyway in the iFrame or not.

**Comment by tsv2013** [comment]
@DouglasHammon SurveyJS Builder is built on top of the KnockoutJS and will not work without it. Our customers are using SurveyJS Builder with different platforms - vanilla JS, jQuery-based apps, ReactJS, Angular of different versions and ReactJS. They have not reported any compatibility problems. If you've got any please open a new issue and we'll investigate it and will try to solve.
