### ISSUE TITLE
The navigator button between tab pages doesn't work

### ISSUE THREAD

**Issue by qav-gabriela-castro** [surveyjs/editor#416]
### Are you requesting a feature, reporting a bug or ask a question?

a bug

### What is the current behavior?
The navigator button between tab pages doesn't work. It returns that error:

Uncaught TypeError: Cannot read property 'element' of undefined
    at PagesEditor.moveLeft (surveyeditor.js:15963)
    at HTMLDivElement.element.onclick (surveyeditor.js:1319)

### How would you reproduce the current behavior (if this is a bug)?

Go to the survey builder : https://surveyjs.io/Survey/Builder/ ;
Add new pages and try to scroll through them

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version: 1.0.45

**Comment by dmitrykurmanov** [comment]
We've fixed the problem. Fix will be available in the next update.
