### ISSUE TITLE
Support dynamic choices for properties

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/editor#418]
If the property.choices depends on other property value then some fancy code is requried. Here is the [current example](https://embed.plnkr.co/l01zarPdpBWRiqPW4Kat/)
Additionally, it is impossible to make a dynamic property.choices if its depends on a parent object. For example dropdown_question.choices (itemvalue) depends on dropdown_question.someproperty or matrix_question.columns (matrix column) on dropdown_question.someproperty.
Ideally, the code should look as:
```
Survey.JsonObject.metaData.addProperty("question", {name: "targetEntity", choices: ["","Account", "Developement"]});
Survey.JsonObject.metaData.addProperty("question", {name: "targetField", isDynamicChoices: true, choices: function(obj){
 return getChoicesByEntity(obj)
}});
Survey.JsonObject.metaData.addProperty("itemvalue", {name: "targetField", isDynamicChoices: true, choices: function(obj){
 return getChoicesByEntity(!!obj ? obj.object : null);
}});

function getChoicesByEntity(obj) {
   var entity = !!obj ? obj.targetEntity : null;
    var choices = [];
    if(!entity) return choices;
    choices.push({value: null});
    choices.push({value: entity + " 1", text: entity + " 1"});
    choices.push({value: entity + " 2", text: entity + " 2"});
    return choices;
}

```

**Comment by lady3bean** [comment]
Belated thanks for the prompt response! 

Would you kindly be able to provide an example of using the isDynamicChoices in a plunkr as well please? I've tried implementing the example code you shared above, but so far I haven't been able to populate either the targetField question property or a targetField item value property based on the target Entity values using hasDynamicChoices. My example built on the old one is here -- https://plnkr.co/edit/mXtCaJ7Ez3LVbxoKneJs?p=preview.
