### ISSUE TITLE
Is it possible to get the number of columns in onMatrixColumnAdded event?

### ISSUE THREAD

**Issue by leksinteractive** [surveyjs/editor#419]
Hi team,

I am adding some functionality via the `onItemValueAdded` and `onMatrixColumnAdded` events. I noticed that in the `onItemValueAdded` event we can access the list of `itemValues` like so, which is great:

```
var editor = new SurveyEditor.SurveyEditor("editorElement", editorOptions);

editor.onItemValueAdded.add(function(sender, options) {
    console.log(options.itemValues);
});
```

Is it possible to access the list of columns in a similar way when using `onMatrixColumnAdded`? I can only see the `newColumn` property in the `options`, but I need to determine the number of columns. I tried accessing it via the `sender` parameter, and I can do it partially, however the value of this parameter doesn't get updated as new columns are added which is not ideal.

Regards,
Aleks

**Comment by andrewtelnov** [comment]
@leksinteractive I did not find a way to do it. I have added two properties into options:
```
   * <br/> options.matrix a matrix question where column is located, matrix.columns.
   * <br/> options.columns editable columns objects. They can be different from options.matrix.columns. options.columns and options.matrix.columns are equal after user press Apply or Cancel and options.columns will be set to options.matrix.columns or reset to initial state.
```
Here is the example:
```
        editor.onMatrixColumnAdded.add(function (editor, options) {
            options.newColumn.name = 'col' + options.columns.length.toString();
        });
```
It will be avaible in the next minor, hopefully on Tuesday.

Thank you,
Andrew

**Comment by leksinteractive** [comment]
Perfect, thanks very much @andrewtelnov 👍
