### ISSUE TITLE
Matrix (multiple choice) freeze browser when  edit and save

### ISSUE THREAD

**Issue by NikolaMalezanoski** [surveyjs/editor#420]
### Are you requesting a feature, reporting a bug or ask a question?
BUG

### What is the current behavior?

When I add Matrix (multiple choice), edit, add the column and save browser frize and got console log error message 

![matrix](https://user-images.githubusercontent.com/10244738/46399451-58f7f880-c72a-11e8-8a13-ee6e073960c4.gif)

**Comment by NikolaMalezanoski** [comment]
This happens after I update to version 1.0.47

**Comment by dmitrykurmanov** [comment]
Thank you! We will fix it ASAP.

**Comment by dmitrykurmanov** [comment]
@NikolaMalezanoski  we've fixed the bug via the https://github.com/surveyjs/editor/commit/b61f0031ef00fb67cdf63e252bed0cf7494e680c. Fix will be available in the minor update (most likely today)
