### ISSUE TITLE
Switches to the first page when add custom question

### ISSUE THREAD

**Issue by Polous-Sergey** [surveyjs/editor#424]
### Are you requesting a feature, reporting a bug or ask a question?

question

I need to add pre-defined questions to the page.
When I have many pages and I try to add a question to a non-front page, the current page switches to the first page.
How can i resolve this problem?
Maybe there is another way to add questions?

#### My code:

var editor = new SurveyEditor.SurveyEditor("editor", {});

var test = {
        "type": "text",
        "name": "test",
        "title": "What do you want?",
        "placeHolder": "money"
    };

    var add = function () {
        var json = JSON.parse(editor.text);

        var pageIndex = json.pages.findIndex(function (item) {
            return item.name === editor.survey.currentPage.name;
        });

        if(!json.pages[pageIndex].elements){
            json.pages[pageIndex].elements = [];
        }

        json.pages[pageIndex].elements.push(test);
        editor.text = JSON.stringify(json);
    }

**Comment by andrewtelnov** [comment]
@Polous-Sergey In theory the following code should work: 
`editor.survey.selectedElement = editor.survey.getPageByName(savedPagedName);`
Unfortunately, the page tab is not changed. I will work on the fix.

Thank you,
Andrew

**Comment by Polous-Sergey** [comment]
Thanks, it works

`var test = {
        "type": "text",
        "name": "test",
        "title": "What do you want?",
        "placeHolder": "money"
    };

    var name = '';
    
    var add = function () {
        name = editor.survey.currentPage.name;
        var json = JSON.parse(editor.text);
        var pageIndex = json.pages.findIndex(function (item) {
            return item.name === editor.survey.currentPage.name;
        });

        if(!json.pages[pageIndex].elements){
            json.pages[pageIndex].elements = [];
        }

        json.pages[pageIndex].elements.push(test);
        editor.text = JSON.stringify(json);
        editor.survey.selectedElement = editor.survey.getPageByName(name);
    }`

**Comment by andrewtelnov** [comment]
@Polous-Sergey In fact this code is working 
`editor.survey.selectedElement = editor.survey.getPageByName(savedPagedName);`.
Here is [the example](https://plnkr.co/edit/6NG1B9DXUvj4Wtebd1DE?p=preview)
The following code doesn't work 
`editor.survey.selectedElement = editor.survey.getQuestionByName('question3');`
It will be work from the next update.

Thank you,
Andrew
