### ISSUE TITLE
Add custom properties

### ISSUE THREAD

**Issue by Polous-Sergey** [surveyjs/editor#425]
### Are you requesting a feature, reporting a bug or ask a question?
Question, but maybe a bug.

https://surveyjs.io/Examples/Builder?id=addproperties&theme=default
On this example added properties, but i can't see the result on page.
How can I add custom properties?

**Comment by tsv2013** [comment]
You can add any element to a survey, or select page or survey and you will see the `tag` property in the property grid on the right side. This is the added custom property.

**Comment by tsv2013** [comment]
Sure.
This is the code:
```JS
SurveyEditor.SurveyQuestionEditorDefinition.definition.question.properties.push("tag");
```
Here is the working sample - https://plnkr.co/edit/a0QqbC9uPnYQb9n1EK8n?p=preview

**Comment by Polous-Sergey** [comment]
cool thanks
