### ISSUE TITLE
triggers for paneldynamic

### ISSUE THREAD

**Issue by sidhuswaroop01** [surveyjs/editor#426]
### Are you requesting a feature, reporting a bug or ask a question?
Asking a question

### What is the current behavior?
I can able to call trigger method using runExpression for all elements except the elements inside the paneldynamic
{
                type: "runexpression",
                expression: "{panel.contact} notempty or {panel.contact} empty",
                runExpression: "setContactValues({panel.contact}, 'panel.contact_name','panel.contact_phone','panel.contact_email'"
              }

### What is the expected behavior?
Unable to run expression

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code
//TriggerMethod setContactValues
    Survey.FunctionFactory.Instance.register("setContactValues", setContactValues);

    function setContactValues(params) {
      console.log("I'm calling");
      if (params.length < 4)
        return;
      let selectedCnt = params[0];
      let name = params[1];
      let phone = params[2];
      let email = params[3];
      console.log(name,phone,email,selectedCnt);
      if (!selectedCnt) {
        survey.clearValue(name);
        survey.clearValue(phone);
        survey.clearValue(email);
        return;
      }
      let values = selectedCnt.split(":");
      survey.setValue(name, values[0]);
      survey.setValue(phone, values[1]);
      survey.setValue(email, values[2]);
    }
```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by tsv2013** [comment]
@sidhuswaroop01 I think this more related to the SurveyJS Library - https://github.com/surveyjs/surveyjs/issues/1380
