### ISSUE TITLE
Unable to save empty multipletext question

### ISSUE THREAD

**Issue by schoolmeister** [surveyjs/editor#428]
### Are you requesting a feature, reporting a bug or ask a question?
Reporting a bug

### What is the current behavior?
Once the multipletext question is saved as empty, trying to save it again (with or without items) produces an error.

### How would you reproduce the current behavior (if this is a bug)?
1. Remove all items from "Multiple Text" question. (either through the UI or by editing the JSON)
2. Save
3. Re-add item through the UI.
4. Save -> Unable to save: "Please enter a value" error message

Ghetto fix: manually re-add at least one choice through the JSON editor

Just to be sure, I made a quick screen cap to show the process https://streamable.com/1bd4j.

#### Provide the test code and the tested page URL (if applicable)
Tested page URL: https://surveyjs.io/Survey/Builder/

### Specify your
* browser: Google Chrome, Version 69.0.3497.100 (Official Build) (64-bit)
* editor version: the latest one, I reckon?

**Comment by andrewtelnov** [comment]
@schoolmeister We will work on the fix.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@schoolmeister A unit test has been added and bug is fixed now. The fix will be available in the next minor update, very likely today.
Additionally, it is impossible to remove all items in the editor and save it.

Thank you,
Andrew
