### ISSUE TITLE
Locale (medium) bug when using the "multipletext" question

### ISSUE THREAD

**Issue by lukasmedia** [surveyjs/editor#432]
### Are you requesting a feature, reporting a bug or ask a question?

(Locale) bug

### What is the current behavior?

If i use the builder (https://surveyjs.io/Survey/Builder/) to create a multipletext question, i fill in a name and some items. 
After that in the survey settings i change the locale to another language and i start edit the "items" popup to change the titles. Check json -> translations are there -> OK.
(allthough i experienced some weird behaviour with storing the translated text, but i cannot reproduce).

1. when translated and i switch language the titles dont change, but the name does. This is confusing.
2. its not possible to translate correctAnswer & defaultValue, or maybe this is by design but i dont know why.

Maybe this is related: https://github.com/surveyjs/widgets/issues/86 ?

### What is the expected behavior?

1. if locale changes title values displayed in de builder should change also;
2. correctAnswer and defaultValue should also be translated (?)

### How would you reproduce the current behavior (if this is a bug)?

Seems like a bug to me

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjs.io/Survey/Builder/

Test code: https://pastebin.com/raw/y05VBZ2s

**Comment by andrewtelnov** [comment]
@lukasmedia I have fixed the first issue. It was definately a bug. 
About the second issue. To be honest, I do not know how to implement this functionality yet. I understand that results may be different in different locales. Let me think about it and ping me please in a week, if I don't comback.
If you are hosting Builder on your machine, I would suggest you to set showTranslationTab option to true. We will publish examples on the next week. This tab allows to edit all localizable strings in one place.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@lukasmedia Let's discuss the second issue in the [separate thread](https://github.com/surveyjs/editor/issues/434)

Thank you,
Andrew
