### ISSUE TITLE
Autocomplete widget not working

### ISSUE THREAD

**Issue by lady3bean** [surveyjs/editor#441]
### Are you requesting a feature, reporting a bug or ask a question?
Reporting a bug

### What is the current behavior?
In the example of using the autocomplete widget here: https://surveyjs.io/Examples/Library/?id=custom-widget-autocomplete&platform=Reactjs, no autocomplete functionality is apparent, and there are some errors in the console. This is the same if looking at it with a different framework option and in the Plunkr example.

In my own use, using the surveyjs-widgets repo in React, I can get other widgets such as the signature pad to work, but autocomplete is not working, though there are no errors.

### What is the expected behavior?
Error-free functionality of the autocomplete widget.

Also, another person opened up a feature request for autocomplete on dropdowns - https://github.com/surveyjs/surveyjs/issues/521. Is there a way to combine dropdowns with autocomplete? It seems awkward to do autocomplete with text fields that have choices assigned to them, since you can't add choices to the text type questions in the UI, and can only do so through custom JS. For my purposes, it would be best if users had a dropdown where they could click on choices as well as the ability to do an autocomplete search within the choices, so if there's any way to do that I'd love to know.

### How would you reproduce the current behavior (if this is a bug)?
Type in the input box
https://surveyjs.io/Examples/Library/?id=custom-widget-autocomplete&platform=Reactjs

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjs.io/Examples/Library/?id=custom-widget-autocomplete&platform=Reactjs

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by tsv2013** [comment]
@lady3bean 
This question is related to the custom widgets repo - https://github.com/surveyjs/widgets/
Let's discuss it here - https://github.com/surveyjs/widgets/issues/89
