### ISSUE TITLE
Clicking out of a title-adorner field sometimes causes title to remain hidden

### ISSUE THREAD

**Issue by chambleton** [surveyjs/editor#442]
### Are you requesting a feature, reporting a bug or ask a question?

Reporting a bug

### What is the current behavior?

Start editing a question title or choice item text (just change the text a little) then click outside that title somewhere. Sometimes the title disappears and cannot be re-displayed until saving the question properties again.

### What is the expected behavior?

It's expected that the edits should either be saved or cancelled, but not that the title/item is hidden.

### How would you reproduce the current behavior (if this is a bug)?

Start editing a question title or choice item text (just change the text a little) then click outside that title somewhere. Sometimes the title disappears and cannot be re-displayed until saving the question properties again.

#### Provide the test code and the tested page URL (if applicable)

I traced this to a bug in the title-editor.ts in which the element.style["oldDisplay"] is undefined; the fix is below:

```
  hideEditor = () => {
    this.isEditing(false);
    this.forNeibours(element => {
//  element.style.display = element.style["oldDisplay"] (current code)
      element.style.display = element.style["oldDisplay"] ?  element.style["oldDisplay"] : "";
    });
  };

```

### Specify your

* browser: chrome 
* editor version: v1.0.16 or greater

**Comment by dmitrykurmanov** [comment]
I've reproduced the issue

**Comment by dmitrykurmanov** [comment]
@chambleton hello!  Thank you for the reporting and suggestions. We've fixed the issue via using the dataset instead of custom style. We thinks that it is more correct way to do it.

Fix will be available in the next minor update.
