### ISSUE TITLE
How to get the other survey questions in a custom widget?

### ISSUE THREAD

**Issue by schoolmeister** [surveyjs/editor#443]
### Are you requesting a feature, reporting a bug or ask a question?
Asking a question.

### Context
I'm building an app that contains some custom widgets. One of the widgets is a small board game the participants have to play, this widget has type "game". After playing this game the participant should receive feedback. To make the options and position of this feedback in the survey fairly customizable to the user of the survey editor, I'm creating a second widget for this feedback.

Since this feedback is dependent upon the result of a game I'd like to add a dropdown property to the feedback widget containing the names of the earlier questions of the custom widget type "game". This way the user can couple the feedback to a specific game question. 

### Problem
However, this means I'd need to somehow get a list of all questions in the editor in the `activatedByChanged(activatedBy)` function. Any clue how I could achieve this, if this is even possible?

### Progress
I've been able to find the questions in the `afterRender(question, element)` with `question.survey.getAllQuestions();` but so far I've been unable to achieve the same in the other function.

Note that I don't have any experience at all with Knockout, so maybe the solution is really obvious, I just can't see it.

**Comment by andrewtelnov** [comment]
@schoolmeister activatedByChanged is called before survey is loading/running, during custom widget registration in the collection. You can't get survey instance in this function. And yes, afterRender is the correct place to get it.
Again, the property has to be added before survey or Editor is created. You may dynamically show/hide it, by using [editor.onCanShowProperty](https://surveyjs.io/Documentation/Builder/?id=surveyeditor#onCanShowProperty) event.

Thank you,
Andrew

**Comment by schoolmeister** [comment]
Thanks for clarifying, that explains why I wasn't able to get that list. I managed to solve my issue by using the `onCanShowProperty` after I create the editor.

I've got one more question though, is it possible to listen for changes in the value of questions?

**Comment by andrewtelnov** [comment]
@schoolmeister for most cases [onPropertyValueChanging](https://surveyjs.io/Documentation/Builder/?id=surveyeditor#onPropertyValueChanging) should work for you.

Thank you,
Andrew
