### ISSUE TITLE
visibility flag editor helper text not showing 

### ISSUE THREAD

**Issue by rajan-g** [surveyjs/editor#46]
Hi Andrewtelnov,
     I was tried with surveyjs editor, it is really amazing. While I am integrated in my local machine visibility editor helper text not showing could you help me ? I just followed your example code. any special configuration I need to do ?

**Comment by andrewtelnov** [comment]
@rajan-g There is nothing any specific. You may look at the html code of the following page: http://surveyjs.org/builder/
