### ISSUE TITLE
is there possible to get current rendered question name in an page not all question name.?

### ISSUE THREAD

**Issue by myselfdesai** [surveyjs/editor#461]
### Are you requesting a feature, reporting a bug or ask a question?

asking a question 

### What is the current behavior?

I can get the all questions using getAllQuestions()

### What is the expected behavior?

Its a question is it possible to get the question names in currently rendered question page.
survey.getQuestionByName(question_name);

i wanted to pass question_name as current rendered page question name.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by myselfdesai** [comment]
I have solved it using customized technique link [https://github.com/surveyjs/surveyjs/issues/1053#issuecomment-458080719](url)

**Comment by myselfdesai** [comment]
I have done it manually 
https://github.com/surveyjs/surveyjs/issues/1053#issuecomment-458080719

**Comment by KMDgit** [comment]
Do this : survey.currentPage.questions[0].propertyHash.name
