### ISSUE TITLE
onComplete event of surveyjs

### ISSUE THREAD

**Issue by anushasipl** [surveyjs/editor#466]
I am trying to get .onComplete event of survey but somehow I am keep getting error:

![image](https://user-images.githubusercontent.com/17494063/51960279-67f37b00-247e-11e9-8772-6d0038059526.png)

I have added this code. But this is not working and does not invoke any event:

editor.onComplete.add(function (survey, options) {
alert('in');
});

Please suggest.

**Comment by tsv2013** [comment]
The SurveyJS Editor hasn't have `onComplete` event. This is the event of a survey.

If you want to access currently edited survey in the editor you should use the [survey](https://surveyjs.io/Documentation/Builder/?id=surveyeditor#survey) property and the [onDesignerSurveyCreated](https://surveyjs.io/Documentation/Builder/?id=surveyeditor#onDesignerSurveyCreated) event.
