### ISSUE TITLE
Test survey result table view: long string overflows table

### ISSUE THREAD

**Issue by Hapcy** [surveyjs/editor#469]
### Are you requesting a feature, reporting a bug or ask a question?

Reporting a bug.

### What is the current behavior?

This bug is reproducible only in Firefox. On the Test Survey Tab if a value overflows the size of the survey result table then it doesn't get clipped and no scrollbar appears so it overflows over display value and out of the table.

Probably due to this.: https://stackoverflow.com/questions/14547722/how-to-control-overflow-of-table-cell-in-firefox

### What is the expected behavior?

It is expected to work like in chrome where a scrollbar appears.

### How would you reproduce the current behavior (if this is a bug)?

1. Open survey editor in FF.
2. Start creating a survey.
3. Add a single input.
4. Change it to "Comment".
5. Go to "Test Survey" tab.
6. Enter a long unbreakable string into the input (e.g.: a bunch of 'a's).
7. Click complete.
8. Observe that in the table view the answer value and the display value overflows their cells.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: It is reproducible in the Builder example on the official page: https://surveyjs.io/Examples/Builder/ . No extra code needed.

### Specify your

* browser: Firefox
* editor version: We use 1.0.63 but it happens on any version.

**Comment by tsv2013** [comment]
Could you specify - what exact JSON or answer causes such a behavior?

For now it looks ok for me - check the screenshot below:

![image](https://user-images.githubusercontent.com/3013415/52785065-1fd07d00-3068-11e9-81a1-1bbaf1900330.png)

**Comment by tsv2013** [comment]
I see... "Long unbreakable string". Rather synthetic case.

**Comment by tsv2013** [comment]
Fix will be available in the nearest update

**Comment by Hapcy** [comment]
Thank you for your fast response!
