### ISSUE TITLE
Other option on panel dynamic is not working

### ISSUE THREAD

**Issue by qav-gabriela-castro** [surveyjs/editor#480]
### Are you requesting a feature, reporting a bug or ask a question?
Reporting a bug

### What is the current behavior?
A question inside a panel dynamic that has a other option don't show the answer

### How would you reproduce the current behavior (if this is a bug)?
The link to reproduce the bug : [plunker](https://plnkr.co/edit/MdcoljsXQmZDIdm1adC6?p=preview)

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by andrewtelnov** [comment]
@qav-gabriela-castro Yep, we will work on the fix.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@qav-gabriela-castro I have added a unit test and fixed the issue.
We will release a new version with the fix on the next week.
You may rebuild the library from the source as described in our [readme file](https://github.com/surveyjs/surveyjs).

Thank you,
Andrew
