### ISSUE TITLE
Rendered input fields do not have easily targetable selector for testing

### ISSUE THREAD

**Issue by rubyaryat** [surveyjs/editor#481]
### Are you requesting a feature, reporting a bug or ask a question?

Question

### What is the current behavior?

Rendered input fields do not have easily targetable selector for testing (of rendered survey).
Currently having to use id attribute but may change after modify survey.
Is there a way to specify for each question a data attribute that is rendered in the resulting html input element?

### What is the expected behavior?

Ability to add a custom data attribute to each input fields (question element), e.g. 'data-cy', which would give us a targetable selector for testing. 

### How would you reproduce the current behavior (if this is a bug)?

n/a

#### Provide the test code and the tested page URL (if applicable)

Example rendering of a text type question. Note id="sq_186i" may change if modify survey, for example when adding questions. 

<input data-bind="attr: {type: question.inputType, size: question.size, id: question.inputId, placeholder: question.inputType === 'range' ? undefined : question.placeHolder, maxLength: question.getMaxLength(), 'aria-label': question.locTitle.renderedHtml}, value:question.koValue, css: question.koCss().root" type="text" size="25" id="sq_186i" placeholder="" aria-label="12)  Zip Code" class="sv_q_text_root">

**Comment by andrewtelnov** [comment]
@rubyaryat You may change the question.id to question.name for example before survey rendering.

Thank you,
Andrew

**Comment by rubyaryat** [comment]
Thanks for quick response. Unfortunately, I've not been able to find how to set the question.id to question.name for my survey. 
I'd like to do this for all questions. Any pointers to what method I need to call to accomplish this/sample code?
Thanks,
Adam

**Comment by andrewtelnov** [comment]
@rubyaryat Here is [the example](https://plnkr.co/edit/vyuQTYIjOxVzBrOBejpN?p=preview)

```
survey.getAllQuestions().forEach(function(question){
  question.id = question.name;  
});
```

Thank you,
Andrew

**Comment by rubyaryat** [comment]
That did the trick.
Thanks!
Adam
