### ISSUE TITLE
Unable to make editor toolbar have custom css for each button

### ISSUE THREAD

**Issue by vandole** [surveyjs/editor#486]
### Are you requesting a feature, reporting a bug or ask a question?
Question

### What is the current behavior?
Each toolbar button is one css class and one css class only, and if we use innerCss it  only appends the value to what is already there.

![surveyJS plunker](https://user-images.githubusercontent.com/45013707/54786660-709f3c80-4bf7-11e9-938e-a505681558e0.jpg)

### What is the expected behavior?
Be able to use  the innerCss when pushing a new toolbar item to override what is already in there to use a button secondary or button danger.

![surveyJS plunked expected](https://user-images.githubusercontent.com/45013707/54786654-6d0bb580-4bf7-11e9-8cdd-66dbd499e994.jpg)

#### Provide the test code and the tested page URL (if applicable)

https://plnkr.co/edit/aApUBRacErHvlkL78k1o?p=preview

**Comment by tsv2013** [comment]
@vandole Each toolbar button has the unique id and can be styles via a CSS rules, e.g.
```
#svd-undo > button {
  background-color: red;
}

#svd-redo > button {
  background-color: blue;
}

#svd-survey-settings > button {
  background-color: green;
}

```

Here is your updated plunker - https://plnkr.co/edit/8kpDUREQAX1AJqKza3qH?p=preview with the above mentioned rules.

**Comment by vandole** [comment]
Okay, so I'm unable to append the bootstrap? Which makes me think glyphicons are a bust as well?

**Comment by tsv2013** [comment]
Editor supports bootstrap theme by default - https://surveyjs.io/Examples/Builder?id=options&theme=bootstrap

But it's a heavily customized boorstrap.

Can you describe in a couple of words - what exactly do you want to achieve?

**Comment by vandole** [comment]
I do see that it's a heavily customized bootstrap.

One half of what I want to achieve works by being able to customize the buttons color. Now i'm trying to see what glyphicons work because I'm trying to move undo/redo into a left/right arrow. I'm trying to dig through your heavily customized bootstrap to see what specific glyphicons are naturally supported. Otherwise i'll be continuing to tinker in that plunker and implement font awesome to see if I can get where I need to go from there.

Thanks for all the help so far

**Comment by tsv2013** [comment]
You can find element by ID and add any CSS class name as you want.

**Comment by vandole** [comment]
This is working so far, but will need more modification on my end. I will make another post later with my updated plnkr incase someone else has this same issue.

**Comment by vandole** [comment]
https://plnkr.co/edit/8kpDUREQAX1AJqKza3qH?p=preview

Solution with angular 4 implementation in comments. Thanks for the help.
