### ISSUE TITLE
How to identify the type of a question from a new item toolbox?

### ISSUE THREAD

**Issue by iwollmann** [surveyjs/editor#487]
### Are you requesting a feature, reporting a bug or ask a question?
Question

### What is the current behavior?
I created the following new item at the toolbox:

`editor
    .toolbox
    .addItem({
        name: "countries",
        isCopied: true,
        iconName: "icon-dropdown",
        title: "All countries",
        json: {
            type: "dropdown",
        }
    });`

If I look at the JSON there is nothing that I can differ questions created through this item or the default dropdown item:

`"elements": [
    {
     "type": "dropdown",
     "name": "question1"
    },
    {
     "type": "dropdown",
     "name": "question2",
     "choices": [
      "item1",
      "item2",
      "item3"
     ]
    }
   ]`

### What is the expected behavior?
The JSON could have a key to define where its from.

**Comment by andrewtelnov** [comment]
@iwollmann Add a new custom property and set it into json.
Here is the code:
```
Survey
  .JsonObject
  .metaData
  .addProperty("question", {
    name: "isCustomQuestion:boolean"
  });

SurveyEditor
  .StylesManager
  .applyTheme("bootstrap");

var editorOptions = {};
var editor = new SurveyEditor.SurveyEditor("editorElement", editorOptions);

editor
    .toolbox
    .addItem({
        name: "countries",
        isCopied: true,
        iconName: "icon-default",
        title: "All countries",
        json: {
            "type": "dropdown",
            optionsCaption: "Select a country...",
            isCustomQuestion: true,
            choicesByUrl: {
                url: "https://restcountries.eu/rest/v2/all"
            }
        }
    });
```
and [working example](https://plnkr.co/edit/6s1HiyPgwr6KwMX1P6Mo?p=preview)

Thank you,
Andrew

**Comment by iwollmann** [comment]
Thanks @andrewtelnov this works!
Another question, why the number of questions is always +1 in the onQuestionAdded event?

If you add 1 question the count will be 2:
`editor.onQuestionAdded.add((editor, options) => {
            console.log(`There is ${editor.getAllQuestions().length} questions`);
        });`

**Comment by andrewtelnov** [comment]
@iwollmann It works as expected. Here is [the example](https://plnkr.co/edit/ZAdmNXhLFIyGIJtSJ7vH?p=preview).
```
editor.onQuestionAdded.add((editor, options) => {
  alert(editor.survey.getAllQuestions().length);
});
```

PS: Please create another issue in the future for a new question.

Thank you,
Andrew
