### ISSUE TITLE
How to save customized panel/element in the toolbar: Not saved in JSON

### ISSUE THREAD

**Issue by Saerdn** [surveyjs/editor#489]
### Are you requesting a feature, reporting a bug or asking a question?
Question (Bug?)

### What is the current behavior?
Within the SurveryJS Builder:
I add e.g. a panel and insert some questions. When I press the "Add to toolbox" button, the panel is added to to the toolbox. However the JSON code in the JSON editor (or when logging the editor text with
```
editor.saveSurveyFunc = function () {
    console.log(editor.text);
}; 
```
is not updated. I therefore have no chance of saving the modified panel to the toolbox.
 
### What is the expected behavior?
The added modified panel (widget?) is also part of the toolbox after reloading the page.

### Specify your

* browser: Chrome
* browser version: 73.0.3683.86 (Offizieller Build) beta (64-Bit)
* surveyjs platform (angular or react or jquery or knockout or vue): knockout
* surveyjs version: 1.0.75

**Comment by tsv2013** [comment]
If you are expecting this behaviour on the https://surveyjs.io/Survey/Builder/ page - then we can accept this as a new item in our TODO list.

If you're hosting editor in your own web application or non your web page, you can customize toolbox by your code. Here are the samples:
https://surveyjs.io/Examples/Builder/?id=toolboxcustomization&theme=bootstrap
https://surveyjs.io/Examples/Builder/?id=toolboxcategories&theme=bootstrap
Here is the documentation page - https://surveyjs.io/Documentation/Builder/?id=questiontoolbox

Here is the documentation on the corresponding event of the SurveyJS Builder model - https://surveyjs.io/Documentation/Builder/?id=surveyeditor#onCustomElementAddingIntoToolbox

**Comment by Saerdn** [comment]
> If you are expecting this behaviour on the https://surveyjs.io/Survey/Builder/ page - then we can accept this as a new item in our TODO list.

Thank you very much. I was able to read/load the (custom) toolbar widgets via `editor.toolbox.copiedJsonText` which is more than enough for my use case. It actually makes more sense to have it like this and don't mix it with the questionnaire json, isn't it?

I hope this also a feasible way in your opinion?
I you don't object we could close this issue :)

**Comment by tsv2013** [comment]
You've choosen the right approach IMO. Yes, I share your point that surveyjs JSON and editor settings shouldn't be mixed.

This is your's issue, @Saerdn and you can close it at any moment. :-) Thank you for the feedback!
