### ISSUE TITLE
Missing parameters at event onItemValueAdded

### ISSUE THREAD

**Issue by iwollmann** [surveyjs/editor#491]
### Are you requesting a feature, reporting a bug or ask a question?
Question/Bug

### What is the current behavior?
According the documentation of the onItemValueAdded event we should have all the properties available through **options.property**:
https://surveyjs.io/Documentation/Builder/?id=surveyeditor#onItemValueAdded

This is not happening, the only property that I receiving is the **propertyName**, however I can access the properties through the **options.newItem.object** option, but the problem here is that this property is only available when I'm creating the item through the popup, when I try to create an item directly from the plus icon, them I don't have this property.

![image](https://user-images.githubusercontent.com/997343/54972184-3b814a00-4f69-11e9-94b5-394cdb7be1ae.png)

The question is, how I can access the question properties of the current item?

### Provide the test code and the tested page URL (if applicable)
I'm using this sample: https://plnkr.co/edit/sYufgtubRKZccC2PKOet?p=preview

**Comment by andrewtelnov** [comment]
@iwollmann Do you want to get access to the question?

Thank you,
Andrew

**Comment by iwollmann** [comment]
Yes!
I already have access to the question, but only if I created the item through the popup:
![image](https://user-images.githubusercontent.com/997343/54995473-90db4c80-4fa5-11e9-88b9-f32eab4d7a36.png)
**Property:** _options.newItem.object_

![image](https://user-images.githubusercontent.com/997343/54995529-b23c3880-4fa5-11e9-9883-da6f0ef66ca1.png)
**Property:** _options.newItem.object_ **here this property is undefined!**

**Comment by andrewtelnov** [comment]
@iwollmann I have fixed this issue.
Please use options.obj from the next version v1.0.76. We will likely release it tomorrow.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
Here is the updated event description:
```
  /**
   * The event is called on adding a new Survey.ItemValue object. It uses as an element in choices array in Radiogroup, checkbox and dropdown questions or Matrix columns and rows properties.
   * Use this event, to set ItemValue.value and ItemValue.text properties by default or set a value to the custom property.
   * <br/> sender the survey editor object that fires the event
   * <br /> options.obj the object that contains the itemsValues array, for example selector, rating and single choice matrix questions.
   * <br/> options.propertyName  the object property Name. It can be "choices" for selector questions or rateValues for rating question or columns/rows for single choice matrix.
   * <br/> options.newItem a new created Survey.ItemValue object.
   * <br/> options.itemValues an editing Survey.ItemValue array. newItem object is not added yet into this array.
   */
  public onItemValueAdded: Survey.Event<
    (sender: SurveyEditor, options: any) => any,
    any
  > = new Survey.Event<(sender: SurveyEditor, options: any) => any, any>();

```
