### ISSUE TITLE
Is it possible to callback a isDirty value? (To warn the user about unsaved changes when leave the page)

### ISSUE THREAD

**Issue by paulocesarpcfj** [surveyjs/editor#492]
### Are you requesting a feature, reporting a bug or asking a question?
It is a question.

### What is the current behavior?
When you leave the page, the user is not warned about unsaved changes.

### What is the expected behavior?
Shows an alert, or retrieve a callback to treat unsaved changes on the Survey Builder.

### How would you reproduce the current behavior (if this is a bug)?
Just add some questions, edit a title, leave the page and everything will be lost without warnings.

### Specify your

* browser: Chrome
* browser version: Latest
* surveyjs platform (angular or react or jquery or knockout or vue): React, but it occurs on the others as well.
* surveyjs version: 1.0.75

**Comment by andrewtelnov** [comment]
@paulocesarpcfj You should warn about unsaved data whe a user is leaving the page.
Here is [the  good article](https://code-maven.com/prevent-leaving-the-page-using-plain-javascript)

And I would suggest to save the data on your server in a second after the change(s) were made, as the most cloud base services do.

Please read more about saving survey JSON [here](https://surveyjs.io/Documentation/Builder/#loadsavesurvey).

Thank you,
Andrew
SurveyJS Team

**Comment by paulocesarpcfj** [comment]
Nice! I will take a look on the JSON article. I already have a handler to warn the user, but I dont have any trigger on the SurveyJS builder to check if the form was changed or not.

Thanks!

**Comment by paulocesarpcfj** [comment]
What I did was to set the `editor.showState = true` and get the state using the DOM. It worked but I'm not sure if it's the best way to handle this. Anyway, I am closing the bug.

Thanks again!

**Comment by andrewtelnov** [comment]
@paulocesarpcfj There is [editor.onModified](https://surveyjs.io/Documentation/Builder/?id=surveyeditor#onModified) event and [editor.state](https://surveyjs.io/Documentation/Builder/?id=surveyeditor#state) property. 

I beleive that is all you need.

Thank you,
Andrew
