### ISSUE TITLE
Need help making the "name" field readonly and instead adding a unique ID to the "name" field.

### ISSUE THREAD

**Issue by chrisweconect** [surveyjs/editor#50]
Hey guys - really like Survey.js.  However: I'm having a problem.  What I need to do is:

a.)  Make the "name" text field in the form "readonly" so our users can't edit that field and... 
b.)  Set that name field to a custom, unique ID so I can match that up with the json generated when a user answers a questions.  Thanks!

**Comment by andrewtelnov** [comment]
@chrisweconect At the current moment there is no way to make the property read-only in the editor. You may only hide it. Additionally the name property can be added in the question editor as well.
Do you want to hide it completely or do you want to make it read-only?
We will have to add an event or something in the API to make it happen.

About custom name generation - I think the best solution is to have onQuestionCreating event, where a new created question will be passed, before adding it to the survey. On this event you will be able to change any question property including the name.
Will it work for you?

Thank you,
Andrew

**Comment by chrisweconect** [comment]
@andrewtelnov - Thanks for the quick reply.  We would prefer to make the "name" field read-only.  How do we create an onQuestionCreating event?  Any example of how to do that?  

Thanks,
Chris

**Comment by andrewtelnov** [comment]
@chrisweconect I will introduce onQuestionCreating event and will do an example. It will be available in the next minor. I think in about a week.
You will be able to get it early if you build the library by yourself. The instruction in the readme file.
Please follow these issues: 
https://github.com/surveyjs/editor/issues/51
https://github.com/surveyjs/editor/issues/52

Thank you,
Andrew

**Comment by chrisweconect** [comment]
@andrewtelnov - Any updates making the "name" field read-only?  Or making the "name" field a unique ID?  Looking forward to this update.

Thanks,
Chris

**Comment by andrewtelnov** [comment]
@chrisweconect I am working on it right now. I have introduced readonly attribute for JsonProperties a week ago: https://github.com/surveyjs/surveyjs/commit/929917d53d1b9a68a58acebcfe5bce14e231b3db
At the current moment I am changing the editor.
I'm fully refactoring the first ("General") tab of the Question Editor. I want to give the ability to add/remove properties and customize the layout of "General" tab. At the current moment it is hardcoded. 
I'am not sure about this week, but definitely on the next week you will have this functionality.
You will have only to include the following code:
`JsonObject.metaData.findProperty("questionbase", "name").readOnly = true;`

Thank you,
Andrew

**Comment by chrisweconect** [comment]
@andrewtelnov - Thanks!

I look forward to this new release.

Chris

**Comment by andrewtelnov** [comment]
@chrisweconect 
It is implemented:

**Comment by andrewtelnov** [comment]
@chrisweconect Here is the [demo](http://editor.surveyjs.io/examples/oncreatequestion.html)
