### ISSUE TITLE
Create API to make properties read-only

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/editor#52]
At the current moment there is no way to disable property editing in the property and question editors.

**Comment by andrewtelnov** [comment]
It is implemented. Here is the code to make a property readonly:
`Survey.JsonObject.metaData.findProperty("questionbase", "name").readOnly = true;`

**Comment by andrewtelnov** [comment]
Done. Here is the [demo](http://editor.surveyjs.io/examples/oncreatequestion.html)

**Comment by Tharuney** [comment]
demo link not working, any help to view demo in another link ?

**Comment by andrewtelnov** [comment]
@Tharuney Here is the code that makes question name property read only:
```Survey.Serializer.findProperty("question", "name").readOnly = true;```

Thank you,
Andrew
