### ISSUE TITLE
Can't get surveyJSON on page initialization

### ISSUE THREAD

**Issue by chrisweconect** [surveyjs/editor#55]
Hey,

I'm looking at this page: http://editor.surveyjs.io/examples/setsurvey.html#code

...and I can't get the editor.text from your instructions.  

First,  document.getElementById('surveyJSON') isn't in the DOM.

Second, it looks like the JSON isn't actually *in* the .svd_json_editor_area textarea.  It seems like it's added magically through Knockout somehow.  

How can I access the *initial* and *updated* JSON from this '.svd_json_editor_area' textarea?

Or, put another way, what is the easiest way to get the value of the .svd_json_editor_area textarea on page load as well as after it has been updated?  I'm trying to copy the value of that JSON generated by the editor so it can be submitted in a form wrapped around the editor.

Thanks,
Chris

**Comment by andrewtelnov** [comment]
@chrisweconect "surveyJSON" is the id of textarea element on the right side. Here is the corresponded html.
`<textarea id="surveyJSON" rows="20" style="width:100%"></textarea>`.

I am sorry, probably I doesn't understand your task.
You have to set the function to saveSurveyFunc callback. In this case the "Save" button will be shown.
On pressing the Save button, this function will be called. In this function you may set the editor.text into your hidden form input/textarea and submit the form to the server.
However, I would better create a web service and make an Ajax call to post the editor.text into the server. 

Here is the client code on the edit survey page of the dxsurvey.com. 
```
    editor.saveSurveyFunc =  function() {
        $.ajax({
            url: "/api/MySurveys/changeJson",
            type: "POST",
            data: { Id: modelData.Id, Json : editor.text }
        });
    }

```

**Comment by chrisweconect** [comment]
Thanks for your help:

1.)  I set the saveSurveyFunc and I don't see the "Save" button.
2.)  The textarea with id="surveyJSON" is nowhere in the DOM.  I think you only see that id when you use the ace editor.
3.)  I need a function on the editor object to get the JSON generated.  Can you call editor.getSurveyJSON and get the survey JSON somehow?  Is there another js function I can call to get the JSON?

Here is the code I have for the editor:

```
  :javascript
    var editorOptions = {showJSONEditorTab: true, showEmbededSurveyTab: false, questionTypes : ['text', 'comment', 'checkbox', 'dropdown', 'radiogroup',  'rating', 'matrix', 'matrixdropdown']};
    var editor = new SurveyEditor.SurveyEditor("editorElement");
    var survey = new SurveyEditor.SurveyEditor("surveyEditorContainer", editorOptions);
    editor.saveSurveyFunc =  function() {
        $.ajax({
            url: "/events/123/surveys",
            type: "POST",
            data: { Id: modelData.Id, Json : editor.text }
        });
    }
```

I'm working with Rails and would prefer to save the JSON generated by the editor in a normal form.  I just need to know how to copy the JSON generated by the editor into a hidden field OR get that JSON by calling a function on the editor so I can put it into an Ajax post.

Thanks,
Chris

**Comment by andrewtelnov** [comment]
@chrisweconect 
1) That is really strange, it works in all examples and the code is pretty straightforward:
```
    public set saveSurveyFunc(value: any) {
        this.saveSurveyFuncValue = value;
        this.koShowSaveButton(value != null);
    }
```
Where koShowSaveButton is used in the data-binding as visible: koShowSaveButton.
I have just looked at your code. You are creating two editors, and you do not set the saveSurveyFunc for an editor bound with "surveyEditorContainer" html element.

2) Chris, the html element is there, there is no magic here. Please go on this page: http://editor.surveyjs.io/examples/setsurvey.html#code. You will see the text area on the right side with title: "The current survey JSON:". It's html is `<textarea id="surveyJSON" rows="20" style="width:100%"></textarea>`.
You may go to "Show Editor" tab, add a question, click on the "Save" button and go back to "Show Code and Description" tab. You will see that the text in the "textarea" is changed.
You may vice versa change a question title in this textarea, click "Apply" button and go to "Show Editor" tab. You will see that the title will be changed as well.

3) Aha, I see the error in your code, you are trying to create two survey visual editors for some reason:
```
  :javascript
    var editorOptions = {showJSONEditorTab: true, showEmbededSurveyTab: false, questionTypes : ['text', 'comment', 'checkbox', 'dropdown', 'radiogroup',  'rating', 'matrix', 'matrixdropdown']};
      //You have two editors. You should comment one of them. It is very likely that your code should be something like this
    //var editor = new SurveyEditor.SurveyEditor("editorElement");
    //var survey = new SurveyEditor.SurveyEditor("surveyEditorContainer", editorOptions);
   //The correct line
   var editor = new SurveyEditor.SurveyEditor("surveyEditorContainer", editorOptions);
    editor.saveSurveyFunc =  function() {
        $.ajax({
            url: "/events/123/surveys",
            type: "POST",
            data: { Id: modelData.Id, Json : editor.text }
        });
    }
```
Thank you,
Andrew

**Comment by chrisweconect** [comment]
Got it. Thanks.
