### ISSUE TITLE
Hook/Callbacks on changes

### ISSUE THREAD

**Issue by hyndsite** [surveyjs/editor#58]
Are there any OnAdd/Update event hooks where a save functionality can be added intuitively when a question is added AND/OR when a question property is updated?

I see some potential hooks available in the OnBeforeAfter of the Module type question, but I am look for a place that would allow passing in function to perform save on adding a question to a survey or updating a question property.

Thanks

**Comment by andrewtelnov** [comment]
@hyndsite I have just added onModified event. I call it in protected setModified() method.
I have added onQuestionAdded event on this week. You may use it to modify a new created question.
To use them, you have to rebuild the library. Please follow the steps in the readme file.

PS: We are going to work on "auto save" feature, hopefully one the next week.

Thank you,
Andrew

**Comment by hyndsite** [comment]
Thanks @andrewtelnov
