### ISSUE TITLE
Can a survey be restored from where it was left?

### ISSUE THREAD

**Issue by svemula09** [surveyjs/editor#59]
Let's say my user answered 5 out of 10 pages. Next time he logs in can he start from 6th page instead of page 1? I am using reactJS

**Comment by andrewtelnov** [comment]
@svemula09 Sure, there is the currentPageNo property in the survey model on get and set (from 0 to visible page count - 1). 
You may store it in your database by using onCurrentPageChanged event:

```
surveyModel.onCurrentPageChanged.add(function(s, options) { 
   myPersistCurrentPageNo = s.currentPageNo; 
});

```

PS: Please create issues in https://github.com/surveyjs/surveyjs/issues for SurveyJS library.
This repo is about SurveyJS Editor.

Thank you,
Andrew
