### ISSUE TITLE
Explanation needed: how to work with localization

### ISSUE THREAD

**Issue by Teqa** [surveyjs/editor#6]
Hi Andrew, 

The latest build is fine now. But it's unclear how you want to approach the localization. 
I see a new attribute locale on survey level. But what does it do?
I expected a folder with a list of items for translation. Like 
"Please drop a question here."
"Pagex"
"Questionx"
Or even the attributes:
"visible", "readonly", etc. 
The latter is less important. The first is making the editor user friendly.

**Comment by andrewtelnov** [comment]
I was planning to add a German or Russian localization later, probably on the next week. 
However, you may already use localization at the current stage.
Take a look at this file: https://github.com/andrewtelnov/surveyjs.editor/blob/master/src/editorLocalization.ts

You will have to create your own variable, similar to "defaultStrings".
For example: 
`export var frenchStrings = { ... }`

Create a new locale:
`editorLocalization.locales["fr"] = frenchStrings;`

You may change the values or add new to defaultStrings. For example:
`defaultStrings.qt.checkbox = "My checkbox"`

PS: I do not localize the property values yet, like: true/false and "Page X" and "Question X". I will do it later. If you need it ASAP - let me know.
To localize the survey itself, please take a look at this folder: https://github.com/andrewtelnov/surveyjs/tree/master/src/localization

Thank you,
Andrew

**Comment by joshreid** [comment]
Hi @andrewtelnov is it possible to pass a Localization strings object as a survey or editor component option?

This would enable the updating of the strings from outside the src.

**Comment by andrewtelnov** [comment]
@joshreid The current approach is the following: 
http://editor.surveyjs.io/examples/localization.html#code
There is a global object and you may add your own localization and change the current locale (default is "en").
Adding a locale property or parameter in the options would make sense if you want to have two editors on the page with different locales.
Otherwise the current approach should work just fine.
Let me know if it helps.

Thank you,
Andrew

**Comment by joshreid** [comment]
Ah yes! Thanks @andrewtelnov

**Comment by xibman** [comment]
Hou have now french local for example

**Comment by andrewtelnov** [comment]
@xibman The developer version contains the french localization, thanks to you!
However the last released version, doesn't. You may wait several days, we are going to release the next update on this week (we are going to introduce the "Panel" concepts, https://github.com/surveyjs/editor/tree/panel), or build the current developer version by yourself following steps in the ReadMe file: https://github.com/surveyjs/editor

Thank you,
Andrew
