### ISSUE TITLE
please consider the following enhancements

### ISSUE THREAD

**Issue by muhfred** [surveyjs/editor#63]
First of all thank you for your awesome work. it's really appreciated. please consider the following to enhance the overall user experience.

1. In single input question:
-  The ability for a user to change the input type of “date, datetime, datetime-local” to be                 mm/dd/yyyy or dd/mm/yyyy, 24H format or AM, PM format
-In input type (week, month) the user should see the calendar viewed accordingly (weekly view, monthly view).
- 	If the user choose, email the validation to be added by default.
- 	In range type there should be values that the user can edit its min and max values.
- 	In input type “tel” the user should be able to add the format of the telephone number.
- 	Input types should be categorized.

2. The properties area should have its own scrolling.
3. A tooltip should appear at the plus sign of add page.
4. Remove dots in properties dropdown list. Survey, page, question1, question2, etc.

5. In checkbox question:
- In fast Entry remove values and values should be generated by default 1, 2, 3, 4….etc., and if values exceeded 9 the values should appear, 01 ,02, 03, 04….10
- In form entry switch value and text positions.
- Add rotating order to choices order.

6. In dropdown question add autocomplete (select2 plugin).
7. Add filter by question name or question type in the middle section of the design.
8. Add icons for questions and answers.

9. In Matrix, Single Choice question:
- Add rows along with columns in Edit.
- In matrix properties, add asc, desc, random, and rotating order.
- Add Input type text and the user should enter one answer only just like the radio button but with input text.
- Add numeric input type to matrix.

Please let me know what do you think. Thank You.

**Comment by andrewtelnov** [comment]
@muhfred There are a lot of improvements and most of them make sense. Unfortunately, some of them could not be added directly into the product, like select2, but there should be a demo, how to include this functionality into the product.
I will be back to this issue later. Some of items we will likely implement, make demos for others and will discuss the rest.

Thank you!
Andrew

**Comment by andrewtelnov** [comment]
> 4. Remove dots in properties dropdown list. Survey, page, question1, question2, etc.

```
//"..." is the default value.
SurveyEditor.SurveyObjects.intend = "  "; 

```

**Comment by andrewtelnov** [comment]
> 9. In Matrix, Single Choice question:

Add rows along with columns in Edit. - Yes, it was fixed several days ago.
All other enhancements are about matrix dropdown. The column designer has been rewritten completely. I was working on it for several days.
Here is new properties in the dropdown column: https://github.com/surveyjs/surveyjs/issues/286

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
> The properties area should have its own scrolling.
It is implemented.

**Comment by andrewtelnov** [comment]
Your first item is about implementing custom widgets. Please review [this demo](http://editor.surveyjs.io/examples/customwidgets.html)

**Comment by andrewtelnov** [comment]
The 6-th topic is also implemented in [custom widget demo](http://editor.surveyjs.io/examples/customwidgets.html)

**Comment by muhfred** [comment]
Thank you andrew, just have a couple of questions, is this project open for contribution?, and can I buy a licence with one time payment option?

**Comment by andrewtelnov** [comment]
@muhfred  Sure, the project is open for contributions.
However, surveyjs Editor is not under MIT license and you will have to sign a contribution agreement. Github has something built-in; we have to read about it.
Of course, it is not a problem, if you are talking about bug fixes or localizations. If you are talking about a large enough functionality, it is better discuss with us before you start. 

About license and one-time payment. You may do not renewal the subscription. It is totally up to you. Here is the statement from http://editor.surveyjs.io/license.html: 
“Allows using the last received update for unlimited period of time.”
It means that if you pay on March 31, 2017, then a version, that you may use in your project(s), should be released on March 31, 2018 or before. You may use it as long as you wish. If you want to use a version released after March 31, 2018, you would have to pay for renewal. If there is no need in new versions, you do not need to renewal the subscription.

Thank you,
Andrew

**Comment by muhfred** [comment]
Dear Andrew, 
Can you please give me feedback regarding the following point?: 
-Adding icons for questions and answers.
Thanks

**Comment by muhfred** [comment]
Dear Andrew, 
I tried to Remove dots in properties dropdown list, but empty spaces doesn't seem to be intended.
//"..." is the default value.
SurveyEditor.SurveyObjects.intend = "  "; 
Thanks.

**Comment by muhfred** [comment]
Dear Andrew, 
Did you think about the following points:
3- A tooltip should appear at the plus sign of add page.
5- In checkbox question:
- In fast Entry remove values and values should be generated by default 1, 2, 3, 4….etc., and if values exceeded 9 the values should appear, 01 ,02, 03, 04….10
- In form entry switch value and text positions.
- Add rotating order to choices order.
7-Add filter by question name or question type in the middle section of the design.

9-In Matrix, Single Choice question:

- In matrix properties, add asc, desc, random, and rotating order.
- Add Input type text and the user should enter one answer only just like the radio button but with input text.
- Add numeric input type to matrix.

Thank you.

**Comment by andrewtelnov** [comment]
@muhfred Yes, I forgot to export SurveyObjects. This code current gives you an error.
I have added a new options: objectsIndend. After releasing v0.12.5 you will be able to set it in options:

```
var editor = new SurveyEditor.SurveyEditor("editor", 
{ alwaySaveTextInPropertyEditors: false, showEmbededSurveyTab : true, objectsIntend: "---" });

```

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
3 - I have added a tool tip
5 - 
> In fast Entry remove values and values should be generated by default 1, 2, 3, 4….etc., and if values exceeded 9 the values should appear, 01 ,02, 03, 04….10

Many people would be unhappy with this decision.  What if I have to enter the states as: TX,Texas?

> In form entry switch value and text positions.

You may do not enter the text, in this case value will be used as a text

> Add rotating order to choices order.

Could you explain please, what should it do?

> 7-Add filter by question name or question type in the middle section of the design.

I wanted to use select2 as objects selector, if select2 is included.

> 9-In Matrix, Single Choice question:

You have all these functionality in matrix dropdown question.  You may have only one column.
Or do you want to have the order for rows?

Thank you,
Andrew

**Comment by muhfred** [comment]
Dear Andrew,
Can you please give me feedback regarding the following point?:
-Adding icons for questions and answers.
Thanks

**Comment by muhfred** [comment]
Add search function for question name or question type next to "save survey" button.

Thanks, Andrew

**Comment by andrewtelnov** [comment]
@muhfred 
>Adding icons for questions and answers.

I am not sure what do you mean. Do you want to have an image before title? 
There is a request of adding markup support for title. I think it is the way to go. In this case, you may do what ever you want.

> Add search function for question name 

It is in our TODO list.

**Comment by muhfred** [comment]
@andrewtelnov for example, if added a Radio Group question (Gender), it would be awesome if we could add an icon next to Gender question, also add icons for each choice (male, female).
Thank you.

**Comment by andrewtelnov** [comment]
Aha, I got you now. I have added this functionality into our TODO list.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@muhfred Please take a look on element selector (dropdown) http://surveyjs.org/builder/
It can use select2 plugin, if select2 is included on the page: https://github.com/surveyjs/editor/issues/77

**Comment by andrewtelnov** [comment]
@muhfred We have added the markdown support. So icons and many other markdown features are available:
http://surveyjs.org/examples/knockout/survey-markdown-radiogroup.html
http://surveyjs.org/examples/knockout/survey-markdown-matrix.html

Thank you,
Andrew

**Comment by muhfred** [comment]
That is so awesome thank you.

**Comment by muhfred** [comment]
make the user have the ability to add a photo in survey header like a logo, a footer to add any copyright or additional information, and the ability to change the background color/image. let me know what you think,
Thanks.

**Comment by andrewtelnov** [comment]
@muhfred I personally think, these features should be out of the survey library. https://dxsurvey.com may provide these features, but not survey js library, like:
```
<div id="mainDivWithBackgroudOrImage">
<div id="header"></div>
<div id="survey"></div>
<div id="footer"></div>
<div>
```
The idea of creating this library - add the ability to insert the survey into any part of your web page, as you wish.

Thank you,
Andrew

**Comment by muhfred** [comment]
@andrewtelnov can we set a Quota on every answer? it's a feature that is in almost every survey engine.
Thank you.

**Comment by andrewtelnov** [comment]
@muhfred I guess you are talking about the service, dxsurvey.com.

Thank you,
Andrew

**Comment by muhfred** [comment]
I'm not sure what you're saying, but the survey engine should set a limit not only on the whole survey but also in each and every answer, let's say as on the whole survey should take 50 results, and on answers, 25 males, and 50 females, 25 males who owns a car, and 50 females who has children, like so, after it reach its quota the survey should stop running.

**Comment by andrewtelnov** [comment]
:-) @muhfred We can't make it on our side. You have to write the code that does it on your side. If you are storing data on dxsurvey.com then you may call web api similar to this demo: http://surveyjs.org/examples/jquery/service-result/. If you see you have enough answers, then show a text that survey is closed instead of the survey. 
We can do it for surveys that people run on dxsurvey.com only.

Thank you,
Andrew

**Comment by muhfred** [comment]
OK, but how to set a quota on answers?
Thank You.

**Comment by andrewtelnov** [comment]
@muhfred I will do an example on plunker later.

Thank you,
Andrew

**Comment by muhfred** [comment]
@andrewtelnov Thank You, I appreciate it. please tell me when you do so.
Thanks.

**Comment by andrewtelnov** [comment]
@muhfred Here is the demo: https://github.com/surveyjs/surveyjs/issues/479

**Comment by muhfred** [comment]
@andrewtelnov Thank you very much, I appreciate it.
