### ISSUE TITLE
 properties names

### ISSUE THREAD

**Issue by MohabElgammal** [surveyjs/editor#65]
Hi andrew, love surveyEditorjs, great work, could you please change or walk me through on how to change the properties names? they seem complicated and not straight forward for the user to understand. Thank you.

**Comment by andrewtelnov** [comment]
@MohabElgammal I guess you are actually talking about localization. I have just made an example: http://editor.surveyjs.io/examples/localization.html#code

Please note, that you have to used cdn version: https://github.com/surveyjs/builds or rebuild the sources.
There was a bug: https://github.com/surveyjs/editor/issues/66

Thank you,
Andrew

**Comment by MohabElgammal** [comment]
sorry andrew, I mean the properties area for each survey, page and question that appears on the right, can we change the names of each property or show me how to change them, Thanks

**Comment by andrewtelnov** [comment]
@MohabElgammal http://editor.surveyjs.io/examples/localization.html#code does exactly what you need.

**Comment by MohabElgammal** [comment]
@andrewtelnov Do you mean that if i changed the English text strings, it would update the properties Area??

**Comment by andrewtelnov** [comment]
@MohabElgammal Exactly, in this example isRequired question property shows as "Wird benötigt". 
```
var deutschStrings = {
    p: {
        isRequired : "Wird benötigt",
        name: "My name traslation"
    }
};
```
Drop a question and look at it's properties in [the demo](http://editor.surveyjs.io/examples/localization.html)

You may change all editors strings, just look at defaultStrings property in this file: https://github.com/surveyjs/editor/blob/master/src/editorLocalization.ts

**Comment by MohabElgammal** [comment]
@andrewtelnov thank you very much
