### ISSUE TITLE
Angular 2 support

### ISSUE THREAD

**Issue by daitd58** [surveyjs/editor#67]
Hi, I'm using the survey angular 2. How can I integrate the survey editor to  my project? I've tried to using the survey editor to my angular 2 project but it gets many problems. Any advice?

Thanks.

**Comment by andrewtelnov** [comment]
@daitd58 Unfortunately SurveyJS Editor supports knockout only at the current moment.
Basically the question is: how to use a knockout widget inside angular 2 app. You may google it, there are some examples.
We will make examples how to use the editor in all popular frameworks, at least in all frameworks, that surveyjs library supports.
I have just added this task into our TODO list and we will work on it, as soon as we finish with the current task (functional tests for surveyjs and Editor).

Thank you,
Andrew

**Comment by daitd58** [comment]
Thanks. Hope your team can make the example for all frameworks that surveyjs library support soon.

**Comment by tsv2013** [comment]
@daitd58 We've prepared example how to use SurveyJS and SurveyJS Editor in the Angular2 application. You can check the [surveyjs_angular_quickstart](https://github.com/surveyjs/surveyjs_angular_quickstart) repo.

**Comment by daitd58** [comment]
@tsv2013 Could you make an example to use SurveyJS and SurveyJS Editor with angular cli? Thanks.

**Comment by tsv2013** [comment]
@daitd58 Do you mean [this](https://cli.angular.io/) tool?

**Comment by daitd58** [comment]
@tsv2013 yes. My project bases on that.  Hope you can make a demo for me? Thanks.

**Comment by tsv2013** [comment]
@daitd58 Sure :)

**Comment by daitd58** [comment]
@tsv2013 👍. Please make it on this day :D.

**Comment by tsv2013** [comment]
@daitd58  You can check the https://github.com/surveyjs/surveyjs_angular_cli repo.

**Comment by daitd58** [comment]
@tsv2013 I don't see where you import SurveyJS and SurveyJS Editor?

**Comment by tsv2013** [comment]
@daitd58 You are right. I forgot to commit changes. Please check the 22d5cd2e1d49eccd1b52d1c3fce4feab185b8a36 commit.

**Comment by daitd58** [comment]
@tsv2013 Yeah. I see it. Thank you. You saved me ✌️
