### ISSUE TITLE
ShowQuestionNumbers property

### ISSUE THREAD

**Issue by SlowburnAZ** [surveyjs/editor#71]
When passing options to the editor, I can't seem to initialize the editor with the 'showQuestionNumbers' option set to "off".

I've tried passing in
`
{
  ...,
  showQuestionNumbers: false,
  ...
`

and also

`
{
  ...,
  showQuestionNumbers: 'off',
  ...
}
`

and neither seems to work.  Do I have the right option property name?

**Comment by andrewtelnov** [comment]
@SlowburnAZ showQuestionNumbers is the survey property and not editor.
You may set it via editor.text:
`editor.text = "{ pages: [ { name: 'page1'}], showQuestionNumbers: 'off' }";`
It may be useful to change the default options in the survey, so for example showQuestionNumbers will have the default value as 'off'.
However,  to be honest, I am not sure about this functionality. It may lead to other issues.

Thank you,
Andrew

**Comment by SlowburnAZ** [comment]
Ah, my mistake.  I thought it could be used in the editor so that then the numbers wouldn't show in the survey when rendered.  I'll just set the prop before rendering the survey on the page.

Thanks!
