### ISSUE TITLE
Bulding issue

### ISSUE THREAD

**Issue by MohabElgammal** [surveyjs/editor#72]
Dear Andrew:-
I got this issue while building last version

 ERROR in ./src/surveyObjects.ts
(119,43): error TS2339: Property 'elements' does not exist on type 'Page'.

ERROR in ./src/surveyObjects.ts
(124,68): error TS2694: Namespace '"D:/projects/asp.net/Kadia/survey/src/editor-0.12.5/node_modules/survey-knockout/survey.ko"' has no exported member 'IElement'.

ERROR in ./src/surveyObjects.ts
(128,57): error TS2694: Namespace '"D:/projects/asp.net/Kadia/survey/src/editor-0.12.5/node_modules/survey-knockout/survey.ko"' has no exported member 'Panel'.

ERROR in ./src/surveyObjects.ts
(130,51): error TS2694: Namespace '"D:/projects/asp.net/Kadia/survey/src/editor-0.12.5/node_modules/survey-knockout/survey.ko"' has no exported member 'Panel'.

ERROR in ./src/surveyjsObjects.ts
(19,14): error TS2339: Property 'onAfterRenderPanel' does not exist on type 'SurveyForDesigner'.

ERROR in ./src/surveyjsObjects.ts
(217,8): error TS2339: Property 'Panel' does not exist on type 'typeof "D:/projects/asp.net/Kadia/survey/src/editor-0.12.5/node_modules/survey-knockout/survey.ko"'.

ERROR in ./src/surveyjsObjects.ts
(222,8): error TS2339: Property 'Panel' does not exist on type 'typeof "D:/projects/asp.net/Kadia/survey/src/editor-0.12.5/node_modules/survey-knockout/survey.ko"'.

ERROR in ./src/surveyjsObjects.ts
(232,8): error TS2339: Property 'Panel' does not exist on type 'typeof "D:/projects/asp.net/Kadia/survey/src/editor-0.12.5/node_modules/survey-knockout/survey.ko"'.

ERROR in ./src/questionToolbox.ts
(104,35): error TS2339: Property 'ElementFactory' does not exist on type 'typeof "D:/projects/asp.net/Kadia/survey/src/editor-0.12.5/node_modules/survey-knockout/survey.ko"'.

ERROR in ./src/questionToolbox.ts
(120,31): error TS2339: Property 'ElementFactory' does not exist on type 'typeof "D:/projects/asp.net/Kadia/survey/src/editor-0.12.5/node_modules/survey-knockout/survey.ko"'.

ERROR in ./src/propertyEditors/propertyTextItemsEditor.ts
(31,18): error TS2339: Property 'isRequired' does not exist on type 'MultipleTextItem'.

ERROR in ./src/editor.ts
(273,45): error TS2339: Property 'getPageByElement' does not exist on type 'SurveyForDesigner'.

ERROR in ./src/editor.ts
(283,42): error TS2694: Namespace '"D:/projects/asp.net/Kadia/survey/src/editor-0.12.5/node_modules/survey-knockout/survey.ko"' has no exported member 'Panel'.

ERROR in ./src/editor.ts
(284,45): error TS2339: Property 'getPageByElement' does not exist on type 'SurveyForDesigner'.

ERROR in ./src/editor.ts
(419,26): error TS2339: Property 'onPanelAdded' does not exist on type 'SurveyForDesigner'.

ERROR in ./src/editor.ts
(420,26): error TS2339: Property 'onPanelRemoved' does not exist on type 'SurveyForDesigner'.

ERROR in ./src/editor.ts
(520,37): error TS2339: Property 'removeElement' does not exist on type 'PageModel'.

ERROR in ./src/dragdrophelper.ts
(96,19): error TS2346: Supplied parameters do not match any signature of call target.

ERROR in ./src/dragdrophelper.ts
(131,43): error TS2694: Namespace '"D:/projects/asp.net/Kadia/survey/src/editor-0.12.5/node_modules/survey-knockout/survey.ko"' has no exported member 'PanelModelBase'.

**Comment by andrewtelnov** [comment]
@MohabElgammal You "elements" and other methods were added into surveyjs v0.12.6. Please make sure that you are reference the correct version.

Thank you,
Andrew

**Comment by tsv2013** [comment]
@MohabElgammal Probably "npm update" resolves this.
