### ISSUE TITLE
VisibleIF GUI 

### ISSUE THREAD

**Issue by MohabElgammal** [surveyjs/editor#73]
Dear Andrew:-
add GUI for visibleIF function 
Thanks

**Comment by andrewtelnov** [comment]
@MohabElgammal It is in our TODO list. Unfortunately, it is quite large and complex task that is why we have to postpone it. 
Anyway, you can be sure, that we will work on it as well. I personally, understand the importance of having easy to use VisibleIf Editor.

Thank you,
Andrew

**Comment by MohabElgammal** [comment]
Ok,I'm waiting
Thank you for your efforts,
Mohab

**Comment by andrewtelnov** [comment]
@MohabElgammal Could you please check our new GUI for visibleIf expression?
Here is [the related issue](https://github.com/surveyjs/editor/issues/251#issuecomment-365848270)

Thank you,
Andrew
