### ISSUE TITLE
compatibility

### ISSUE THREAD

**Issue by pierrecharlesp** [surveyjs/editor#75]
Thanks for great job.
Which version of firefox is compatible with survey.js ? 
I meet issues with VisibleIf property and firefox ESR 45.3.
VisibleIF isn't working. Page doesn't appear.

Many thanks.

**Comment by andrewtelnov** [comment]
@pierrecharlesp What version of surveyjs do you using? react. jquery, knockout?

Thank you,
Andrew

**Comment by pierrecharlesp** [comment]
jquery

**Comment by pierrecharlesp** [comment]
do you advice me to use React or Knockout ?

**Comment by andrewtelnov** [comment]
@pierrecharlesp we will investigate the issue. @tsv2013 is working on it: https://github.com/surveyjs/surveyjs/issues/322

**Comment by tsv2013** [comment]
@pierrecharlesp All SurveyJS library platfroms should work identically. Editor uses KnockoutJS internally. I'm closing this as a duplicate of https://github.com/surveyjs/surveyjs/issues/322. Could you please check updated thread?
