### ISSUE TITLE
Bar Rating Custom Widget Throws Error editor version 0.12.6

### ISSUE THREAD

**Issue by muhfred** [surveyjs/editor#76]
Dear Andrew,
When I try to use the custom widget bar rating, It appears in the question types, but when I try to add the question it throws the following error in the console window:

`knockout-3.3.0.js:66 Uncaught TypeError: Unable to process binding "foreach: function (){return { data:row.koElements,as:'question',afterRender:row.koAfterRender} }"
Message: Unable to process binding "if: function (){return !question.isPanel }"
Message: Unable to process binding "template: function (){return { name:'survey-question',data:question,afterRender:$parent.panel.koQuestionAfterRender} }"
Message: Unable to process binding "template: function (){return { name:question.koTemplateName(),data:question,afterRender:question.koQuestionAfterRender} }"
Message: $el.barrating is not a function
    at Object.afterRender (test.js:53)
    at QuestionCustomWidget.afterRender (questionCustomWidgets.ts:9)
    at QuestionSelectBaseImplementor.QuestionImplementor.koQuestionAfterRender (koquestion.ts:74)
    at QuestionImplementor._this.question.koQuestionAfterRender (koquestion.ts:32)
    at Object.u (knockout-3.3.0.js:35)
    at e (knockout-3.3.0.js:104)
    at knockout-3.3.0.js:105
    at l (knockout-3.3.0.js:44)
    at Object.a.w.a.j (knockout-3.3.0.js:47)
    at Object.a.eb (knockout-3.3.0.js:105)`

please review and advice
Thank you.

**Comment by andrewtelnov** [comment]
@muhfred Please check that you are using library and editor the same version. The latest version is 0.12.6.
The following example works fine: http://editor.surveyjs.io/examples/customwidgets.html

Thank you,
Andrew

**Comment by muhfred** [comment]
it's not an issue for survey editor, you have to download and include the js libraries according to each widget.
Great Work,
Thank you.
