### ISSUE TITLE
Survey editor build failed with Meteor

### ISSUE THREAD

**Issue by summer0nguyen** [surveyjs/editor#80]
I'm building Survey Editor with meteor and React. 

> W20170421-04:00:32.101(7)? (STDERR) /home/summer/.meteor/packages/meteor-tool/.1.4.0.opqorv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170421-04:00:32.102(7)? (STDERR) 						throw(ex);
W20170421-04:00:32.102(7)? (STDERR) 						^
W20170421-04:00:32.103(7)? (STDERR) 
W20170421-04:00:32.103(7)? (STDERR) TypeError: Cannot set property 'emulateTransitionEnd' of undefined
W20170421-04:00:32.103(7)? (STDERR)     at webpack:///~/bootstrap/js/transition.js:39:1
W20170421-04:00:32.104(7)? (STDERR)     at Object.dismiss (webpack:///~/bootstrap/js/transition.js:59:1)
W20170421-04:00:32.104(7)? (STDERR)     at __webpack_require__ (webpack:/webpack/bootstrap e925ed98336edea58b46:22:1)
W20170421-04:00:32.104(7)? (STDERR)     at Object.<anonymous> (webpack:///~/bootstrap/dist/js/npm.js:5:1)
W20170421-04:00:32.104(7)? (STDERR)     at __webpack_require__ (webpack:/webpack/bootstrap e925ed98336edea58b46:22:1)
W20170421-04:00:32.104(7)? (STDERR)     at n.(anonymous function).i (webpack:///~/surveyjs-editor/surveyeditor.min.js:7:1)
W20170421-04:00:32.104(7)? (STDERR)     at Object.DEBUG (webpack:///~/surveyjs-editor/surveyeditor.min.js:7:1)
W20170421-04:00:32.105(7)? (STDERR)     at __webpack_require__ (webpack:/webpack/bootstrap e925ed98336edea58b46:22:1)
W20170421-04:00:32.105(7)? (STDERR)     at Object.<anonymous> (webpack:///imports/components/survey/editor_tabs/SurveyDesign.jsx:6:1)
W20170421-04:00:32.105(7)? (STDERR)     at __webpack_require__ (webpack:/webpack/bootstrap e925ed98336edea58b46:22:1)
=> Exited with code: 1

I have this error . 
I thought that jquery is missing but it's not. 
Do you have any idea.
Thanks

**Comment by dmitrykurmanov** [comment]
@summer0nguyen, hello! Could you please specify surveyjs-editor version? And t would be greate it you provide an example for debugging.

**Comment by summer0nguyen** [comment]
Dear @dmitrykurmanov , thank you for replying.
I used the latest version of surveyjs-editor. 

I used rubix410.sketchpixy.com/ltr/social as a seed project with : React , Webpack .

**Comment by summer0nguyen** [comment]
I think it's not a problem of survey-editor :) 
Great job
