### ISSUE TITLE
Survey Save and import 

### ISSUE THREAD

**Issue by summer0nguyen** [surveyjs/editor#81]
Hello,
I am making Survey using SurveyJS with React. 

I have problem in exporting text from SurveyEditor and importing the text to SurveyReact .

Here is the code on Survey Editor : 

```
saveSurvey(){
  survey.survey_config = this.editor.text;
  // .... Save Survey 
 console.log(typeof survey_config) => shown "string" 
}
```

Here is the code on Survey JS 

```
render() {
    if(this.props.survey){
       
        console.log(JSON.parse(this.props.survey.survey_config))  // Shows Error about JSON parsing 


    }else{
      return (<div>Loading </div>)
    }
  }
```

I think it's simple to you. But I don;t know how to fix. 
Do you have any idea.
Thank you

**Comment by summer0nguyen** [comment]
Hello,
I found that you are using JSON5 ( your own version ) in survey-editor . 
I saved the JSON5 string ( editor.text) to my database. 
And When I load the text to survey : 

```

var JSON5 = require('json5');

....
....
 json = JSON5.parse(this.props.survey.survey_config);
return (
              <div id="surveyform">
                   <Survey.Survey json={json} onComplete={this.sendDataToServer.bind(this)}/>
              </div>
          )
```

I wonder if it raise any further errors  OR any better solution for saving the text. 
Thank you very much

**Comment by andrewtelnov** [comment]
@summer0nguyen You may simply turn-on generateValidJSON option in the editor:
Here is the docs: http://editor.surveyjs.io/examples/options.html#code

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
I will make a valid JSON generation as a default one, https://github.com/surveyjs/editor/issues/82

**Comment by summer0nguyen** [comment]
Awesome . 
 I'm stuck at this for a long time. 
Thank you very much.  .
You did a very great job.
