### ISSUE TITLE
Breaking change: Generate the valid JSON by default

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/editor#82]
At the current version, v0.12.10 and early, Editor generates JSON5. It is easily for reading. However, there are issues on different back-ends with JSON5.
The easiest solution, generate valid JSON by default and turn-on JSON5 on surveyjs.org/builder and dxsurvey.com.

**Comment by rjsteinert** [comment]
Is there a work around for this in 0.12.15?

**Comment by andrewtelnov** [comment]
@rjsteinert Do you mean how to make the JSON generation readable, but not valid?
You may set the option as :
`   var editor = new SurveyEditor.SurveyEditor("editor", { generateValidJSON : false});`

Thank you,
Andrew

**Comment by rjsteinert** [comment]
@andrewtelnov Hi Andrew, sorry, I'm looking to generate valid JSON. The `generateValidJSON` option did the trick! I definitely agree that generating valid JSON by default is a sensible option.

Thanks for the tip, I was able to finish my pull request to surveyjs_angular_cli. 

https://github.com/surveyjs/surveyjs_angular_cli/pull/4/files#diff-4ed3181376fdc2cf15122db0f58d4c93R13
