### ISSUE TITLE
.Dist folder

### ISSUE THREAD

**Issue by MohabElgammal** [surveyjs/editor#83]
### Are you requesting a feature, reporting a bug or ask a queation?
No

### What is the current behavior?
after building the latest version 0.12.11, i can't find The (.dist) folder, so i can include the javascript files 

### What is the expected behavior?
 i want to include the javascript files after building

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:0.12.11

**Comment by dmitrykurmanov** [comment]
@MohabElgammal, hello! 'dist' was renamed to 'package' and we fixed our readme, thanks!

**Comment by MohabElgammal** [comment]
i can't find the package folder either

**Comment by dmitrykurmanov** [comment]
@MohabElgammal I can't reproduce it. Do you have any errors during the build?

**Comment by MohabElgammal** [comment]
OK,i finally got it
Thanks
