### ISSUE TITLE
Survey Editor Trigger : Complete Survey not working

### ISSUE THREAD

**Issue by summer0nguyen** [surveyjs/editor#84]
Hello,
I found that the complete survey trigger does not work anymore on : 0.12.11 and 0.12.10

I created a survey : http://surveyjs.org/builder/#b79fb49c-d400-4c85-b486-c2e4ffb67857 

with 2 questions and 1 Trigger: Close the survey if question1 = 0 

But when I choose  0  ( No, please close) . Nothing happens. 

I remember testing it worked on previous version . 

Could you please have a look at this. 
Thank you

**Comment by andrewtelnov** [comment]
@summer0nguyen Please add one more page and you will see that it still working. It triggers on pressing the "Next" page button.

Thank you,
Andrew

**Comment by summer0nguyen** [comment]
Dear @andrewtelnov : thank you very much.
I got it
