### ISSUE TITLE
Complex conditions in trigger

### ISSUE THREAD

**Issue by varunkumar** [surveyjs/editor#85]
Is there a way to define complex conditions (AND, OR) in setValue trigger?

**Comment by andrewtelnov** [comment]
@varunkumar Unfortunately, you can't do it right now.
You have to use onValueChanged event: http://surveyjs.org/examples/jquery/survey-data.html

**Comment by andrewtelnov** [comment]
@varunkumar We support expression like in visibleIf since v1.0.30 released on this week.

Thank you,
Andrew
