### ISSUE TITLE
Locale list customization?

### ISSUE THREAD

**Issue by GeorgeBB** [surveyjs/editor#86]
Greetings! Is it possible to customize the locale option lists in editor?
Appreciated!

**Comment by andrewtelnov** [comment]
@GeorgeBB I think we will make it similar to wiki language choice:
العربية
Azərbaycanca
বাংলা
Български
Bosanski
Català
Čeština
Cymraeg
Dansk
Deutsch
.....
If you are ok with it, we  add this in out TODO list.

Thank you,
Andrew

**Comment by GeorgeBB** [comment]
Great response!

Just thinking that it would be much more flexible if user can customize the choices of language.  For example, only English and Portuguese are configured to be available to select in the locale dropdown in editor, because users may only focus on certain languages they need.

Cheers!

**Comment by andrewtelnov** [comment]
@GeorgeBB Yes, it makes sense as well. I have created a card in our TODO list and added the ability to filter the choices.

Thank you,
Andrew

**Comment by GeorgeBB** [comment]
Thanks to your attention and efforts!
Cheers!

**Comment by andrewtelnov** [comment]
@GeorgeBB Sorry that it takes me so long. I have started to work on this.
At first I have found that the easiest way to limit the number of locales is already here.
Use the following code:
```
var supportedLocales = ["en", "de", "fr"];
for(var key in Survey.surveyLocalization.locales) {
  if(supportedLocales.indexOf(key) < 0) {
    delete Survey.surveyLocalization.locales[key];
  }
}
```
I have just added a new property: [Survey.surveyLocalization.defaultLocale](https://github.com/surveyjs/surveyjs/issues/433). It will be available in the next minor version.
Further, I am working on properties values localization. Locale property is just another property which values I have to localize (show locale values as languages names). 

Thank you,
Andrew

**Comment by GeorgeBB** [comment]
@andrewtelnov Much appreciated to your great efforts!

**Comment by andrewtelnov** [comment]
@GeorgeBB The new version shows locales as on wiki (https://github.com/surveyjs/editor/issues/103) and you will be able to limit the number of supported locales as simple as:
`Survey.surveyLocalization.supportedLocales = ["en", "de"];`

Thank you,
Andrew
