### ISSUE TITLE
onRowAdded / onColumnAdded (and removed)

### ISSUE THREAD

**Issue by chrisweconect** [surveyjs/editor#87]
Hi, 

I'm generating custom UUID's for each question name like in your example here: http://editor.surveyjs.io/examples/oncreatequestion.html#code

It works fine.

I'm now trying to generated a custom UUID for in the "name" field in columns and "value" field on question rows in Matrices.  I use the onQuestionAdded callback for that and it works great.

However - if a user **adds** a row or column, the new UUID isn't generated because it's not possible to hook into that event and automatically generate a UUID for the new row/column.

I noticed you have an "onModified" hook, but I can't get the current question from that in order to generate a new UUID for the column/row.

Questions:

1.)  Are you able to add an onRowAdded / onColumnAdded (and removed) hook?  Or is there currently a way to hook into creating a row/column?

2.)  I also can't get the readonly to work for the name fields as shown on your examples page (above).

I'm on the latest version.

Thanks!  I'm really enjoying using Survey.js

Examples:

![screen shot 2017-05-04 at 14 21 01](https://cloud.githubusercontent.com/assets/24935674/25751645/0b5a5362-31b6-11e7-8333-41e494dc7bc9.png)

![screen shot 2017-05-04 at 14 20 57](https://cloud.githubusercontent.com/assets/24935674/25751653/10a48c8e-31b6-11e7-9f3f-a995e90ec5d6.png)

![screen shot 2017-05-05 at 14 49 19](https://cloud.githubusercontent.com/assets/24935674/25751656/1474101e-31b6-11e7-9d9e-34283517fe90.png)

**Comment by andrewtelnov** [comment]
@chrisweconect I have been thinking about your suggestion. I have to admit, that it looks interesting to me.
I have two questions:
1) Do you want to have this functionality just for matrix, or for checkbox/radiogroup/dropdown.choices as well? I may add an event for ItemsValue Editor on adding a new item.
2) Frankly, you do not need to show "Value" column in your customized editor at all. It will just confuse the end-users. However, "Fast Entry" section has to be hide in this case. What do you think? Do you need it or it will be waste of our time?

Thank you,
Andrew

**Comment by chrisweconect** [comment]
@andrewtelnov - Thanks for your quick reply (as always).

1.) For the non-matrix questions, the onQuestionAdded works **okay**.  It's not optimal, however, because it's very general.  For example, it also fires when simply **sorting** the questions on the page.  Not sure we want that happening. But for now, it works okay on non-matrix questions.

2.)  It would be very helpful to have an "**onQuestionModified**" or **onQuestionChanged**" event we can hook into when adding/modifying a matrix row/column.  It would be good to have that event fire when "apply" is clicked OR when you click outside of a text field in the row/column editor before it's validated and saved.

This way we can create custom UUID's for the matrix questions.

(Background: We're using custom UUID's so when json with answers comes in, we can match an answer with a question based on that answer's question UUID.  Then we're storing that answer in our database along with the question id.  This is why we need to add custom UUID's to the questions.)

So - yes! - we would like to have "onQuestionModified/onQuestionChanged" fire when adding a row or column to the matrix.  (Even better would be to have an automatically-added UUID field on every question, but I'm sure that would be much more work.)

Thanks **very** much,
Chris

**Comment by joshreid** [comment]
Hi Andrew
I am trying to do just the same thing, but for all selectbase (question with choices) - I want to set the choice values to a guid on add and hide the value from editor for all - so the user only sees and enters the text.
Look forward to your thoughts, thanks!

**Comment by andrewtelnov** [comment]
@chrisweconect and @joshreid please take a look at: https://github.com/surveyjs/editor/issues/89
It will come with the next minor update, likely on this week.

Thank you,
Andrew

**Comment by chrisweconect** [comment]
@andrewtelnov - Thanks very much.
