### ISSUE TITLE
How to set default answers when adding a question

### ISSUE THREAD

**Issue by muhfred** [surveyjs/editor#88]
### Are you requesting a feature, reporting a bug or ask a queation?

question

### What is the current behavior?

when adding a checkbox question, it automatically sets defaults answers, how can I adjust this default answers?

### What is the expected behavior?

when adding a checkbox question, I want to be able to set the default answers when the question is added.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: chrome 58
* editor version: 012.12

**Comment by andrewtelnov** [comment]
@muhfred There is an example, that does exactly what you need. Please read this document for the example: http://editor.surveyjs.io/examples/toolboxcustomization.html#code

**Comment by andrewtelnov** [comment]
@muhfred Please read the doc carefully. It is probably needs to be improved, but all methods are there.

```
var newCheckbox = {
        "name": "checkbox",
        "iconName": "checkbox",
        "title": "My Checkbox",
        "json": {   type: "checkbox",  choices: [  "my item1",  "my item2" ] } 
};
editor.toolbox.replaceItem(newCheckbox);
```

**Comment by muhfred** [comment]
@andrewtelnov OK got it, Thank You.
