### ISSUE TITLE
Add events to setup a new added ItemValue (choices Row) and a matrix column

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/editor#89]
The value for choices, matrix.columns and matrix.rows maybe auto generated. For example, by setting UUID  into value.

**Comment by andrewtelnov** [comment]
Two new events have been added:
editor.onItemValueAdded - calls when a new item in checkbox/dropdown/radigroup choices, matrix.columns, matrix.rows, matrixdropdown.rows.
editor.onMatrixColumnAdded - calls when a new column in matrixdropdown or in matrixdynamic is added.
Here is the example of using:
```
editor.onItemValueAdded.add(function(editor, options){
  //matrixdropdown.rows and matrix.rows
  if(options.propertyName == 'rows') {
    options.newItem.value = guid();
  }
});
editor.onMatrixColumnAdded.add(function(editor, options){
  options.newColumn.name = guid();
});

```

**Comment by chrisweconect** [comment]
@andrewtelnov - Great!  Thanks very much, Andrew.

**Comment by joshreid** [comment]
This is awesome Andrew thanks!!!
