### ISSUE TITLE
Checkbox Radiogroup hascomment hasother is not working properly

### ISSUE THREAD

**Issue by krishnathamisetty** [surveyjs/editor#90]
### Are you requesting a feature, reporting a bug or ask a queation?
bug

### What is the current behavior?
For Checkbox, Radiogroup:
1. When user selected hasOther = true and enter otherText (Other (please specify), otherText is not reflecting on "Survey Designer" as well on "Test Survey", "Other (please specify)" is showing when user clicks on "Other (describe)" at the time of "Test Survey".
2. When user selected hasComment = true and hasOther = false, we noticed the same above point 1 issue.
3. When user selected hasComment = true and hasOther = false and while running Test Survey, comment enter by user is not showing under survey results, comment information is showing only when user select hasComment = false and hasOther = true
4. user select hasComment = true and hasOther = true, hasOther is becoming false i.e. Radio or Checkbox is not showing and user enter comment is also not showing on Survey Results.
5. Can you explain the difference between hasComment and hasOther.

### How would you reproduce the current behavior (if this is a bug)?
Use below Tested page URL, to reproduce this issue.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:http://surveyjs.org/builder/#6b057f3d-59d4-478b-aee5-4c32c0793634

Test code

```
your_code_here

```

### Specify your

* browser: chrome
* editor version: 0.12.14

**Comment by andrewtelnov** [comment]
@krishnathamisetty Bugs have been fixed.

Thank you,
Andrew

**Comment by krishnathamisetty** [comment]
Thanks Andrew for your quick response.
I verified your fix using survey editor which is available @ http://surveyjs.org/builder/. Do I need to wait for new version of Survey Editor?

**Comment by krishnathamisetty** [comment]
In survey designer it is showing immediately, but when you refresh again it is showing Other (describe) instead of otherText message and also it is not reflected on Test Survey.

**Comment by andrewtelnov** [comment]
@krishnathamisetty I did not update the site yet. We will do it with the next release. Likely on this week.
You may always build the sources, library and editor, by yourself and use them in your app. The instruction in the readme files of the repos.

Thank you,
Andrew

**Comment by krishnathamisetty** [comment]
Thanks Andrew.

**Comment by krishnathamisetty** [comment]
This is working fine in 0.12.15 Version.
