### ISSUE TITLE
Multiple Text questions -- name (text1, text2) is not changing immediately

### ISSUE THREAD

**Issue by krishnathamisetty** [surveyjs/editor#91]
### Are you requesting a feature, reporting a bug or ask a queation?
bug

### What is the current behavior?
While editing Multiple Text --> Items --> when I updated Name: text1, text2 with some other text is not reflecting immediately until unless when I refresh the page or clicking any other tab on survey editor

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by andrewtelnov** [comment]
It is fixed. 
Thank you, Andrew

**Comment by krishnathamisetty** [comment]
This is working fine.
