### ISSUE TITLE
Add column in checkbox or radio element

### ISSUE THREAD

**Issue by grelu** [surveyjs/editor#92]
### Are you requesting a feature, reporting a bug or ask a queation?
Question

### What is the current behavior?
When I add an element (checkbox type), I don't have the possibility to add a column.

### What is the expected behavior?
I would like to have the possibility to add, for example, a column in the field

Example view (fast entry)

1|0.25|first item
2|0.5|second item
3|1|third item

Values 0.25, 0.5 and 1 are in a custom field in input checkbox : num='0.25', or customCol='0.25'

Is it possible ?
Thank you very much ! Surveyjs is wonderful...

**Comment by andrewtelnov** [comment]
@grelu Sorry for delay. I have missed your question for some reason :-(
I do not understand the question. Why do you need to have value 1, 2, 3 and not 0.25, 0.5 and 1?

Thank you,
Andrew

**Comment by grelu** [comment]
@andrewtelnov : no problem ! My question : it is possible to add more column ? Now, we have two columns : value and text. But I need others values in my choices. For exemple, to do a grading, I want this :

1 - Question ?

Choices =

Value : 1, Text : "Answer 1", Grade : 0
Value : 2, Text : "Answer 2', Grade : 0.5
Value : 3, Text : "Answer 3', Grade : 2

Do you understand ?
Thank you.

**Comment by andrewtelnov** [comment]
Yes, sure. it is possible to have a custom attribute in valueitem. There are some unit tests on that. 
So you want to have basically a json for every value item.
To be honest it is tricky. I do not have an idea, how to make it in general.
Of course, you may create your own property editor and register it. Property editors are created as a plug-in system. But it would not be easy :-(
Anyway, why do you need to have value: 1 and grade: 0, when you may have value: 0 and it should make a trick.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
You may have a value: 1-0, 2-0.5, 3-2 as well.

Thank you,
Andrew

**Comment by grelu** [comment]
Ok thank you @andrewtelnov
