### ISSUE TITLE
How Can I add a new plugin in questions editor modal?

### ISSUE THREAD

**Issue by muhfred** [surveyjs/editor#93]
### Are you requesting a feature, reporting a bug or ask a queation?

question/feature.

### What is the current behavior?

I want to add and bind values in Question Editor modal in choices question?

### What is the expected behavior?

add an [ icon picker](https://victor-valencia.github.io/bootstrap-iconpicker/) next to text and value fields in choices question editor modal. and bind the icons to each choice (answer).
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: chrome
* editor version: 0.12.15

**Comment by andrewtelnov** [comment]
@muhfred Will markdown work for you? It gives you way more freedom.
http://surveyjs.org/examples/jquery/survey-markdown-radiogroup.html

**Comment by muhfred** [comment]
Markdown is great, the thing is that I want the user to insert these icons, How can I do that?

**Comment by andrewtelnov** [comment]
@muhfred You may create your own markdown and use it or use both your markdown and third-party markdown.
So a customer will have to write in the item text: [SMILE] and you will replace the smile with the link on a smile icon on survey.onTextMarkdown event.

Thank you,
Andrew
