### ISSUE TITLE
How to render survey with user answer for review

### ISSUE THREAD

**Issue by krishnathamisetty** [surveyjs/editor#95]
### Are you requesting a feature, reporting a bug or ask a queation?
feature question

### What is the current behavior?
Using survey editor we are able to create survey and user will provide their feedback using test survey. Administrator of survey wants to review each survey with user feedback. So our question how to render survey using user feedback for review in read only mode.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by krishnathamisetty** [comment]
It will be great, if we get sample code for the same.

**Comment by andrewtelnov** [comment]
@krishnathamisetty Here is the demo: http://surveyjs.org/examples/jquery/survey-displaymode.html
`survey.mode = "display";`

Thank you,
Andrew

**Comment by krishnathamisetty** [comment]
great thanks.

How to set default value in Survey Editor for each individual question.
