### ISSUE TITLE
How to set default value in survey editor

### ISSUE THREAD

**Issue by krishnathamisetty** [surveyjs/editor#96]
### Are you requesting a feature, reporting a bug or ask a queation?

question

### What is the current behavior?

Using survey designer we want to set default value. Is this possible for all question types?

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by krishnathamisetty** [comment]
Thanks andrew for your reply. My question related with Survey Design properties window. While designing survey we want to assign default for each different question. Not through programme.

**Comment by andrewtelnov** [comment]
@krishnathamisetty  Ah, you are asking about default value. No, we do not have this functionality yet.

Thank you,
Andrew

**Comment by krishnathamisetty** [comment]
Thanks @andrewtelnov. When can we expect this functionality.

**Comment by andrewtelnov** [comment]
@krishnathamisetty It has been implemented. There is a property question.defaultValue

Thank you,
Andrew
