### ISSUE TITLE
Add a form-group class to the other element

### ISSUE THREAD

**Issue by grelu** [surveyjs/editor#97]
### Are you requesting a feature, reporting a bug or ask a queation?

Question or bug ?

### What is the current behavior?

Impossible to add a bootstrap class form-group to the "other" element.

  <div class='col-xs-6'
         My Other Element
  </div>

### What is the expected behavior?

I want to add a form class like this

<div class='form-group'>
  <div class='col-xs-6'
         My Other Element
  </div>
</div>

Thank !

**Comment by andrewtelnov** [comment]
The issue was fixed: https://github.com/surveyjs/surveyjs/commit/98c1ff8dde488b1ea14fac4521ba5cba940bd29f

**Comment by andrewtelnov** [comment]
@grelu I have added to css.dropdown.other class and make sure library is using this and css.checkbox.other and css.radiogroup.other classes.
Please use this demo to change the classes: http://surveyjs.org/examples/jquery/survey-customcss.html
The changes will be included into the next minor release.

PS: Please create this kind of issues in surveyjs repo.

Thank you,
Andrew

**Comment by grelu** [comment]
@andrewtelnov ok I'm sorry.
Thank you very much.
