### ISSUE TITLE
Editor Survey Designer not showing panels when visibleif criteria are set

### ISSUE THREAD

**Issue by HankIndustry** [surveyjs/editor#98]
### Are you requesting a feature, reporting a bug or ask a question?

Reporting a bug

### What is the current behavior?

When adding "visibleif" criteria to a panel, then saving, the panel disappears from the survey builder.  It is visible if triggered in the survey test, but in the builder the panel is not visible.  On manually removing the invisibleif criteria and setting visible to true in the JSON editor, the panel becomes visible again.

### What is the expected behavior?

The panel should continue to appear in the survey builder even if visibleif criteria is added and saved.

### How would you reproduce the current behavior (if this is a bug)?

1) Create a survey
2) Add a checkbox question
3) Add a panel
4) Add a question to the panel
5) Add visibleif criteria to the panel so it appears when the first item of the checkbox question is selected
6) Save the survey
7) Observe the panel no longer appears in the survey builder, but it does work in the survey test
8) Edit JSON to remove visibleif criteria and set visible to true for the panel
9) Observe the panel is now back in the survey builder

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://dxsurvey.com/published?id=8eac3d9c-9e9d-46ff-aed8-b6a6148e242c

Test code

{
 pages: [
  {
   name: "page1",
   elements: [
    {
     type: "checkbox",
     choices: [
      {
       value: "1",
       text: "Panel 1"
      },
      {
       value: "2",
       text: "Panel 2"
      },
      {
       value: "3",
       text: "Panel 3"
      }
     ],
     name: "question2",
     title: "Panel Selector"
    },
    {
     type: "panel",
     elements: [
      {
       type: "text",
       name: "question1",
       title: "Panel 1 - Question 1"
      }
     ],
     name: "panel1",
     title: "Panel 1",
     visible: false,
     visibleIf: "{question2} = 1"
    }
   ]
  }
 ]
}

### Specify your

* browser: Chrome
* editor version:

**Comment by andrewtelnov** [comment]
@HankIndustry Yes, thank you. I have fixed the bug.
-
Andrew
