### ISSUE TITLE
Request: Copy panel creates non-duplicate question names

### ISSUE THREAD

**Issue by HankIndustry** [surveyjs/editor#99]
### Are you requesting a feature, reporting a bug or ask a question?

Requesting a feature

### What is the current behavior?

When a panel with questions is copied, the question names (question4, question5, etc) remain the same, so if in one panel a selection is made on a question, that same selection will be made on the copied question in the duplicate panel.  Currently one will have to manually rename the copied questions, as well as any subsequent questions created afterwards to avoid overlapping names.

### What is the expected behavior?

It would be nice if there was another copy option (dupicate?) to update duplicated question names with new unique names (question10, question11, etc), effectively creating new, otherwise identical questions.

Additionally, if there is "visibleif" criteria on the questions, it would be very handy if the names could be updated to reference the new questions.  For example, if I have a panel1 with question1 and question2 that I duplicate, I would have panel2 with question3 and question4.  If question2 is triggered by question1, then the new question4 would be triggered by question3.

**Comment by andrewtelnov** [comment]
@HankIndustry Yes, right. I did not test this functionality properly after adding a Panel object. I have added couple unit tests and fix the issue.
It will be really tricky for visibleIf. It makes sense to implement, but there are may important tasks that we have to work on.

Thank you,
Andrew
